// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowUp = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M13.854 7l-5-5h-.707l-5 5 .707.707L8 3.561V14h1V3.56l4.147 4.147.707-.707z" fill="#424242"/></svg>;
export default ArrowUp;
