// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowBoth = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M3 9l2.147 2.146-.707.708-3-3v-.708l3-3 .707.708L3 8h10l-2.146-2.146.707-.708 3 3v.708l-3 3-.707-.707L13 9H3z" fill="#424242"/></svg>;
export default ArrowBoth;
