// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Atlasos = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M12 1.608l12 20.785H0l2.537-4.394h13.852L12 10.396l-1.844 3.193H5.082z"/></svg>;
export default Atlasos;
