// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Naver = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M16.273 12.845L7.376 0H0v24h7.726V11.156L16.624 24H24V0h-7.727v12.845z"/></svg>;
export default Naver;
