// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Printables = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M3.678 4.8L12 9.6v9.6l8.322-4.8V4.8L12 0zM12 19.2l-8.322-4.8V24z"/></svg>;
export default Printables;
