// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Simpleanalytics = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M1.019 13.019h3.849V24h-3.85zm8.943-6.68h3.85V24h-3.85zM19.132 0h3.85v24h-3.85z"/></svg>;
export default Simpleanalytics;
