// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AdOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-ad-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 5h10a2 2 0 012 2v10m-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2"/><path d="M7 15v-4a2 2 0 012-2m2 2v4M7 13h4M17 9v4M16.115 12.131c.33.149.595.412.747.74M3 3l18 18"/></svg>;
export default AdOff;
