// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AdjustmentsSpark = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-adjustments-spark" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 10a2 2 0 104 0 2 2 0 00-4 0M6 4v4M6 12v8M13.879 15.312a2 2 0 10-2.26 2.652M12 4v10M16 7a2 2 0 104 0 2 2 0 00-4 0M18 4v1M18 9v2.5M19 22.5a4.75 4.75 0 013.5-3.5 4.75 4.75 0 01-3.5-3.5 4.75 4.75 0 01-3.5 3.5 4.75 4.75 0 013.5 3.5"/></svg>;
export default AdjustmentsSpark;
