// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AdjustmentsPause = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-adjustments-pause" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 10a2 2 0 104 0 2 2 0 00-4 0M6 4v4M6 12v8M13.627 14.836a2 2 0 10-.62 2.892M12 4v10M12 18v2M16 7a2 2 0 104 0 2 2 0 00-4 0M18 4v1M17 17v5M21 17v5M18 9v4.5"/></svg>;
export default AdjustmentsPause;
