// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlphabetKorean = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-alphabet-korean" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 7h6c0 2.5-1.593 8.474-6 10M16 5v14zM16 12h2"/></svg>;
export default AlphabetKorean;
