// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Archive = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-archive" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 6a2 2 0 012-2h14a2 2 0 012 2v0a2 2 0 01-2 2H5a2 2 0 01-2-2zM5 8v10a2 2 0 002 2h10a2 2 0 002-2V8M10 12h4"/></svg>;
export default Archive;
