// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowLeft = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 12h14M5 12l6 6M5 12l6-6"/></svg>;
export default ArrowLeft;
