// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowRampRight2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrow-ramp-right-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 3v8.707M16 14l4-4-4-4"/><path d="M6 21c0-6.075 4.925-11 11-11h3"/></svg>;
export default ArrowRampRight2;
