// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowLeftCircle = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left-circle" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 12H3M6 9l-3 3 3 3M17 12a2 2 0 104 0 2 2 0 10-4 0"/></svg>;
export default ArrowLeftCircle;
