// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsRightDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrows-right-down" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 17l4 4 4-4"/><path d="M7 21V10a3 3 0 013-3h11"/><path d="M17 11l4-4-4-4"/></svg>;
export default ArrowsRightDown;
