// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowBigUpLines = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrow-big-up-lines" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 12H5.414a1 1 0 01-.707-1.707l6.586-6.586a1 1 0 011.414 0l6.586 6.586A1 1 0 0118.586 12H15v3H9v-3zM9 21h6M9 18h6"/></svg>;
export default ArrowBigUpLines;
