// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsDoubleNwSe = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrows-double-nw-se" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 21L3 10M3 14v-4h4M17 14h4v-4M10 3l11 11"/></svg>;
export default ArrowsDoubleNwSe;
