// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowBounce = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-arrow-bounce" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 18h4M3 8a9 9 0 019 9v1l1.428-4.285a12 12 0 016.018-6.938L20 6.5"/><path d="M15 6h5v5"/></svg>;
export default ArrowBounce;
