// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AwardOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-award-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16.72 12.704a6 6 0 00-8.433-8.418m-1.755 2.24a6 6 0 007.936 7.944"/><path d="M12 15l3.4 5.89 1.598-3.233.707.046m1.108-2.902l-1.617-2.8M6.802 12l-3.4 5.89L7 17.657l1.598 3.232 3.4-5.889M3 3l18 18"/></svg>;
export default AwardOff;
