// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Badge4k = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-badge-4k" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 7a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><path d="M7 9v2a1 1 0 001 1h1M10 9v6M14 9v6M17 9l-2 3 2 3M15 12h-1"/></svg>;
export default Badge4k;
