// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BadgeWc = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-badge-wc" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 7a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><path d="M6.5 9l.5 6 2-4 2 4 .5-6M17 10.5a1.5 1.5 0 00-3 0v3a1.5 1.5 0 003 0"/></svg>;
export default BadgeWc;
