// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Baguette = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-baguette" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5.628 11.283l5.644-5.637c2.665-2.663 5.924-3.747 8.663-1.205l.188.181a2.987 2.987 0 010 4.228L8.836 20.124a3 3 0 01-4.089.135l-.143-.135C1.876 17.4 2.9 14.007 5.628 11.283zM9.5 7.5L11 11M6.5 10.5L8 14M12.5 4.5L14 8"/></svg>;
export default Baguette;
