// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BallVolleyball = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-ball-volleyball" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0M12 12a8 8 0 008 4M7.5 13.5A12 12 0 0016 20M12 12a8 8 0 00-7.464 4.928M12.951 7.353a12 12 0 00-9.88 4.111M12 12a8 8 0 00-.536-8.928M15.549 15.147a12 12 0 001.38-10.611"/></svg>;
export default BallVolleyball;
