// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BallpenOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-ballpen-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 6l7 7-2 2M10 10l-4.172 4.172a2.828 2.828 0 104 4L14 14"/><path d="M16 12l4.414-4.414a2 2 0 000-2.829l-1.171-1.171a2 2 0 00-2.829 0L12 8M4 20l1.768-1.768M3 3l18 18"/></svg>;
export default BallpenOff;
