// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Barcode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-barcode" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 7V6a2 2 0 012-2h2M4 17v1a2 2 0 002 2h2M16 4h2a2 2 0 012 2v1M16 20h2a2 2 0 002-2v-1M5 11h1v2H5zM10 11v2M14 11h1v2h-1zM19 11v2"/></svg>;
export default Barcode;
