// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Barrel = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-barrel" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7.278 4h9.444a2 2 0 011.841 1.22C19.521 7.48 20 9.74 20 12c0 2.26-.479 4.52-1.437 6.78A2 2 0 0116.722 20H7.278a2 2 0 01-1.841-1.22C4.479 16.52 4 14.26 4 12c0-2.26.479-4.52 1.437-6.78A2 2 0 017.278 4z"/><path d="M14 4c.667 2.667 1 5.333 1 8s-.333 5.333-1 8M10 4c-.667 2.667-1 5.333-1 8s.333 5.333 1 8M4.5 16h15M19.5 8h-15"/></svg>;
export default Barrel;
