// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Battery2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-battery-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 7h11a2 2 0 012 2v.5a.5.5 0 00.5.5.5.5 0 01.5.5v3a.5.5 0 01-.5.5.5.5 0 00-.5.5v.5a2 2 0 01-2 2H6a2 2 0 01-2-2V9a2 2 0 012-2M7 10v4M10 10v4"/></svg>;
export default Battery2;
