// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bed = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-bed" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 9a2 2 0 104 0 2 2 0 10-4 0M22 17v-3H2M2 8v9M12 14h10v-2a3 3 0 00-3-3h-7v5z"/></svg>;
export default Bed;
