// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BookmarkMinus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-bookmark-minus" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 17l-6 4V7a4 4 0 014-4h4a4 4 0 014 4v8M16 19h6"/></svg>;
export default BookmarkMinus;
