// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bow = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-bow" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 3h4v4M21 3L6 18M3 18h3v3M16.5 20c1.576-1.576 2.5-4.095 2.5-6.5C19 8.69 15.31 5 10.5 5 8.085 5 5.578 5.913 4 7.5L16.5 20z"/></svg>;
export default Bow;
