// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BracesOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-braces-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5.176 5.177C5.063 5.428 5 5.707 5 6v3c0 1.657-.895 3-2 3 1.105 0 2 1.343 2 3v3a2 2 0 002 2M17 4a2 2 0 012 2v3c0 1.657.895 3 2 3-1.105 0-2 1.343-2 3m-.176 3.821A2 2 0 0117 20M3 3l18 18"/></svg>;
export default BracesOff;
