// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandXbox = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-xbox" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0M6.5 5c7.72 2.266 10.037 7.597 12.5 12.5M17.5 5C9.78 7.266 7.463 12.597 5 17.5"/></svg>;
export default BrandXbox;
