// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandBootstrap = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-bootstrap" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M2 12a2 2 0 002-2V6a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 002 2M2 12a2 2 0 012 2v4a2 2 0 002 2h12a2 2 0 002-2v-4a2 2 0 012-2"/><path d="M9 16V8h3.5a2 2 0 110 4H9h4a2 2 0 110 4H9z"/></svg>;
export default BrandBootstrap;
