// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandSketch = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-sketch" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3.262 10.878l8 8.789c.4.44 1.091.44 1.491 0l8-8.79c.313-.344.349-.859.087-1.243L17.303 4.44a1 1 0 00-.823-.436H7.554a1 1 0 00-.823.436l-3.54 5.192c-.263.385-.227.901.087 1.246z"/></svg>;
export default BrandSketch;
