// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandChrome = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-chrome" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0"/><path d="M9 12a3 3 0 106 0 3 3 0 10-6 0M12 9h8.4M14.598 13.5l-4.2 7.275M9.402 13.5l-4.2-7.275"/></svg>;
export default BrandChrome;
