// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandLinktree = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-linktree" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 10h16M6.5 4.5l11 11M6.5 15.5l11-11M12 10V2M12 15v7"/></svg>;
export default BrandLinktree;
