// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandRevolut = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-revolut" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 10h3v10H5z"/><path d="M14.5 4H5v3h9.4a1.5 1.5 0 010 3H11v4l4 6h4l-5-7h.5a4.5 4.5 0 100-9z"/></svg>;
export default BrandRevolut;
