// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandAndroid = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-android" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 10v6M20 10v6M7 9h10v8a1 1 0 01-1 1H8a1 1 0 01-1-1V9a5 5 0 0110 0M8 3l1 2M16 3l-1 2M9 18v3M15 18v3"/></svg>;
export default BrandAndroid;
