// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandTerraform = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-terraform" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 15.5L3.524 9.284A1 1 0 013 8.404V4.35a1.35 1.35 0 012.03-1.166L15 9v10.65a1.35 1.35 0 01-2.03 1.166l-3.474-2.027A1 1 0 019 17.926V6M15 15.5l5.504-3.21a1 1 0 00.496-.864V7.85a1.35 1.35 0 00-2.03-1.166L15 9"/></svg>;
export default BrandTerraform;
