// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandSteam = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-steam" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16.5 5a4.5 4.5 0 11-.653 8.953L11.5 16.962V17a3 3 0 01-2.824 3H8.5a3 3 0 01-2.94-2.402L3 16.5V13l3.51 1.755a2.989 2.989 0 012.834-.635l2.727-3.818A4.5 4.5 0 0116.5 5z"/><circle cx="16.5" cy="9.5" r="1" fill="currentColor"/></svg>;
export default BrandSteam;
