// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandLeetcode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-leetcode" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 13h7.5M9.424 7.268l4.999-4.999M16.633 16.644l-2.402 2.415a3.189 3.189 0 01-4.524 0l-3.77-3.787a3.223 3.223 0 010-4.544l3.77-3.787a3.189 3.189 0 014.524 0l2.302 2.313"/></svg>;
export default BrandLeetcode;
