// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandCypress = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-cypress" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19.48 17.007A9 9 0 1012 21a2.08 2.08 0 001.974-1.423L17.5 9M13.5 9l2 6M10.764 9.411a3 3 0 10-.023 5.19"/></svg>;
export default BrandCypress;
