// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandSnowflake = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-snowflake" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 21v-5.5l4.5 2.5M10 21v-5.5L5.5 18M3.5 14.5L8 12 3.5 9.5M20.5 9.5L16 12l4.5 2.5M10 3v5.5L5.5 6M14 3v5.5L18.5 6M12 11l1 1-1 1-1-1z"/></svg>;
export default BrandSnowflake;
