// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandFiverr = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-fiverr" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 3h-2a6 6 0 00-6 6H4v4h3v8h4v-7h4v7h4V10h-8V8.967A1.967 1.967 0 0113 7h2V3z"/></svg>;
export default BrandFiverr;
