// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandAppgallery = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-appgallery" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 8a4 4 0 014-4h8a4 4 0 014 4v8a4 4 0 01-4 4H8a4 4 0 01-4-4zM9 8a3 3 0 006 0"/></svg>;
export default BrandAppgallery;
