// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandAo3 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-ao3" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M2 5c7.109 4.1 10.956 10.131 12 14 1.074-4.67 4.49-8.94 8-11"/><path d="M12 8a2 2 0 104 0 2 2 0 10-4 0M7 9c-.278 5.494-2.337 7.33-4 10 4.013-2 6.02-5 15.05-5 4.012 0 3.51 2.5 1 3 2 .5 2.508 5-2.007 2"/></svg>;
export default BrandAo3;
