// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandAbstract = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-abstract" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 3c7.2 0 9 1.8 9 9s-1.8 9-9 9-9-1.8-9-9 1.8-9 9-9z"/><path d="M8 13.5a2.5 2.5 0 105 0 2.5 2.5 0 10-5 0"/><path d="M8 8h8v8"/></svg>;
export default BrandAbstract;
