// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrandAzure = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-azure" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 7.5L2 17h4l6-15zM22 20L15 5l-3 7 4 5-8 3z"/></svg>;
export default BrandAzure;
