// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BuildingBurjAlArab = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-building-burj-al-arab" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 21h18M7 21V3M7 4c5.675.908 10 5.613 10 11.28A11 11 0 0115.395 21M5 9h12M7 13h4M7 17h4"/></svg>;
export default BuildingBurjAlArab;
