// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Certificate2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-certificate-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 15a3 3 0 106 0 3 3 0 10-6 0M10 7h4"/><path d="M10 18v4l2-1 2 1v-4"/><path d="M10 19H8a2 2 0 01-2-2V5a2 2 0 012-2h8a2 2 0 012 2v12a2 2 0 01-2 2h-2"/></svg>;
export default Certificate2;
