// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartCohort = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-chart-cohort" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 9h18V3H3v18h6V3"/><path d="M3 15h12V3"/></svg>;
export default ChartCohort;
