// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChessRook = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-chess-rook" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8 16l-1.447.724a1 1 0 00-.553.894V20h12v-2.382a1 1 0 00-.553-.894L16 16H8zM8 16l1-9h6l1 9M6 4l.5 3h11l.5-3M10 4v3M14 4v3"/></svg>;
export default ChessRook;
