// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CircleLetterS = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-circle-letter-s" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0"/><path d="M10 15a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 00-1-1h-2a1 1 0 01-1-1V9a1 1 0 011-1h2a1 1 0 011 1"/></svg>;
export default CircleLetterS;
