// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClearFormatting = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clear-formatting" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 15l4 4m0-4l-4 4M7 6V5h11v1M7 19h4M13 5L9 19"/></svg>;
export default ClearFormatting;
