// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockRecord = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clock-record" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M21 12.3a9 9 0 10-8.683 8.694M12 7v5l2 2M16 19a3 3 0 106 0 3 3 0 10-6 0"/></svg>;
export default ClockRecord;
