// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockHeart = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clock-heart" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.956 11.107a9 9 0 10-9.579 9.871M18 22l3.35-3.284a2.143 2.143 0 00.005-3.071 2.242 2.242 0 00-3.129-.006l-.224.22-.223-.22a2.242 2.242 0 00-3.128-.006 2.143 2.143 0 00-.006 3.071L18 22z"/><path d="M12 7v5l.5.5"/></svg>;
export default ClockHeart;
