// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockMinus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clock-minus" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.477 15.022a9 9 0 10-7.998 5.965M12 7v5l3 3M16 19h6"/></svg>;
export default ClockMinus;
