// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockCheck = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clock-check" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.942 13.021a9 9 0 10-9.407 7.967M12 7v5l3 3M15 19l2 2 4-4"/></svg>;
export default ClockCheck;
