// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockPin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-clock-pin" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.971 11.278a9 9 0 10-8.313 9.698M12 7v5l1.5 1.5"/><path d="M21.121 20.121a3 3 0 10-4.242 0c.418.419 1.125 1.045 2.121 1.879 1.051-.89 1.759-1.516 2.121-1.879zM19 18v.01"/></svg>;
export default ClockPin;
