// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CloudStorm = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-cloud-storm" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 18a4.6 4.4 0 010-9 5 4.5 0 0111 2h1a3.5 3.5 0 010 7h-1"/><path d="M13 14l-2 4h3l-2 4"/></svg>;
export default CloudStorm;
