// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CodePlus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-code-plus" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 12h6M12 9v6M6 19a2 2 0 01-2-2v-4l-1-1 1-1V7a2 2 0 012-2M18 19a2 2 0 002-2v-4l1-1-1-1V7a2 2 0 00-2-2"/></svg>;
export default CodePlus;
