// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Command = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-command" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 9a2 2 0 112-2v10a2 2 0 11-2-2h10a2 2 0 11-2 2V7a2 2 0 112 2H7"/></svg>;
export default Command;
