// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ConeOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-cone-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.396 16.384L12.87 2.507a1 1 0 00-1.74 0L9.504 5.505M8.097 8.099L3 17.497v.5C3 19.657 7.03 21 12 21c3.202 0 6.014-.558 7.609-1.398M3 3l18 18"/></svg>;
export default ConeOff;
