// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CraneOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-crane-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 21h6M9 21V9M9 5V3L8 4M6 6L3 9h6M13 9h8M9 3l10 6M17 9v4a2 2 0 012 2m-2 2a2 2 0 01-2-2M3 3l18 18"/></svg>;
export default CraneOff;
