// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CrystalBall = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-crystal-ball" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6.73 17.018a8 8 0 1110.54 0M5 19a2 2 0 002 2h10a2 2 0 100-4H7a2 2 0 00-2 2zM11 7a3 3 0 00-3 3"/></svg>;
export default CrystalBall;
