// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Cup = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-cup" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 11h14V8H5zM17.5 11L16 21H8L6.5 11M6 8V7a2 2 0 012-2h8a2 2 0 012 2v1M15 5V3"/></svg>;
export default Cup;
