// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyXrp = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-xrp" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 5l3.585 3.585a4.83 4.83 0 006.83 0L19 5M5 19l3.585-3.585a4.83 4.83 0 016.83 0L19 18.999"/></svg>;
export default CurrencyXrp;
