// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyAfghani = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-afghani" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 13h-3.5A3.5 3.5 0 1115 9.5V16H8M12 3v.01M12 19v2"/></svg>;
export default CurrencyAfghani;
