// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyPeso = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-peso" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8 19V5h3.5a4.5 4.5 0 110 9H8M18 8H6M18 11H6"/></svg>;
export default CurrencyPeso;
