// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyYenOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-yen-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 19v-7m5-7l-3.328 4.66M8 17h8M8 13h5M3 3l18 18"/></svg>;
export default CurrencyYenOff;
