// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyReal = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-real" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M21 6h-4a3 3 0 000 6h1a3 3 0 010 6h-4M4 18V6h3a3 3 0 110 6H4c5.5 0 5 4 6 6M18 6V4M17 20v-2"/></svg>;
export default CurrencyReal;
