// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyForint = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-forint" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 4H7a3 3 0 00-3 3v12M10 11H4M16 4v13a2 2 0 002 2h2M19 9h-5"/></svg>;
export default CurrencyForint;
