// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyNaira = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-currency-naira" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 18V7.052a1.05 1.05 0 011.968-.51l6.064 10.916a1.05 1.05 0 001.968-.51V6M5 10h14M5 14h14"/></svg>;
export default CurrencyNaira;
