// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceTvOld = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-tv-old" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 9a2 2 0 012-2h14a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2zM16 3l-4 4-4-4M15 7v13M18 15v.01M18 12v.01"/></svg>;
export default DeviceTvOld;
