// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceIpadHorizontalCode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-ipad-horizontal-code" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 20H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v7M9 17h2.5M20 21l2-2-2-2M17 17l-2 2 2 2"/></svg>;
export default DeviceIpadHorizontalCode;
