// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceComputerCameraOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-computer-camera-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6.15 6.153a7 7 0 009.696 9.696m2-2a7 7 0 00-9.699-9.695"/><path d="M9.13 9.122a3 3 0 003.743 3.749m2-2a3 3 0 00-3.737-3.736M8 16l-2.091 3.486A1 1 0 006.766 21h10.468a1 1 0 00.857-1.514L16 16M3 3l18 18"/></svg>;
export default DeviceComputerCameraOff;
