// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceWatchShare = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-watch-share" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12.5 18H9a3 3 0 01-3-3V9a3 3 0 013-3h6a3 3 0 013 3v4M9 18v3h3M9 6V3h6v3M16 22l5-5M21 21.5V17h-4.5"/></svg>;
export default DeviceWatchShare;
