// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceProjector = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-projector" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8 9a5 5 0 1010 0A5 5 0 008 9"/><path d="M9 6H5a2 2 0 00-2 2v8a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2h-2M6 15h1M7 18l-1 2M18 18l1 2"/></svg>;
export default DeviceProjector;
