// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceImacX = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-imac-x" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 17H4a1 1 0 01-1-1V4a1 1 0 011-1h16a1 1 0 011 1v9M3 13h18M8 21h5M10 17l-.5 4M22 22l-5-5M17 22l5-5"/></svg>;
export default DeviceImacX;
