// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceIpadHorizontalSearch = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-device-ipad-horizontal-search" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11.5 20H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v5.5M9 17h2"/><path d="M15 18a3 3 0 106 0 3 3 0 10-6 0M20.2 20.2L22 22"/></svg>;
export default DeviceIpadHorizontalSearch;
