// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DiscountOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-discount-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 15l3-3m2-2l1-1M9.148 9.145A.498.498 0 009.5 10a.5.5 0 00.35-.142M14.148 14.145A.498.498 0 0014.5 15a.5.5 0 00.35-.142"/><path d="M5.641 5.631A9 9 0 1018.36 18.369m1.68-2.318A9 9 0 007.966 3.953M3 3l18 18"/></svg>;
export default DiscountOff;
