// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Discount = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-discount" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 15l6-6"/><circle cx="9.5" cy="9.5" r=".5" fill="currentColor"/><circle cx="14.5" cy="14.5" r=".5" fill="currentColor"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0"/></svg>;
export default Discount;
