// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Disc = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-disc" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0"/><path d="M11 12a1 1 0 102 0 1 1 0 10-2 0M7 12a5 5 0 015-5M12 17a5 5 0 005-5"/></svg>;
export default Disc;
