// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DropletQuestion = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-droplet-question" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M18.064 10.877l-4.89-7.26c-.42-.625-1.287-.803-1.936-.397a1.376 1.376 0 00-.41.397l-4.893 7.26C4.24 13.715 4.9 17.318 7.502 19.423c2.203 1.782 5.259 2.056 7.723.82M19 22v.01M19 19a2.003 2.003 0 00.914-3.782 1.98 1.98 0 00-2.414.483"/></svg>;
export default DropletQuestion;
