// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Eraser = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-eraser" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 20H8.5l-4.21-4.3a1 1 0 010-1.41l10-10a1 1 0 011.41 0l5 5a1 1 0 010 1.41L11.5 20M18 13.3L11.7 7"/></svg>;
export default Eraser;
