// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EyeCode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-eye-code" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 12a2 2 0 104 0 2 2 0 00-4 0"/><path d="M11.11 17.958C7.901 17.651 5.2 15.665 3 12c2.4-4 5.4-6 9-6 3.6 0 6.6 2 9 6-.21.352-.427.688-.647 1.008M20 21l2-2-2-2M17 17l-2 2 2 2"/></svg>;
export default EyeCode;
