// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Fence = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-fence" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 12v4h16v-4zM6 16v4h4v-4m0-4V6L8 4 6 6v6M14 16v4h4v-4m0-4V6l-2-2-2 2v6"/></svg>;
export default Fence;
