// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Ferry = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-ferry" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 17h14.08a3 3 0 002.5-1.34L21.721 13H4.5zM14.556 7.959l-.382-1.415M6.107 12.675L7.491 8h8l2.675 4.598"/></svg>;
export default Ferry;
