// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilterDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-filter-down" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 20l-3 1v-8.5L4.52 7.572A2 2 0 014 6.227V4h16v2.172a2 2 0 01-.586 1.414L15 12v3M19 16v6M22 19l-3 3-3-3"/></svg>;
export default FilterDown;
