// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Fish = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-fish" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16.69 7.44A6.973 6.973 0 0015 12a6.97 6.97 0 001.699 4.571"/><path d="M2 9.504c7.715 8.647 14.75 10.265 20 2.498C16.75 4.241 9.715 5.86 2 14.506M18 11v.01M11.5 10.5c-.667 1-.667 2 0 3"/></svg>;
export default Fish;
