// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Flask2Off = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-flask-2-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6.1 15H15M17.742 17.741A6 6 0 0115.318 21H8.683A6 6 0 0110 10.34v-.326M10 6V3h4v7m.613.598a6 6 0 012.801 2.817M9 3h6M3 3l18 18"/></svg>;
export default Flask2Off;
