// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GenderThird = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-gender-third" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 12a5 5 0 1010 0 5 5 0 00-10 0zM11 12H8M8 12L3 8v8z"/></svg>;
export default GenderThird;
