// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Ghost3 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-ghost-3" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 11a7 7 0 0114 0v7a1.78 1.78 0 01-3.1 1.4 1.65 1.65 0 00-2.6 0 1.65 1.65 0 01-2.6 0 1.65 1.65 0 00-2.6 0A1.78 1.78 0 015 18v-7M10 10h.01M14 10h.01"/></svg>;
export default Ghost3;
