// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Globe = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-globe" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 9a4 4 0 108 0 4 4 0 00-8 0M5.75 15A8.015 8.015 0 1015 2M11 17v4M7 21h8"/></svg>;
export default Globe;
