// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Grill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-grill" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 8H5a6 6 0 006 6h2a6 6 0 006-5.775V8zM17 20a2 2 0 110-4 2 2 0 010 4zM15 14l1 2M9 14l-3 6M15 18H7M15 5V4M12 5V4M9 5V4"/></svg>;
export default Grill;
