// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const H1 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-h-1" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 18v-8l-2 2M4 6v12M12 6v12M11 18h2M3 18h2M4 12h8M3 6h2M11 6h2"/></svg>;
export default H1;
