// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HandFingerLeft = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hand-finger-left" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 8H3.5a1.5 1.5 0 000 3H11M10.5 11h-2a1.5 1.5 0 100 3H11M9.5 14a1.5 1.5 0 000 3H11"/><path d="M10.5 17a1.5 1.5 0 000 3H15a6 6 0 006-6v-2 .208a6 6 0 00-2.7-5.012L18 7q-.718-.468-5.728-3.286a1.5 1.5 0 00-2.022.536 1.87 1.87 0 00.28 2.28L12 8"/></svg>;
export default HandFingerLeft;
