// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hash = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hash" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 9h14M5 15h14M11 4L7 20M17 4l-4 16"/></svg>;
export default Hash;
