// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hdr = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hdr" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 16V8M7 8v8M3 12h4M10 8v8h2a2 2 0 002-2v-4a2 2 0 00-2-2h-2zM17 12h2a2 2 0 100-4h-2v8m4 0l-3-4"/></svg>;
export default Hdr;
