// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HeartDiscount = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-heart-discount" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 19l-1 1-7.5-7.428A5 5 0 1112 6.006a5 5 0 117.5 6.572M16 21l5-5M21 21v.01M16 16v.01"/></svg>;
export default HeartDiscount;
