// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HelmetOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-helmet-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8.633 4.654a9 9 0 0111.718 11.7m-1.503 2.486A9.008 9.008 0 0117.656 20H6.344a9 9 0 01-.185-13.847"/><path d="M20 9h-7m-2.768 1.246c.507 2 1.596 3.418 3.268 4.254.524.262 1.07.49 1.64.683M3 3l18 18"/></svg>;
export default HelmetOff;
