// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hemisphere = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hemisphere" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 9a9 3 0 1018 0A9 3 0 103 9M3 9a9 9 0 0018 0"/></svg>;
export default Hemisphere;
