// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hierarchy2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hierarchy-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 3h4v4h-4zM3 17h4v4H3zM17 17h4v4h-4zM7 17l5-4 5 4M12 7v6"/></svg>;
export default Hierarchy2;
