// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HomeCog = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-home-cog" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 21v-6a2 2 0 012-2h1.6"/><path d="M20 11l-8-8-9 9h2v7a2 2 0 002 2h4.159M16 18a2 2 0 104 0 2 2 0 10-4 0M18 14.5V16M18 20v1.5M21.032 16.25l-1.299.75M16.27 19l-1.3.75M14.97 16.25l1.3.75M19.733 19l1.3.75"/></svg>;
export default HomeCog;
