// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HomeUp = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-home-up" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 21v-6a2 2 0 012-2h2c.641 0 1.212.302 1.578.771"/><path d="M20.136 11.136L12 3l-9 9h2v7a2 2 0 002 2h6.344M19 22v-6M22 19l-3-3-3 3"/></svg>;
export default HomeUp;
