// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HotelService = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-hotel-service" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8.5 10A1.5 1.5 0 017 8.5a5.5 5.5 0 0111 0V19a2 2 0 01-2 2H9a2 2 0 01-2-2v-2c0-1.38.71-2.444 1.88-3.175l4.424-2.765C14.359 10.4 15 9.744 15 8.5a2.5 2.5 0 10-5 0A1.5 1.5 0 018.5 10z"/></svg>;
export default HotelService;
