// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HttpGet = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-http-get" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 8H5a2 2 0 00-2 2v4a2 2 0 002 2h2v-4H6M14 8h-4v8h4M10 12h2.5M17 8h4M19 8v8"/></svg>;
export default HttpGet;
