// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LanguageKatakana = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-language-katakana" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 5h6.586a1 1 0 01.707 1.707L11 8M8 8c0 1.5.5 3-2 5M12 20l4-9 4 9M19.1 18h-6.2"/></svg>;
export default LanguageKatakana;
