// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LayersLinked = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-layers-linked" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 8.268A2 2 0 0120 10v8a2 2 0 01-2 2h-8a2 2 0 01-2-2v-8a2 2 0 012-2h3"/><path d="M5 15.734A2 2 0 014 14V6a2 2 0 012-2h8a2 2 0 012 2v8a2 2 0 01-2 2h-3"/></svg>;
export default LayersLinked;
