// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LayoutAlignTop = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-layout-align-top" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 4h16M9 10a2 2 0 012-2h2a2 2 0 012 2v8a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>;
export default LayoutAlignTop;
