// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterA = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-a" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 20V8a4 4 0 014-4h2a4 4 0 014 4v12M7 13h10"/></svg>;
export default LetterA;
