// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterCaseToggle = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-case-toggle" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 15.5a3.5 3.5 0 107 0 3.5 3.5 0 10-7 0M14 19V8.5a3.5 3.5 0 017 0V19M14 13h7M10 12v7"/></svg>;
export default LetterCaseToggle;
