// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterTSmall = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-t-small" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 8h4M12 8v8"/></svg>;
export default LetterTSmall;
