// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterE = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-e" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 4H7v16h10M7 12h8"/></svg>;
export default LetterE;
