// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterG = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-g" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M18 9a5 5 0 00-5-5h-2a5 5 0 00-5 5v6a5 5 0 005 5h2a5 5 0 005-5v-2h-4"/></svg>;
export default LetterG;
