// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterRSmall = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-letter-r-small" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 12h2a2 2 0 100-4h-2v8m4 0l-3-4"/></svg>;
export default LetterRSmall;
