// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LocationX = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-location-x" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13.5 21l-.224-.448L10 14l-7-3.5a.55.55 0 010-1L21 3l-3.622 10.03M22 22l-5-5M17 22l5-5"/></svg>;
export default LocationX;
