// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Login2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-login-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 8V6a2 2 0 012-2h7a2 2 0 012 2v12a2 2 0 01-2 2h-7a2 2 0 01-2-2v-2"/><path d="M3 12h13l-3-3M13 15l3-3"/></svg>;
export default Login2;
