// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MailboxOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mailbox-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 21v-6.5a3.5 3.5 0 00-7 0V21h18m0-4v-2a4 4 0 00-4-4h-2m-4 0H6.5M12 8V3h4l2 2-2 2h-4M6 15h1M3 3l18 18"/></svg>;
export default MailboxOff;
