// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MapDiscount = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-map-discount" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 19l-4-2-6 3V7l6-3 6 3 6-3v8.5M9 4v13M15 7v5.5M16 21l5-5M21 21v.01M16 16v.01"/></svg>;
export default MapDiscount;
