// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Massage = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-massage" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 17a1 1 0 102 0 1 1 0 10-2 0M8 5a1 1 0 102 0 1 1 0 10-2 0M4 22l4-2v-3h12M11 20h9M8 14l3-2 1-4c3 1 3 4 3 6"/></svg>;
export default Massage;
