// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MathCtg = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-math-ctg" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 8h4M21 8h-2a2 2 0 00-2 2v4a2 2 0 002 2h2v-4h-1M12 8v8M7 10a2 2 0 10-4 0v4a2 2 0 104 0"/></svg>;
export default MathCtg;
