// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MathXy = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-math-xy" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 9l3 5.063M4 9l6 6M4 15l6-6M20 9l-4.8 9"/></svg>;
export default MathXy;
