// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MathSec = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-math-sec" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 15c.345.6 1.258 1 2 1a2 2 0 100-4 2 2 0 110-4c.746 0 1.656.394 2 1M21 10a2 2 0 10-4 0v4a2 2 0 104 0M14 8h-4v8h4M10 12h2.5"/></svg>;
export default MathSec;
