// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Medal2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-medal-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 3h6l3 7-6 2-6-2zM12 12L9 3M15 11l-3-8M12 19.5L9 21l.5-3.5-2-2 3-.5 1.5-3 1.5 3 3 .5-2 2L15 21z"/></svg>;
export default Medal2;
