// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Melon = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-melon" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20 10c0 5.523-4.477 10-10 10a9.967 9.967 0 01-6.984-2.842l4.343-4.153a4 4 0 005.76-5.51l4.342-4.153A9.963 9.963 0 0120 10z"/></svg>;
export default Melon;
