// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MenuOrder = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-menu-order" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 10h16M4 14h16M9 18l3 3 3-3M9 6l3-3 3 3"/></svg>;
export default MenuOrder;
