// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Message2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-message-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8 9h8M8 13h6M9 18H6a3 3 0 01-3-3V7a3 3 0 013-3h12a3 3 0 013 3v8a3 3 0 01-3 3h-3l-3 3-3-3z"/></svg>;
export default Message2;
