// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MobiledataOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mobiledata-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16 12V4M8 20v-8M13 7l3-3 3 3M5 17l3 3 3-3M3 3l18 18"/></svg>;
export default MobiledataOff;
