// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoodAnnoyed = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mood-annoyed" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 21a9 9 0 110-18 9 9 0 010 18zM15 14c-2 0-3 1-3.5 2.05M9 10h-.01M15 10h-.01"/></svg>;
export default MoodAnnoyed;
