// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoodEdit = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mood-edit" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.955 11.104a9 9 0 10-9.895 9.847M9 10h.01M15 10h.01"/><path d="M9.5 15c.658.672 1.56 1 2.5 1 .126 0 .251-.006.376-.018M18.42 15.61a2.1 2.1 0 012.97 2.97L18 22h-3v-3l3.42-3.39z"/></svg>;
export default MoodEdit;
