// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoodPlus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mood-plus" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20.985 12.528a9 9 0 10-8.45 8.456M16 19h6M19 16v6M9 10h.01M15 10h.01"/><path d="M9.5 15c.658.64 1.56 1 2.5 1s1.842-.36 2.5-1"/></svg>;
export default MoodPlus;
