// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoodSmileDizzy = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mood-smile-dizzy" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12a9 9 0 1018 0 9 9 0 10-18 0M14.5 15a3.5 3.5 0 01-5 0M8 9l2 2M10 9l-2 2M14 9l2 2M16 9l-2 2"/></svg>;
export default MoodSmileDizzy;
