// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoodBitcoin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mood-bitcoin" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 21v-6m2 0v-1.5m0 9V21m-2-3h3m-1 0h.5a1.5 1.5 0 010 3H16m3-3h.5a1.5 1.5 0 000-3H16M20.87 10.48a9 9 0 10-7.876 10.465M9 10h.01M15 10h.01"/><path d="M9.5 15c.658.64 1.56 1 2.5 1 .357 0 .709-.052 1.043-.151"/></svg>;
export default MoodBitcoin;
