// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Mountain = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-mountain" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 20h18L14.079 5.388a2.3 2.3 0 00-4.158 0L3 20z"/><path d="M7.5 11l2 2.5L12 11l2 3 2.5-2"/></svg>;
export default Mountain;
