// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NavigationDollar = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-navigation-dollar" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15.945 11.551L12 3 4.03 20.275c-.07.2-.017.424.135.572.15.148.374.193.57.116L12 18.5l1.594.54M21 15h-2.5a1.5 1.5 0 000 3h1a1.5 1.5 0 010 3H17M19 21v1m0-8v1"/></svg>;
export default NavigationDollar;
