// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NavigationDiscount = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-navigation-discount" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16.43 12.603L12 3 4.03 20.275c-.07.2-.017.424.135.572.15.148.374.193.57.116L12 18.5l1.272.431M16 21l5-5M21 21v.01M16 16v.01"/></svg>;
export default NavigationDiscount;
