// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Number51Small = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-number-51-small" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 8h1v8M7 15a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 00-1-1H7V8h4"/></svg>;
export default Number51Small;
