// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Number70Small = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-number-70-small" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 10v4a2 2 0 104 0v-4a2 2 0 10-4 0M6 8h4l-2 8"/></svg>;
export default Number70Small;
