// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PackageOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-package-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M8.812 4.793L12 3l8 4.5V16m-2.282 1.784L12 21l-8-4.5v-9l2.223-1.25M14.543 10.57L20 7.5M12 12v9M12 12L4 7.5M16 5.25l-4.35 2.447M9.086 9.139L8 9.75M3 3l18 18"/></svg>;
export default PackageOff;
