// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Pepper = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-pepper" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 11c0 2.21-2.239 4-5 4s-5-1.79-5-4a8 8 0 1016 0 3 3 0 00-6 0M16 8c0-2 2-4 4-4"/></svg>;
export default Pepper;
