// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PhotoSearch = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-photo-search" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 8h.01M11.5 21H6a3 3 0 01-3-3V6a3 3 0 013-3h12a3 3 0 013 3v5.5"/><path d="M15 18a3 3 0 106 0 3 3 0 10-6 0M20.2 20.2L22 22M3 16l5-5c.928-.893 2.072-.893 3 0l2 2"/></svg>;
export default PhotoSearch;
