// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PigMoney = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-pig-money" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 11v.01M5.173 8.378a3 3 0 114.656-1.377"/><path d="M16 4v3.803A6.019 6.019 0 0118.658 11h1.341a1 1 0 011 1v2a1 1 0 01-1 1h-1.342c-.336.95-.907 1.8-1.658 2.473V19.5a1.5 1.5 0 01-3 0v-.583a6.04 6.04 0 01-1 .083h-4a6.04 6.04 0 01-1-.083v.583a1.5 1.5 0 01-3 0v-2.027A6 6 0 018.999 7h2.5l4.5-3h0z"/></svg>;
export default PigMoney;
