// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayerPause = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-player-pause" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 6a1 1 0 011-1h2a1 1 0 011 1v12a1 1 0 01-1 1H7a1 1 0 01-1-1zM14 6a1 1 0 011-1h2a1 1 0 011 1v12a1 1 0 01-1 1h-2a1 1 0 01-1-1z"/></svg>;
export default PlayerPause;
