// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayVolleyball = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-play-volleyball" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 4a1 1 0 102 0 1 1 0 00-2 0"/><path d="M20.5 10a.5.5 0 100-1 .5.5 0 000 1z" fill="currentColor"/><path d="M2 16l5 1 .5-2.5M11.5 21l2.5-5.5L8.5 12 12 8l3 4 4 2"/></svg>;
export default PlayVolleyball;
