// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayBasketball = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-play-basketball" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 4a1 1 0 102 0 1 1 0 00-2 0M5 21l3-3 .75-1.5M14 21v-4l-4-3 .5-6"/><path d="M5 12l1-3 4.5-1 3.5 3 4 1"/><path d="M18.5 16a.5.5 0 100-1 .5.5 0 000 1z" fill="currentColor"/></svg>;
export default PlayBasketball;
