// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayerEject = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-player-eject" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 12h14l-7-8zM5 17a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H6a1 1 0 01-1-1z"/></svg>;
export default PlayerEject;
