// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Playlist = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-playlist" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 17a3 3 0 106 0 3 3 0 10-6 0M17 17V4h4M13 5H3M3 9h10M9 13H3"/></svg>;
export default Playlist;
