// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayCardJ = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-play-card-j" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 5v14a2 2 0 01-2 2H7a2 2 0 01-2-2V5a2 2 0 012-2h10a2 2 0 012 2M8 6h.01M16 18h.01"/><path d="M10 9h4v4a2 2 0 11-4 0"/></svg>;
export default PlayCardJ;
