// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Podium = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-podium" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 8h14l-.621 2.485A2 2 0 0116.439 12H7.561a2 2 0 01-1.94-1.515L5 8zM7 8V6a3 3 0 013-3M8 12l1 9M16 12l-1 9M7 21h10"/></svg>;
export default Podium;
