// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PointOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-point-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9.15 9.194a4 4 0 005.697 5.617M16 12a4 4 0 00-4-4M3 3l18 18"/></svg>;
export default PointOff;
