// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PointerQuestion = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-pointer-question" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15.062 12.506l-.284-.284 3.113-2.09a1.2 1.2 0 00-.309-2.228L4 4l3.904 13.563a1.2 1.2 0 002.228.308l2.09-3.093 1.278 1.278M19 22v.01M19 19a2.003 2.003 0 00.914-3.782 1.98 1.98 0 00-2.414.483"/></svg>;
export default PointerQuestion;
