// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const QuoteOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-quote-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 11H6a1 1 0 01-1-1V7a1 1 0 011-1m4 4v3c0 2.667-1.333 4.333-4 5M19 11h-4m-1-1V7a1 1 0 011-1h3a1 1 0 011 1v6c0 .66-.082 1.26-.245 1.798m-1.653 2.29c-.571.4-1.272.704-2.102.912M3 3l18 18"/></svg>;
export default QuoteOff;
