// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ReceiptOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-receipt-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 21V5m2-2h10a2 2 0 012 2v10m0 4.01V21l-3-2-2 2-2-2-2 2-2-2-3 2M11 7h4M9 11h2M13 15h2M15 11v.01M3 3l18 18"/></svg>;
export default ReceiptOff;
