// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RewindForward20 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-rewind-forward-20" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5.007 16.478A6 6 0 019 6h11M15 15.5v3a1.5 1.5 0 003 0v-3a1.5 1.5 0 00-3 0z"/><path d="M17 9l3-3-3-3M9 14h2a1 1 0 011 1v1a1 1 0 01-1 1h-1a1 1 0 00-1 1v1a1 1 0 001 1h2"/></svg>;
export default RewindForward20;
