// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RewindForward5 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-rewind-forward-5" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 18A6 6 0 119 6h11M13 20h2a1 1 0 001-1v-1a1 1 0 00-1-1h-2v-3h3"/><path d="M17 9l3-3-3-3"/></svg>;
export default RewindForward5;
