// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Rollercoaster = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-rollercoaster" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 21a5.55 5.55 0 005.265-3.795L9 15a8.775 8.775 0 018.325-6H21M20 9v12M8 21v-3M12 21V11M16 9.5V21M15 3h5v3h-5zM6 8l4-3 2 2.5-4 3-1.8-.5z"/></svg>;
export default Rollercoaster;
