// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RouteX = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-route-x" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 17l4 4M7 17l-4 4M17 3l4 4M21 3l-4 4M11 19h5.5a3.5 3.5 0 000-7h-8a3.5 3.5 0 010-7H13"/></svg>;
export default RouteX;
