// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Route = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-route" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 19a2 2 0 104 0 2 2 0 00-4 0M19 7a2 2 0 100-4 2 2 0 000 4zM11 19h5.5a3.5 3.5 0 000-7h-8a3.5 3.5 0 010-7H13"/></svg>;
export default Route;
