// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RouterOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-router-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 13h2a2 2 0 012 2v2m-.588 3.417c-.362.36-.861.583-1.412.583H5a2 2 0 01-2-2v-4a2 2 0 012-2h8M17 17v.01M13 17v.01M12.226 8.2a4 4 0 016.024.55M9.445 5.407A8 8 0 0121.5 6.5M3 3l18 18"/></svg>;
export default RouterOff;
