// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ScriptX = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-script-x" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 20H6a3 3 0 010-6h11a3 3 0 00-3 3m7-3V6a2 2 0 00-2-2H9a2 2 0 00-2 2v8M17 17l4 4m0-4l-4 4"/></svg>;
export default ScriptX;
