// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ScubaDiving = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-scuba-diving" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 12a1 1 0 102 0 1 1 0 00-2 0M2 2l3 3 1.5 4 3.5 2 6 2 1 4 2.5 3M11 8l4.5 1.5"/></svg>;
export default ScubaDiving;
