// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Sdk = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-sdk" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M7 8H4a1 1 0 00-1 1v2a1 1 0 001 1h2a1 1 0 011 1v2a1 1 0 01-1 1H3M17 8v8M21 8l-3 4 3 4M17 12h1M10 8v8h2a2 2 0 002-2v-4a2 2 0 00-2-2h-2z"/></svg>;
export default Sdk;
