// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Share3 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-share-3" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 4v4C6.425 9.028 3.98 14.788 3 20c-.037.206 5.384-5.962 10-6v4l8-7-8-7z"/></svg>;
export default Share3;
