// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShieldCheck = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-shield-check" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11.46 20.846A12 12 0 013.5 6 12 12 0 0012 3a12 12 0 008.5 3 12 12 0 01-.09 7.06M15 19l2 2 4-4"/></svg>;
export default ShieldCheck;
