// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShieldCode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-shield-code" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 21A12 12 0 013.5 6 12 12 0 0012 3a12 12 0 008.5 3 12 12 0 01-.078 7.024M20 21l2-2-2-2M17 17l-2 2 2 2"/></svg>;
export default ShieldCode;
