// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShoppingCartCheck = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-shopping-cart-check" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 19a2 2 0 104 0 2 2 0 00-4 0"/><path d="M11.5 17H6V3H4"/><path d="M6 5l14 1-1 7H6M15 19l2 2 4-4"/></svg>;
export default ShoppingCartCheck;
