// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShovelPitchforks = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-shovel-pitchforks" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5 3h4M7 3v12M4 15h6v3a3 3 0 01-6 0v-3zM14 21v-3a3 3 0 016 0v3M17 21V3"/></svg>;
export default ShovelPitchforks;
