// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Signal3g = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-signal-3g" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 8h-2a2 2 0 00-2 2v4a2 2 0 002 2h2v-4h-1M6 8h2.5A1.5 1.5 0 0110 9.5v1A1.5 1.5 0 018.5 12H7h1.5a1.5 1.5 0 011.5 1.5v1A1.5 1.5 0 018.5 16H6"/></svg>;
export default Signal3g;
