// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Slice = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-slice" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 19L18 4l3 3-6 6 2 2a14 14 0 01-14 4"/></svg>;
export default Slice;
