// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SoccerField = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-soccer-field" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M9 12a3 3 0 106 0 3 3 0 10-6 0M3 9h3v6H3zM18 9h3v6h-3z"/><path d="M3 7a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2zM12 5v14"/></svg>;
export default SoccerField;
