// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SocialOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-social-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 5a2 2 0 104 0 2 2 0 10-4 0M3 19a2 2 0 104 0 2 2 0 10-4 0M17.57 17.602a2 2 0 002.83 2.827M11.113 11.133a3 3 0 103.765 3.715M12 7v1M6.7 17.8l2.8-2M17.3 17.8l-2.8-2M3 3l18 18"/></svg>;
export default SocialOff;
