// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Sock = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-sock" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M13 3v6l4.798 5.142a4 4 0 01-5.441 5.86l-6.736-6.41A2 2 0 015 12.141V3h8z"/><path d="M7.895 15.768C8.603 15.047 9 14.091 9 13a4 4 0 00-4-4"/></svg>;
export default Sock;
