// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Soup = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-soup" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 11h16a1 1 0 011 1v.5c0 1.5-2.517 5.573-4 6.5v1a1 1 0 01-1 1H8a1 1 0 01-1-1v-1c-1.687-1.054-4-5-4-6.5V12a1 1 0 011-1zM12 4a2.4 2.4 0 00-1 2 2.4 2.4 0 001 2M16 4a2.4 2.4 0 00-1 2 2.4 2.4 0 001 2M8 4a2.4 2.4 0 00-1 2 2.4 2.4 0 001 2"/></svg>;
export default Soup;
