// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SourceCode = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-source-code" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14.5 4H17a3 3 0 013 3v10a3 3 0 01-3 3H7a3 3 0 01-3-3v-5M6 5L4 7l2 2"/><path d="M10 9l2-2-2-2"/></svg>;
export default SourceCode;
