// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Spaces = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-spaces" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6.045 9.777a6 6 0 105.951.023M11.997 20.196a6 6 0 10-2.948-5.97"/><path d="M17.95 9.785Q18 9.399 18 9a6 6 0 10-3.056 5.23"/></svg>;
export default Spaces;
