// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareToggleHorizontal = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-square-toggle-horizontal" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M22 12H2M4 14V6a2 2 0 012-2h12a2 2 0 012 2v8M18 20a2 2 0 002-2M4 18a2 2 0 002 2M14 20h-4"/></svg>;
export default SquareToggleHorizontal;
