// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareRoot = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-square-root" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12h2l4 8 4-16h8"/></svg>;
export default SquareRoot;
