// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareF3 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-square-f3" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 5a2 2 0 012-2h14a2 2 0 012 2v14a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><path d="M13 9.5a.5.5 0 01.5-.5h1a1.5 1.5 0 010 3H14h.5a1.5 1.5 0 010 3h-1a.5.5 0 01-.5-.5M8 12h2M10 9H8v6"/></svg>;
export default SquareF3;
