// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StackMiddle = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-stack-middle" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16 10l4-2-8-4-8 4 4 2"/><path d="M12 12l-4-2-4 2 8 4 8-4-4-2-4 2z" fill="currentColor"/><path d="M8 14l-4 2 8 4 8-4-4-2"/></svg>;
export default StackMiddle;
