// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StairsDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-stairs-down" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M22 21h-5v-5h-5v-5H7V6H2M18 3v7M15 7l3 3 3-3"/></svg>;
export default StairsDown;
