// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Steam = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-steam" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 4a1 1 0 102 0 1 1 0 10-2 0M3 12a1 1 0 102 0 1 1 0 10-2 0M19 12a1 1 0 102 0 1 1 0 10-2 0M11 20a1 1 0 102 0 1 1 0 10-2 0M5.5 5.5l3 3M15.5 15.5l3 3M18.5 5.5l-3 3M8.5 15.5l-3 3"/></svg>;
export default Steam;
