// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StepInto = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-step-into" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 3v12M16 11l-4 4M8 11l4 4M11 20a1 1 0 102 0 1 1 0 10-2 0"/></svg>;
export default StepInto;
