// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Subtask = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-subtask" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M6 9h6M4 5h4M6 5v11a1 1 0 001 1h5M12 8a1 1 0 011-1h6a1 1 0 011 1v2a1 1 0 01-1 1h-6a1 1 0 01-1-1zM12 16a1 1 0 011-1h6a1 1 0 011 1v2a1 1 0 01-1 1h-6a1 1 0 01-1-1z"/></svg>;
export default Subtask;
