// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SwipeDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-swipe-down" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 4a4 4 0 110 8 4 4 0 010-8zM12 12v8M9 17l3 3 3-3"/></svg>;
export default SwipeDown;
