// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Switch = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-switch" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M15 4h4v4M14.75 9.25L19 4M5 19l4-4M15 19h4v-4M5 5l14 14"/></svg>;
export default Switch;
