// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextPlus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-text-plus" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 10H5M5 6h14M14 14H5M5 18h6M18 15v6M15 18h6"/></svg>;
export default TextPlus;
