// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextGrammar = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-text-grammar" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 9a3 3 0 106 0 3 3 0 00-6 0M4 12V7a3 3 0 116 0v5M4 9h6M20 6v6M4 16h12M4 20h6M14 20l2 2 5-5"/></svg>;
export default TextGrammar;
