// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Theater = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-theater" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M4 20h16M20 16V6a2 2 0 00-2-2H6a2 2 0 00-2 2v10l4-6c2.667 1.333 5.333 1.333 8 0l4 6z"/></svg>;
export default Theater;
