// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Tie = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-tie" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M12 22l4-4-2.5-11 .993-2.649A1 1 0 0013.557 3h-3.114a1 1 0 00-.936 1.351L10.5 7 8 18l4 4z"/><path d="M10.5 7h3l5 5.5"/></svg>;
export default Tie;
