// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TimeDurationOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-time-duration-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12v.01M7.5 19.8v.01M4.2 16.5v.01M4.2 7.5v.01M12 21a8.994 8.994 0 006.362-2.634m1.685-2.336A9 9 0 0012 3M3 3l18 18"/></svg>;
export default TimeDurationOff;
