// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ToolsKitchen2 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-tools-kitchen-2" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M19 3v12h-5c-.023-3.681.184-7.406 5-12zm0 12v6h-1v-3M8 4v17M5 4v3a3 3 0 106 0V4"/></svg>;
export default ToolsKitchen2;
