// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TopologyStarRing = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-topology-star-ring" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M14 20a2 2 0 10-4 0 2 2 0 004 0zM14 4a2 2 0 10-4 0 2 2 0 004 0zM6 12a2 2 0 10-4 0 2 2 0 004 0zM22 12a2 2 0 10-4 0 2 2 0 004 0zM14 12a2 2 0 10-4 0 2 2 0 004 0zM6 12h4M14 12h4M13.5 5.5l5 5M5.5 13.5l5 5M13.5 18.5l5-5M10.5 5.5l-5 5M12 6v4M12 14v4"/></svg>;
export default TopologyStarRing;
