// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TopologyFullHierarchy = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-topology-full-hierarchy" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M20 18a2 2 0 10-4 0 2 2 0 004 0zM8 18a2 2 0 10-4 0 2 2 0 004 0zM8 6a2 2 0 10-4 0 2 2 0 004 0zM20 6a2 2 0 10-4 0 2 2 0 004 0zM14 12a2 2 0 10-4 0 2 2 0 004 0zM6 8v8M18 16V8M8 6h8M16 18H8M7.5 7.5l3 3M13.5 13.5l3 3M16.5 7.5l-3 3M10.5 13.5l-3 3"/></svg>;
export default TopologyFullHierarchy;
