// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TrendingUp = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-trending-up" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 17l6-6 4 4 8-8"/><path d="M14 7h7v7"/></svg>;
export default TrendingUp;
