// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UvIndex = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-uv-index" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 12h1m16 0h1M5.6 5.6l.7.7m12.1-.7l-.7.7M8 12a4 4 0 118 0M12 4V3M13 16l2 5h1l2-5M6 16v3a2 2 0 104 0v-3"/></svg>;
export default UvIndex;
