// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VectorTriangle = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-vector-triangle" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 5a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1zM3 18a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1zM17 18a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 01-1 1h-2a1 1 0 01-1-1zM6.5 17.1l5-9.1M17.5 17.1l-5-9.1M7 19h10"/></svg>;
export default VectorTriangle;
