// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Versions = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-versions" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 7a2 2 0 012-2h6a2 2 0 012 2v10a2 2 0 01-2 2h-6a2 2 0 01-2-2zM7 7v10M4 8v8"/></svg>;
export default Versions;
