// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VideoOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-video-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M3 3l18 18M15 11v-1l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-.675.946"/><path d="M10 6h3a2 2 0 012 2v3m0 4v1a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h1"/></svg>;
export default VideoOff;
