// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ViewfinderOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-viewfinder-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M5.65 5.623a9 9 0 1012.71 12.745m1.684-2.328A9 9 0 007.95 3.96M12 3v4M12 21v-3M3 12h4M21 12h-3M12 12v.01M3 3l18 18"/></svg>;
export default ViewfinderOff;
