// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Vinyl = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-vinyl" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M16 3.937A9 9 0 1021 12M11 12a1 1 0 102 0 1 1 0 10-2 0M19 4a1 1 0 102 0 1 1 0 10-2 0"/><path d="M20 4l-3.5 10-2.5 2"/></svg>;
export default Vinyl;
