// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Wallet = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-wallet" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 8V5a1 1 0 00-1-1H6a2 2 0 000 4h12a1 1 0 011 1v3m0 4v3a1 1 0 01-1 1H6a2 2 0 01-2-2V6"/><path d="M20 12v4h-4a2 2 0 010-4h4"/></svg>;
export default Wallet;
