// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WallpaperOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-wallpaper-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M10 6h8a2 2 0 012 2v8m-.58 3.409A2 2 0 0118 20H6"/><path d="M4 18a2 2 0 104 0 2 2 0 10-4 0"/><path d="M8 18V8M4.573 4.598A2.003 2.003 0 004 6v12M3 3l18 18"/></svg>;
export default WallpaperOff;
