// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WalletOff = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-wallet-off" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M17 8V5a1 1 0 00-1-1H8m-3.413.584A2 2 0 006 8h2m4 0h6a1 1 0 011 1v3"/><path d="M19 19a1 1 0 01-1 1H6a2 2 0 01-2-2V6"/><path d="M16 12h4v4m-4 0a2 2 0 01-2-2M3 3l18 18"/></svg>;
export default WalletOff;
