// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Wiper = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-wiper" {...props}><path d="M0 0h24v24H0z" stroke="none"/><path d="M11 18a1 1 0 102 0 1 1 0 10-2 0M3 9l5.5 5.5a5 5 0 017 0L21 9A12 12 0 003 9M12 18L9.8 5.2"/></svg>;
export default Wiper;
