// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Badge = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-badge" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M16.486 3.143L12 5.833l-4.486-2.69A1 1 0 006 4v13a1 1 0 00.486.857l5 3a1 1 0 001.028 0l5-3A1 1 0 0018 17V4a1 1 0 00-1.514-.857z"/></svg>;
export default Badge;
