// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Circle = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-circle" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M7 3.34a10 10 0 11-4.995 8.984L2 12l.005-.324A10 10 0 017 3.34z"/></svg>;
export default Circle;
