// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CreditCard = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-credit-card" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M22 10v6a4 4 0 01-4 4H6a4 4 0 01-4-4v-6h20zM7.01 14H7a1 1 0 10.01 2 1 1 0 000-2zM13 14h-2a1 1 0 000 2h2a1 1 0 000-2zm5-10a4 4 0 014 4H2a4 4 0 014-4h12z"/></svg>;
export default CreditCard;
