// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceWatch = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-device-watch" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M15 2a1 1 0 011 1v2.126c1.726.445 3 2.01 3 3.874v6a4 4 0 01-3 3.874V21a1 1 0 01-1 1H9a1 1 0 01-1-1v-2.126A4 4 0 015 15V9a4 4 0 013-3.874V3a1 1 0 011-1zm-1 17h-4v1h4zm0-15h-4v1h4z"/></svg>;
export default DeviceWatch;
