// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LayoutSidebar = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-layout-sidebar" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M6 21a3 3 0 01-3-3V6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3zM18 5h-8v14h8a1 1 0 001-1V6a1 1 0 00-1-1"/></svg>;
export default LayoutSidebar;
