// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LayoutDistributeHorizontal = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-layout-distribute-horizontal" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M20 3a1 1 0 010 2H4a1 1 0 110-2zM20 19a1 1 0 010 2H4a1 1 0 010-2zM16 8a3 3 0 013 3v2a3 3 0 01-3 3H8a3 3 0 01-3-3v-2a3 3 0 013-3z"/></svg>;
export default LayoutDistributeHorizontal;
