// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Mushroom = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-mushroom" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M15 15v4a3 3 0 01-5.995.176L9 19v-4h6zM4.9 13a1.9 1.9 0 01-1.894-1.752L3 11.1C3 6.077 7.027 2 12 2s9 4.077 9 9.1a1.9 1.9 0 01-1.752 1.894L19.1 13H4.9z"/></svg>;
export default Mushroom;
