// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const OvalVertical = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-oval-vertical" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M12 5C6.543 5 2 8.028 2 12s4.543 7 10 7 10-3.028 10-7-4.543-7-10-7z"/></svg>;
export default OvalVertical;
