// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Windsock = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="icon icon-tabler icons-tabler-filled icon-tabler-windsock" {...props}><path d="M0 0h24v24H0z" fill="none"/><path d="M6 2a1 1 0 011 1v1.079l11.083.924A1 1 0 0119 6v4a1 1 0 01-.917.997L7 11.92V20h1a1 1 0 010 2H4a1 1 0 010-2h1V3a1 1 0 011-1m1 4.086v3.827l3-.25V6.336zm7 .584v2.659l3-.25V6.92z"/></svg>;
export default Windsock;
