// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f170 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path d="M62 52c0 5.5-4.5 10-10 10H12C6.5 62 2 57.5 2 52V12C2 6.5 6.5 2 12 2h40c5.5 0 10 4.5 10 10v40z" fill="#ff5a79"/><path d="M41.7 46H47L35 14h-6L17 46h5.3l4.2-11.2h11.1L41.7 46zM28.3 30l3.7-9.9 3.7 9.9h-7.4z" fill="#fff"/></svg>;
export default Svg1f170;
