// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f1f91f1fc = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path d="M32 2v30H2c0 16.6 13.4 30 30 30s30-13.4 30-30S48.6 2 32 2z" fill="#ed4c5c"/><path d="M32 2C15.4 2 2 15.4 2 32h30V2z" fill="#2a5f9e"/><path d="M24 20.3l5-1.3-5-1.3 3.7-3.7-5 1.3 1.3-5-3.7 3.7L19 9l-1.3 5-3.7-3.7 1.3 5-5-1.3 3.7 3.7L9 19l5 1.3-3.7 3.7 5-1.3-1.3 5 3.7-3.7 1.3 5 1.3-5 3.7 3.7-1.3-5 5 1.3-3.7-3.7" fill="#fff"/><circle cx="19" cy="19" r="5.7" fill="#428bc1"/><circle cx="19" cy="19" r="5" fill="#fff"/></svg>;
export default Svg1f1f91f1fc;
