// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f1fb = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><circle cx="32" cy="32" r="30" fill="#4fd1d9"/><path d="M38.4 17.5h6.3l-9.9 29h-5.7l-9.8-29h6.5l6.3 22 6.3-22" fill="#fff"/></svg>;
export default Svg1f1fb;
