// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f4cd = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path fill="#d0d0d0" d="M42.6 29.4L2 62l32.6-40.6z"/><circle cx="45" cy="19" r="17" fill="#ed4c5c"/></svg>;
export default Svg1f4cd;
