// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f527 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path d="M47.4 47.4l7.5-2 8.8 8.8c1-4.2-.1-8.9-3.4-12.2-3.3-3.3-7.9-4.4-12.2-3.4L25.4 16c1-4.2-.1-8.9-3.4-12.2C18.7.5 14.1-.6 9.8.4l8.8 8.8-2 7.5-7.5 2L.4 9.8c-1 4.2.1 8.9 3.4 12.2 3.3 3.3 7.9 4.4 12.2 3.4L38.6 48c-1 4.2.1 8.9 3.4 12.2 3.3 3.3 7.9 4.4 12.2 3.4l-8.8-8.8 2-7.4" fill="#94989b"/></svg>;
export default Svg1f527;
