// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f53b = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path fill="#ed4c5c" d="M32 62L62 2H2z"/></svg>;
export default Svg1f53b;
