// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f53a = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path fill="#ed4c5c" d="M32 2L2 62h60z"/></svg>;
export default Svg1f53a;
