// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1f538 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path fill="#f27a52" d="M16.019 32l15.98-15.981 15.98 15.98L32 47.98z"/></svg>;
export default Svg1f538;
