// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg25aa = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><path fill="#333" d="M16 16h32v32H16z"/></svg>;
export default Svg25aa;
