// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg2b06 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" {...props}><circle cx="32" cy="32" r="30" fill="#4fd1d9"/><path fill="#fff" d="M48 30.3L32 15 16 30.3h10.6V49h10.3V30.3z"/></svg>;
export default Svg2b06;
