// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChromeMinimize = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M14 8v1H3V8h11z" fill="#C5C5C5"/></svg>;
export default ChromeMinimize;
