// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DebugBreakpointFunction = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M8 4l4 6.905H4L8 4z" fill="#E51400"/></svg>;
export default DebugBreakpointFunction;
