// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ThreeBars = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M14 5H2V3h12v2zm0 4H2V7h12v2zM2 13h12v-2H2v2z" fill="#C5C5C5"/></svg>;
export default ThreeBars;
