// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoreIcon = (props: React.SVGProps<SVGSVGElement>) => <svg aria-label="more icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M6 14.5a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm12 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm-6 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"/></svg>;
export default MoreIcon;
