// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ALargeSmall = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-a-large-small" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 14h-5M16 16v-3.5a2.5 2.5 0 015 0V16M4.5 13h6M3 16l4.5-9 4.5 9"/></svg>;
export default ALargeSmall;
