// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignLeft = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-align-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M15 12H3M17 18H3M21 6H3"/></svg>;
export default AlignLeft;
