// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Ampersands = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-ampersands" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10 17c-5-3-7-7-7-9a2 2 0 014 0c0 2.5-5 2.5-5 6 0 1.7 1.3 3 3 3 2.8 0 5-2.2 5-5M22 17c-5-3-7-7-7-9a2 2 0 014 0c0 2.5-5 2.5-5 6 0 1.7 1.3 3 3 3 2.8 0 5-2.2 5-5"/></svg>;
export default Ampersands;
