// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowBigLeft = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-arrow-big-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 15h-6v4l-7-7 7-7v4h6v6z"/></svg>;
export default ArrowBigLeft;
