// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowRight = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-arrow-right" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14M12 5l7 7-7 7"/></svg>;
export default ArrowRight;
