// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowDownLeft = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-arrow-down-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M17 7L7 17M17 17H7V7"/></svg>;
export default ArrowDownLeft;
