// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bold = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-bold" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M6 12h9a4 4 0 010 8H7a1 1 0 01-1-1V5a1 1 0 011-1h7a4 4 0 010 8"/></svg>;
export default Bold;
