// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bomb = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-bomb" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="11" cy="13" r="9"/><path d="M14.35 4.65L16.3 2.7a2.41 2.41 0 013.4 0l1.6 1.6a2.4 2.4 0 010 3.4l-1.95 1.95M22 2l-1.5 1.5"/></svg>;
export default Bomb;
