// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BookLock = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-book-lock" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 6V4a2 2 0 10-4 0v2M20 15v6a1 1 0 01-1 1H6.5a1 1 0 010-5H20"/><path d="M4 19.5v-15A2.5 2.5 0 016.5 2H10"/><rect x="12" y="6" width="8" height="5" rx="1"/></svg>;
export default BookLock;
