// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BotOff = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-bot-off" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M13.67 8H18a2 2 0 012 2v4.33M2 14h2M20 14h2M22 22L2 2M8 8H6a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 001.414-.586M9 13v2M9.67 4H12v2.33"/></svg>;
export default BotOff;
