// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bot = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-bot" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2M20 14h2M15 13v2M9 13v2"/></svg>;
export default Bot;
