// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BrickWall = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-brick-wall" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M12 9v6M16 15v6M16 3v6M3 15h18M3 9h18M8 15v6M8 3v6"/></svg>;
export default BrickWall;
