// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BringToFront = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-bring-to-front" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect x="8" y="8" width="8" height="8" rx="2"/><path d="M4 10a2 2 0 01-2-2V4a2 2 0 012-2h4a2 2 0 012 2M14 20a2 2 0 002 2h4a2 2 0 002-2v-4a2 2 0 00-2-2"/></svg>;
export default BringToFront;
