// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CalendarArrowUp = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-calendar-arrow-up" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M14 18l4-4 4 4M16 2v4M18 22v-8"/><path d="M21 11.343V6a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h9M3 10h18M8 2v4"/></svg>;
export default CalendarArrowUp;
