// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartNoAxesCombined = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-chart-no-axes-combined" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 16v5M16 14v7M20 10v11M22 3l-8.646 8.646a.5.5 0 01-.708 0L9.354 8.354a.5.5 0 00-.707 0L2 15M4 18v3M8 14v7"/></svg>;
export default ChartNoAxesCombined;
