// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartColumnDecreasing = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-chart-column-decreasing" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M13 17V9M18 17v-3M3 3v16a2 2 0 002 2h16M8 17V5"/></svg>;
export default ChartColumnDecreasing;
