// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartSpline = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-chart-spline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 3v16a2 2 0 002 2h16"/><path d="M7 16c.5-2 1.5-7 4-7 2 0 2 3 4 3 2.5 0 4.5-5 5-7"/></svg>;
export default ChartSpline;
