// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChevronUp = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-chevron-up" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 15l-6-6-6 6"/></svg>;
export default ChevronUp;
