// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Cigarette = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-cigarette" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M17 12H3a1 1 0 00-1 1v2a1 1 0 001 1h14M18 8c0-2.5-2-2.5-2-5M21 16a1 1 0 001-1v-2a1 1 0 00-1-1M22 8c0-2.5-2-2.5-2-5M7 12v4"/></svg>;
export default Cigarette;
