// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CircleParkingOff = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-circle-parking-off" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M5 5l14 14M13 13a3 3 0 100-6H9v2M9 17v-2.34"/></svg>;
export default CircleParkingOff;
