// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CircleEqual = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-circle-equal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M7 10h10M7 14h10"/><circle cx="12" cy="12" r="10"/></svg>;
export default CircleEqual;
