// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CircleCheckBig = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-circle-check-big" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21.801 10A10 10 0 1117 3.335M9 11l3 3L22 4"/></svg>;
export default CircleCheckBig;
