// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CloudUpload = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-cloud-upload" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 13v8M4 14.899A7 7 0 1115.71 8h1.79a4.5 4.5 0 012.5 8.242"/><path d="M8 17l4-4 4 4"/></svg>;
export default CloudUpload;
