// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CloudFog = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-cloud-fog" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 14.899A7 7 0 1115.71 8h1.79a4.5 4.5 0 012.5 8.242M16 17H7M17 21H9"/></svg>;
export default CloudFog;
