// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Combine = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-combine" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10 18H5a3 3 0 01-3-3v-1M14 2a2 2 0 012 2v4a2 2 0 01-2 2M20 2a2 2 0 012 2v4a2 2 0 01-2 2"/><path d="M7 21l3-3-3-3"/><rect x="14" y="14" width="8" height="8" rx="2"/><rect x="2" y="2" width="8" height="8" rx="2"/></svg>;
export default Combine;
