// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CornerUpRight = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-corner-up-right" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M15 14l5-5-5-5"/><path d="M4 20v-7a4 4 0 014-4h12"/></svg>;
export default CornerUpRight;
