// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CreativeCommons = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-creative-commons" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M10 9.3a2.8 2.8 0 00-3.5 1 3.1 3.1 0 000 3.4 2.7 2.7 0 003.5 1M17 9.3a2.8 2.8 0 00-3.5 1 3.1 3.1 0 000 3.4 2.7 2.7 0 003.5 1"/></svg>;
export default CreativeCommons;
