// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Divide = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-divide" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="6" r="1"/><path d="M5 12h14"/><circle cx="12" cy="18" r="1"/></svg>;
export default Divide;
