// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileMusic = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-file-music" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10.5 22H18a2 2 0 002-2V7l-5-5H6a2 2 0 00-2 2v8.4"/><path d="M8 18v-7.7L16 9v7"/><circle cx="14" cy="16" r="2"/><circle cx="6" cy="18" r="2"/></svg>;
export default FileMusic;
