// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileVolume = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-file-volume" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M11 11a5 5 0 010 6M14 2v4a2 2 0 002 2h4"/><path d="M4 6.765V4a2 2 0 012-2h9l5 5v13a2 2 0 01-2 2H6a2 2 0 01-.93-.23"/><path d="M7 10.51a.5.5 0 00-.826-.38l-1.893 1.628A1 1 0 013.63 12H2.5a.5.5 0 00-.5.5v3a.5.5 0 00.5.5h1.129a1 1 0 01.652.242l1.893 1.63a.5.5 0 00.826-.38z"/></svg>;
export default FileVolume;
