// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Filter = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-filter" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M22 3H2l8 9.46V19l4 2v-8.54L22 3z"/></svg>;
export default Filter;
