// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilterX = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-filter-x" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M13.013 3H2l8 9.46V19l4 2v-8.54l.9-1.055M22 3l-5 5M17 3l5 5"/></svg>;
export default FilterX;
