// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Flower = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-flower" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="3"/><path d="M12 16.5A4.5 4.5 0 117.5 12 4.5 4.5 0 1112 7.5a4.5 4.5 0 114.5 4.5 4.5 4.5 0 11-4.5 4.5M12 7.5V9M7.5 12H9M16.5 12H15M12 16.5V15M8 8l1.88 1.88M14.12 9.88L16 8M8 16l1.88-1.88M14.12 14.12L16 16"/></svg>;
export default Flower;
