// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FolderRoot = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-folder-root" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 20h16a2 2 0 002-2V8a2 2 0 00-2-2h-7.93a2 2 0 01-1.66-.9l-.82-1.2A2 2 0 007.93 3H4a2 2 0 00-2 2v13c0 1.1.9 2 2 2z"/><circle cx="12" cy="13" r="2"/><path d="M12 15v5"/></svg>;
export default FolderRoot;
