// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Forklift = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-forklift" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 12H5a2 2 0 00-2 2v5"/><circle cx="13" cy="19" r="2"/><circle cx="5" cy="19" r="2"/><path d="M8 19h3m5-17v17h6M6 12V7c0-1.1.9-2 2-2h3l5 5"/></svg>;
export default Forklift;
