// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Frame = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-frame" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M22 6H2M22 18H2M6 2v20M18 2v20"/></svg>;
export default Frame;
