// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GalleryHorizontalEnd = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-gallery-horizontal-end" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M2 7v10M6 5v14"/><rect width="12" height="18" x="10" y="3" rx="2"/></svg>;
export default GalleryHorizontalEnd;
