// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Gamepad = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-gamepad" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M6 12h4M8 10v4M15 13h.01M18 11h.01"/><rect width="20" height="12" x="2" y="6" rx="2"/></svg>;
export default Gamepad;
