// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GitGraph = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-git-graph" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="5" cy="6" r="3"/><path d="M5 9v6"/><circle cx="5" cy="18" r="3"/><path d="M12 3v18"/><circle cx="19" cy="6" r="3"/><path d="M16 15.7A9 9 0 0019 9"/></svg>;
export default GitGraph;
