// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Globe = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-globe" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 000 20 14.5 14.5 0 000-20M2 12h20"/></svg>;
export default Globe;
