// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Heading4 = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-heading-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 12h8M4 18V6M12 18V6M17 10v4h4M21 10v8"/></svg>;
export default Heading4;
