// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hospital = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-hospital" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 6v4M14 14h-4M14 18h-4M14 8h-4M18 12h2a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2v-9a2 2 0 012-2h2"/><path d="M18 22V4a2 2 0 00-2-2H8a2 2 0 00-2 2v18"/></svg>;
export default Hospital;
