// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Info = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-info" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>;
export default Info;
