// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const JapaneseYen = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-japanese-yen" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 9.5V21m0-11.5L6 3m6 6.5L18 3M6 15h12M6 11h12"/></svg>;
export default JapaneseYen;
