// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Joystick = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-joystick" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 17a2 2 0 00-2-2H5a2 2 0 00-2 2v2a2 2 0 002 2h14a2 2 0 002-2v-2zM6 15v-2M12 15V9"/><circle cx="12" cy="6" r="3"/></svg>;
export default Joystick;
