// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ListTodo = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-list-todo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect x="3" y="5" width="6" height="6" rx="1"/><path d="M3 17l2 2 4-4M13 6h8M13 12h8M13 18h8"/></svg>;
export default ListTodo;
