// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LoaderCircle = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-loader-circle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 12a9 9 0 11-6.219-8.56"/></svg>;
export default LoaderCircle;
