// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MessageSquareReply = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-message-square-reply" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/><path d="M10 7l-3 3 3 3"/><path d="M17 13v-1a2 2 0 00-2-2H7"/></svg>;
export default MessageSquareReply;
