// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MessageCircleMore = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-message-circle-more" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M7.9 20A9 9 0 104 16.1L2 22zM8 12h.01M12 12h.01M16 12h.01"/></svg>;
export default MessageCircleMore;
