// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MessageCircleCode = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-message-circle-code" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10 9.5L8 12l2 2.5M14 9.5l2 2.5-2 2.5"/><path d="M7.9 20A9 9 0 104 16.1L2 22z"/></svg>;
export default MessageCircleCode;
