// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MonitorCheck = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-monitor-check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M9 10l2 2 4-4"/><rect width="20" height="14" x="2" y="3" rx="2"/><path d="M12 17v4M8 21h8"/></svg>;
export default MonitorCheck;
