// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoveVertical = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-move-vertical" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2v20M8 18l4 4 4-4M8 6l4-4 4 4"/></svg>;
export default MoveVertical;
