// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoveUpLeft = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-move-up-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 11V5h6M5 5l14 14"/></svg>;
export default MoveUpLeft;
