// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Navigation2 = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-navigation-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2l7 19-7-4-7 4 7-19z"/></svg>;
export default Navigation2;
