// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PaintRoller = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-paint-roller" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="16" height="6" x="2" y="2" rx="2"/><path d="M10 16v-2a2 2 0 012-2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2"/><rect width="4" height="6" x="8" y="16" rx="1"/></svg>;
export default PaintRoller;
