// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Paperclip = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-paperclip" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l8.57-8.57A4 4 0 1118 8.84l-8.59 8.57a2 2 0 01-2.83-2.83l8.49-8.48"/></svg>;
export default Paperclip;
