// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ParkingMeter = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-parking-meter" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M11 15h2M12 12v3M12 19v3M15.282 19a1 1 0 00.948-.68l2.37-6.988a7 7 0 10-13.2 0l2.37 6.988a1 1 0 00.948.68zM9 9a3 3 0 116 0"/></svg>;
export default ParkingMeter;
