// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PiggyBank = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-piggy-bank" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M19 5c-1.5 0-2.8 1.4-3 2-3.5-1.5-11-.3-11 5 0 1.8 0 3 2 4.5V20h4v-2h3v2h4v-4c1-.5 1.7-1 2-2h2v-4h-2c0-1-.5-1.5-1-2V5zM2 9v1c0 1.1.9 2 2 2h1M16 11h.01"/></svg>;
export default PiggyBank;
