// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PillBottle = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-pill-bottle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 11h-4a1 1 0 00-1 1v5a1 1 0 001 1h4"/><path d="M6 7v13a2 2 0 002 2h8a2 2 0 002-2V7"/><rect width="16" height="5" x="4" y="2" rx="1"/></svg>;
export default PillBottle;
