// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RailSymbol = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-rail-symbol" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 15h14M5 9h14M14 20l-5-5 6-6-5-5"/></svg>;
export default RailSymbol;
