// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ReceiptCent = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-receipt-cent" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1zM12 6.5v11M15 9.4a4 4 0 100 5.2"/></svg>;
export default ReceiptCent;
