// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ReceiptIndianRupee = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-receipt-indian-rupee" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1zM8 7h8"/><path d="M12 17.5L8 15h1a4 4 0 000-8M8 11h8"/></svg>;
export default ReceiptIndianRupee;
