// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Reply = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-reply" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M9 17l-5-5 5-5"/><path d="M20 18v-2a4 4 0 00-4-4H4"/></svg>;
export default Reply;
