// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Rewind = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-rewind" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M11 19l-9-7 9-7v14zM22 19l-9-7 9-7v14z"/></svg>;
export default Rewind;
