// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Router = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-router" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="20" height="8" x="2" y="14" rx="2"/><path d="M6.01 18H6M10.01 18H10M15 10v4M17.84 7.17a4 4 0 00-5.66 0M20.66 4.34a8 8 0 00-11.31 0"/></svg>;
export default Router;
