// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ScanQrCode = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-scan-qr-code" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M17 12v4a1 1 0 01-1 1h-4M17 3h2a2 2 0 012 2v2M17 8V7M21 17v2a2 2 0 01-2 2h-2M3 7V5a2 2 0 012-2h2M7 17h.01M7 21H5a2 2 0 01-2-2v-2"/><rect x="7" y="7" width="5" height="5" rx="1"/></svg>;
export default ScanQrCode;
