// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SeparatorHorizontal = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-separator-horizontal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 12h18M8 8l4-4 4 4M16 16l-4 4-4-4"/></svg>;
export default SeparatorHorizontal;
