// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SlidersVertical = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-sliders-vertical" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M2 14h4M10 8h4M18 16h4"/></svg>;
export default SlidersVertical;
