// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Spade = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-spade" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 9c-1.5 1.5-3 3.2-3 5.5A5.5 5.5 0 007.5 20c1.8 0 3-.5 4.5-2 1.5 1.5 2.7 2 4.5 2a5.5 5.5 0 005.5-5.5c0-2.3-1.5-4-3-5.5l-7-7-7 7zM12 18v4"/></svg>;
export default Spade;
