// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareParkingOff = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-square-parking-off" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3.6 3.6A2 2 0 015 3h14a2 2 0 012 2v14a2 2 0 01-.59 1.41M3 8.7V19a2 2 0 002 2h10.3M2 2l20 20"/><path d="M13 13a3 3 0 100-6H9v2M9 17v-2.3"/></svg>;
export default SquareParkingOff;
