// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareCode = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-square-code" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M10 9.5L8 12l2 2.5M14 9.5l2 2.5-2 2.5"/><rect width="18" height="18" x="3" y="3" rx="2"/></svg>;
export default SquareCode;
