// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareEqual = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-square-equal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M7 10h10M7 14h10"/></svg>;
export default SquareEqual;
