// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareMousePointer = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-square-mouse-pointer" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12.034 12.681a.498.498 0 01.647-.647l9 3.5a.5.5 0 01-.033.943l-3.444 1.068a1 1 0 00-.66.66l-1.067 3.443a.5.5 0 01-.943.033z"/><path d="M21 11V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h6"/></svg>;
export default SquareMousePointer;
