// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Tally5 = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-tally-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 4v16M9 4v16M14 4v16M19 4v16M22 6L2 18"/></svg>;
export default Tally5;
