// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TowerControl = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-tower-control" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18.2 12.27L20 6H4l1.8 6.27a1 1 0 00.95.73h10.5a1 1 0 00.96-.73zM8 13v9M16 22v-9M9 6l1 7M15 6l-1 7M12 6V2M13 2h-2"/></svg>;
export default TowerControl;
