// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TreeDeciduous = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-tree-deciduous" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M8 19a4 4 0 01-2.24-7.32A3.5 3.5 0 019 6.03V6a3 3 0 116 0v.04a3.5 3.5 0 013.24 5.65A4 4 0 0116 19zM12 19v3"/></svg>;
export default TreeDeciduous;
