// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Type = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-type" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M4 7V4h16v3M9 20h6M12 4v16"/></svg>;
export default Type;
