// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UserRoundMinus = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-user-round-minus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M2 21a8 8 0 0113.292-6"/><circle cx="10" cy="8" r="5"/><path d="M22 19h-6"/></svg>;
export default UserRoundMinus;
