// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UserMinus = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-user-minus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 11h-6"/></svg>;
export default UserMinus;
