// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WifiLow = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-wifi-low" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 20h.01M8.5 16.429a5 5 0 017 0"/></svg>;
export default WifiLow;
