// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Youtube = (props: React.SVGProps<SVGSVGElement>) => <svg className="lucide lucide-youtube" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M2.5 17a24.12 24.12 0 010-10 2 2 0 011.4-1.4 49.56 49.56 0 0116.2 0A2 2 0 0121.5 7a24.12 24.12 0 010 10 2 2 0 01-1.4 1.4 49.55 49.55 0 01-16.2 0A2 2 0 012.5 17"/><path d="M10 15l5-3-5-3z"/></svg>;
export default Youtube;
