// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowUp = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" {...props}><path d="M16 4L6 14l1.41 1.41L15 7.83V30h2V7.83l7.59 7.58L26 14 16 4z"/></svg>;
export default ArrowUp;
