// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FaceWinkFilled = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" {...props}><path d="M16 2a14 14 0 1 0 14 14A14 14 0 0 0 16 2zM8 13h6v2H8zm8 11a8 8 0 0 1-6.85-3.89l1.71-1a6 6 0 0 0 10.28 0l1.71 1A8 8 0 0 1 16 24zm4.5-8a2.5 2.5 0 0 1 0-5 2.5 2.5 0 0 1 0 5z"/></svg>;
export default FaceWinkFilled;
