// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberSmall4 = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" {...props}><path d="M17 11v4h-2v-4h-2v6h4v4h2V11h-2z"/></svg>;
export default NumberSmall4;
