// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PageLast = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" {...props}><path d="M18 16L8 26l-1.4-1.4 8.6-8.6-8.6-8.6L8 6zm4-12h2v24h-2z"/></svg>;
export default PageLast;
