// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StarHalf = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" {...props}><path d="M11.45 11.22L1.28 12.7l7.36 7.17L6.9 30l9.1-4.78V2l-4.55 9.22z"/></svg>;
export default StarHalf;
