// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Capsule1 = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M6.398 7.625a5.625 5.625 0 1111.25 0v8.75a5.625 5.625 0 01-11.25 0v-8.75zM12.023 3.5a4.125 4.125 0 00-4.125 4.125v3.625h8.25V7.625A4.125 4.125 0 0012.023 3.5zm4.125 9.25h-8.25v3.625a4.125 4.125 0 108.25 0V12.75z" fill="#323544"/></svg>;
export default Capsule1;
