// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><path d="M12.3 9.3l-3.8 3.8V1h-1v12.1L3.7 9.3 3 10l5 5 5-5z"/></svg>;
export default ArrowDown;
