// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowRight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><path d="M9.3 3.7l3.8 3.8H1v1h12.1l-3.8 3.8.7.7 5-5-5-5z"/></svg>;
export default ArrowRight;
