// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CheckmarkFilled = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><path d="M8 1C4.1 1 1 4.1 1 8s3.1 7 7 7 7-3.1 7-7-3.1-7-7-7zm-1 9.8L4.5 8.2l.8-.8L7 9.2l3.7-3.7.8.8L7 10.8z"/></svg>;
export default CheckmarkFilled;
