// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Menu = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><path d="M2 3h12v1H2zm0 9h12v1H2zm0-4.5h12v1H2z"/></svg>;
export default Menu;
