// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AirplaneInFlightFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 216a8 8 0 01-8 8H72a8 8 0 110-16h144a8 8 0 018 8zM208 96h-60.68l-45.66-45.66A8 8 0 0096 48h-8a16 16 0 00-15.17 21.06l9 26.94H59.32L37.66 74.34A8 8 0 0032 72h-8A16 16 0 008.69 92.6l14.07 46.89A39.75 39.75 0 0061.07 168H240a8 8 0 008-8v-24a40 40 0 00-40-40z"/></svg>;
export default AirplaneInFlightFill;
