// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignTopLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M222 40a6 6 0 01-6 6H40a6 6 0 010-12h176a6 6 0 016 6zm-16 40v96a14 14 0 01-14 14h-40a14 14 0 01-14-14V80a14 14 0 0114-14h40a14 14 0 0114 14zm-12 0a2 2 0 00-2-2h-40a2 2 0 00-2 2v96a2 2 0 002 2h40a2 2 0 002-2zm-76 0v136a14 14 0 01-14 14H64a14 14 0 01-14-14V80a14 14 0 0114-14h40a14 14 0 0114 14zm-12 0a2 2 0 00-2-2H64a2 2 0 00-2 2v136a2 2 0 002 2h40a2 2 0 002-2z"/></svg>;
export default AlignTopLight;
