// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignCenterHorizontalBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 136h-68v-16h44a20 20 0 0020-20V60a20 20 0 00-20-20h-44v-8a12 12 0 00-24 0v8H72a20 20 0 00-20 20v40a20 20 0 0020 20h44v16H48a20 20 0 00-20 20v40a20 20 0 0020 20h68v8a12 12 0 0024 0v-8h68a20 20 0 0020-20v-40a20 20 0 00-20-20zM76 64h104v32H76zm128 128H52v-32h152z"/></svg>;
export default AlignCenterHorizontalBold;
