// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignLeftFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 152v40a16 16 0 01-16 16H80a16 16 0 01-16-16v-40a16 16 0 0116-16h136a16 16 0 0116 16zM40 32a8 8 0 00-8 8v176a8 8 0 0016 0V40a8 8 0 00-8-8zm40 88h96a16 16 0 0016-16V64a16 16 0 00-16-16H80a16 16 0 00-16 16v40a16 16 0 0016 16z"/></svg>;
export default AlignLeftFill;
