// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignRightSimpleFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 56v144a8 8 0 01-16 0V56a8 8 0 0116 0zm-48 24H32a16 16 0 00-16 16v64a16 16 0 0016 16h152a16 16 0 0016-16V96a16 16 0 00-16-16z"/></svg>;
export default AlignRightSimpleFill;
