// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignTop = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 40a8 8 0 01-8 8H40a8 8 0 010-16h176a8 8 0 018 8zm-16 40v96a16 16 0 01-16 16h-40a16 16 0 01-16-16V80a16 16 0 0116-16h40a16 16 0 0116 16zm-16 0h-40v96h40zm-72 0v136a16 16 0 01-16 16H64a16 16 0 01-16-16V80a16 16 0 0116-16h40a16 16 0 0116 16zm-16 0H64v136h40z"/></svg>;
export default AlignTop;
