// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AlignLeftBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M52 40v176a12 12 0 01-24 0V40a12 12 0 0124 0zm16 60V64a20 20 0 0120-20h88a20 20 0 0120 20v36a20 20 0 01-20 20H88a20 20 0 01-20-20zm24-4h80V68H92zm144 60v36a20 20 0 01-20 20H88a20 20 0 01-20-20v-36a20 20 0 0120-20h128a20 20 0 0120 20zm-24 4H92v28h120z"/></svg>;
export default AlignLeftBold;
