// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AmazonLogoFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M152 136a24 24 0 11-24-24 24 24 0 0124 24zm80-8A104 104 0 11128 24a104.11 104.11 0 01104 104zm-80-24a40 40 0 100 64 8 8 0 0016 0v-64a40 40 0 00-73.87-21.29 8 8 0 0013.54 8.52A24 24 0 01152 104zm44.81 65.61a8 8 0 00-11.2 1.58 72 72 0 01-115.22 0 8 8 0 10-12.78 9.62 88 88 0 00140.78 0 8 8 0 00-1.58-11.2z"/></svg>;
export default AmazonLogoFill;
