// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Ambulance = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M80 120a8 8 0 018-8h16V96a8 8 0 0116 0v16h16a8 8 0 010 16h-16v16a8 8 0 01-16 0v-16H88a8 8 0 01-8-8zm176 0v64a16 16 0 01-16 16h-17a32 32 0 01-62 0h-50a32 32 0 01-62 0H32a16 16 0 01-16-16V72a16 16 0 0116-16h152a8 8 0 018 8v8h34.58a15.93 15.93 0 0114.86 10.06l14 35A7.92 7.92 0 01256 120zm-64-32v24h44.18l-9.6-24zM32 184h17a32 32 0 0162 0h50a32.11 32.11 0 0115-19.69V72H32zm64 8a16 16 0 10-16 16 16 16 0 0016-16zm112 0a16 16 0 10-16 16 16 16 0 0016-16zm32-8v-56h-48v32a32.06 32.06 0 0131 24z"/></svg>;
export default Ambulance;
