// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowUDownRightBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232.49 176.49l-48 48a12 12 0 01-17-17L195 180H88a68 68 0 010-136h88a12 12 0 010 24H88a44 44 0 000 88h107l-27.52-27.51a12 12 0 1117-17l48 48a12 12 0 01.01 17z"/></svg>;
export default ArrowUDownRightBold;
