// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowCircleDownRightThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 28a100 100 0 10100 100A100.11 100.11 0 00128 28zm0 192a92 92 0 1192-92 92.1 92.1 0 01-92 92zm36-108v48a4 4 0 01-4 4h-48a4 4 0 010-8h38.34L93.17 98.83a4 4 0 015.66-5.66L156 150.34V112a4 4 0 018 0z"/></svg>;
export default ArrowCircleDownRightThin;
