// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowFatUpFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M231.39 123.06A8 8 0 01224 128h-40v80a16 16 0 01-16 16H88a16 16 0 01-16-16v-80H32a8 8 0 01-5.66-13.66l96-96a8 8 0 0111.32 0l96 96a8 8 0 011.73 8.72z"/></svg>;
export default ArrowFatUpFill;
