// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowCircleDownDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 128a96 96 0 11-96-96 96 96 0 0196 96z" opacity=".2"/><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm37.66-85.66a8 8 0 010 11.32l-32 32a8 8 0 01-11.32 0l-32-32a8 8 0 0111.32-11.32L120 148.69V88a8 8 0 0116 0v60.69l18.34-18.35a8 8 0 0111.32 0z"/></svg>;
export default ArrowCircleDownDuotone;
