// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowCircleDownRightBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 20a108 108 0 10108 108A108.12 108.12 0 00128 20zm0 192a84 84 0 1184-84 84.09 84.09 0 01-84 84zm44-100v48a12 12 0 01-12 12h-48a12 12 0 010-24h19l-43.49-43.51a12 12 0 0117-17L148 131v-19a12 12 0 0124 0z"/></svg>;
export default ArrowCircleDownRightBold;
