// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowLineRightThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M186.83 125.17a4 4 0 010 5.66l-72 72a4 4 0 01-5.66-5.66L174.34 132H32a4 4 0 010-8h142.34l-65.17-65.17a4 4 0 015.66-5.66zM216 36a4 4 0 00-4 4v176a4 4 0 008 0V40a4 4 0 00-4-4z"/></svg>;
export default ArrowLineRightThin;
