// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsOutSimpleBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M220 48v48a12 12 0 01-24 0V77l-39.51 39.52a12 12 0 01-17-17L179 60h-19a12 12 0 010-24h48a12 12 0 0112 12zM99.51 139.51L60 179v-19a12 12 0 00-24 0v48a12 12 0 0012 12h48a12 12 0 000-24H77l39.52-39.51a12 12 0 00-17-17z"/></svg>;
export default ArrowsOutSimpleBold;
