// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsClockwiseLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M222 48v48a6 6 0 01-6 6h-48a6 6 0 010-12h33.52l-18.05-18a81.51 81.51 0 00-57.53-24h-.46a81.5 81.5 0 00-57.29 23.28 6 6 0 11-8.38-8.58 93.38 93.38 0 0165.67-26.76h.52a93.45 93.45 0 0166 27.53l18 18V48a6 6 0 0112 0zm-34.19 136.72a81.5 81.5 0 01-57.29 23.34h-.46a81.51 81.51 0 01-57.53-24L54.48 166H88a6 6 0 000-12H40a6 6 0 00-6 6v48a6 6 0 0012 0v-33.52l18 18.05a93.45 93.45 0 0066 27.53h.52a93.38 93.38 0 0065.67-26.76 6 6 0 10-8.38-8.58z"/></svg>;
export default ArrowsClockwiseLight;
