// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowRight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 80v72a8 8 0 01-16 0V99.31l-98.34 98.35a8 8 0 01-11.32 0l-96-96a8 8 0 0111.32-11.32L120 180.69 212.69 88H160a8 8 0 010-16h72a8 8 0 018 8z"/></svg>;
export default ArrowElbowRight;
