// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowURightDownFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M221.66 181.66l-48 48a8 8 0 01-11.32 0l-48-48A8 8 0 01120 168h40V88a48 48 0 00-96 0v88a8 8 0 01-16 0V88a64 64 0 01128 0v80h40a8 8 0 015.66 13.66z"/></svg>;
export default ArrowURightDownFill;
