// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowLeftDownLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M238 72a6 6 0 01-6 6H94v123.51l37.76-37.75a6 6 0 018.48 8.48l-48 48a6 6 0 01-8.48 0l-48-48a6 6 0 018.48-8.48L82 201.51V72a6 6 0 016-6h144a6 6 0 016 6z"/></svg>;
export default ArrowElbowLeftDownLight;
