// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowDownLeft = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 32v144a8 8 0 01-8 8H67.31l34.35 34.34a8 8 0 01-11.32 11.32l-48-48a8 8 0 010-11.32l48-48a8 8 0 0111.32 11.32L67.31 168H184V32a8 8 0 0116 0z"/></svg>;
export default ArrowElbowDownLeft;
