// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsInCardinalThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M93.17 66.83a4 4 0 015.66-5.66L124 86.34V24a4 4 0 018 0v62.34l25.17-25.17a4 4 0 115.66 5.66l-32 32a4 4 0 01-5.66 0zm37.66 90.34a4 4 0 00-5.66 0l-32 32a4 4 0 005.66 5.66L124 169.66V232a4 4 0 008 0v-62.34l25.17 25.17a4 4 0 005.66-5.66zM232 124h-62.34l25.17-25.17a4 4 0 10-5.66-5.66l-32 32a4 4 0 000 5.66l32 32a4 4 0 005.66-5.66L169.66 132H232a4 4 0 000-8zm-133.17 1.17l-32-32a4 4 0 00-5.66 5.66L86.34 124H24a4 4 0 000 8h62.34l-25.17 25.17a4 4 0 005.66 5.66l32-32a4 4 0 000-5.66z"/></svg>;
export default ArrowsInCardinalThin;
