// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowLineUpThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M202.83 141.17a4 4 0 01-5.66 5.66L132 81.66V224a4 4 0 01-8 0V81.66l-65.17 65.17a4 4 0 01-5.66-5.66l72-72a4 4 0 015.66 0zM216 36H40a4 4 0 000 8h176a4 4 0 000-8z"/></svg>;
export default ArrowLineUpThin;
