// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowBendDoubleUpRight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M229.66 109.66l-48 48a8 8 0 01-11.32-11.32L212.69 104l-42.35-42.34a8 8 0 0111.32-11.32l48 48a8 8 0 010 11.32zm-48-11.32l-48-48a8 8 0 00-11.32 11.32L156.69 96H128A104.11 104.11 0 0024 200a8 8 0 0016 0 88.1 88.1 0 0188-88h28.69l-34.35 34.34a8 8 0 0011.32 11.32l48-48a8 8 0 000-11.32z"/></svg>;
export default ArrowBendDoubleUpRight;
