// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowSquareInBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M132 136v64a12 12 0 01-24 0v-35l-59.51 59.49a12 12 0 01-17-17L91 148H56a12 12 0 010-24h64a12 12 0 0112 12zm76-108H80a20 20 0 00-20 20v44a12 12 0 0024 0V52h120v120h-40a12 12 0 000 24h44a20 20 0 0020-20V48a20 20 0 00-20-20z"/></svg>;
export default ArrowSquareInBold;
