// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowRightLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M238 80v72a6 6 0 01-12 0V94.48L124.24 196.24a6 6 0 01-8.48 0l-96-96a6 6 0 018.48-8.48L120 183.51 217.52 86H160a6 6 0 010-12h72a6 6 0 016 6z"/></svg>;
export default ArrowElbowRightLight;
