// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowSquareRightThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 36H48a12 12 0 00-12 12v160a12 12 0 0012 12h160a12 12 0 0012-12V48a12 12 0 00-12-12zm4 172a4 4 0 01-4 4H48a4 4 0 01-4-4V48a4 4 0 014-4h160a4 4 0 014 4zm-41.17-82.83a4 4 0 010 5.66l-32 32a4 4 0 01-5.66-5.66L158.34 132H88a4 4 0 010-8h70.34l-25.17-25.17a4 4 0 015.66-5.66z"/></svg>;
export default ArrowSquareRightThin;
