// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsOutLineVertical = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 128a8 8 0 01-8 8H40a8 8 0 010-16h176a8 8 0 018 8zM101.66 53.66L120 35.31V96a8 8 0 0016 0V35.31l18.34 18.35a8 8 0 0011.32-11.32l-32-32a8 8 0 00-11.32 0l-32 32a8 8 0 0011.32 11.32zm52.68 148.68L136 220.69V160a8 8 0 00-16 0v60.69l-18.34-18.35a8 8 0 00-11.32 11.32l32 32a8 8 0 0011.32 0l32-32a8 8 0 00-11.32-11.32z"/></svg>;
export default ArrowsOutLineVertical;
