// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowLeft = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M237.66 101.66l-96 96a8 8 0 01-11.32 0L32 99.31V152a8 8 0 01-16 0V80a8 8 0 018-8h72a8 8 0 010 16H43.31L136 180.69l90.34-90.35a8 8 0 0111.32 11.32z"/></svg>;
export default ArrowElbowLeft;
