// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowsLeftRightLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M212.24 171.76a6 6 0 010 8.48l-32 32a6 6 0 01-8.48-8.48L193.51 182H48a6 6 0 010-12h145.51l-21.75-21.76a6 6 0 018.48-8.48zM75.76 116.24a6 6 0 008.48-8.48L62.49 86H208a6 6 0 000-12H62.49l21.75-21.76a6 6 0 00-8.48-8.48l-32 32a6 6 0 000 8.48z"/></svg>;
export default ArrowsLeftRightLight;
