// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowRightDownFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M229.66 165.66l-48 48a8 8 0 01-11.32 0l-48-48A8 8 0 01128 152h40V72H32a8 8 0 010-16h144a8 8 0 018 8v88h40a8 8 0 015.66 13.66z"/></svg>;
export default ArrowElbowRightDownFill;
