// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArrowElbowLeftBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240.49 104.49l-96 96a12 12 0 01-17 0L36 109v43a12 12 0 01-24 0V80a12 12 0 0112-12h72a12 12 0 010 24H53l83 83 87.51-87.52a12 12 0 0117 17z"/></svg>;
export default ArrowElbowLeftBold;
