// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ArticleNyTimesBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M156 92a12 12 0 0112-12h64a12 12 0 010 24h-64a12 12 0 01-12-12zm76 28h-64a12 12 0 000 24h64a12 12 0 000-24zm0 40H80a12 12 0 000 24h152a12 12 0 000-24zm0 40H80a12 12 0 000 24h152a12 12 0 000-24zM96 144a12 12 0 000-24h-4V68h24v4a12 12 0 0024 0V56a12 12 0 00-12-12H32a12 12 0 00-12 12v16a12 12 0 0024 0v-4h24v52h-4a12 12 0 000 24z"/></svg>;
export default ArticleNyTimesBold;
