// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const AsclepiusThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M212 79v1a36 36 0 01-36 36h-44v88h12a20 20 0 0013.33-34.91 4 4 0 115.34-6A28 28 0 01144 212h-12v20a4 4 0 01-8 0v-20H96a4 4 0 010-8h28v-88H96a20 20 0 000 40 4 4 0 010 8 28 28 0 010-56h28V24a4 4 0 018 0v84h44a28 28 0 0028-28v-1a27 27 0 00-27-27h-17a4 4 0 010-8h17a35 35 0 0135 35zM56 92H32a4 4 0 01-4-4v-8a36 36 0 0136-36h32a4 4 0 010 8h-4v4a36 36 0 01-36 36zm28-36v-4H64a28 28 0 00-28 28v4h20a28 28 0 0028-28z"/></svg>;
export default AsclepiusThin;
