// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BackspaceFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 40H68.53a16.12 16.12 0 00-13.72 7.77L9.14 123.88a8 8 0 000 8.24l45.67 76.11A16.11 16.11 0 0068.53 216H216a16 16 0 0016-16V56a16 16 0 00-16-16zm-50.34 106.34a8 8 0 01-11.32 11.32L136 139.31l-18.35 18.35a8 8 0 01-11.31-11.32L124.69 128l-18.35-18.34a8 8 0 1111.31-11.32L136 116.69l18.34-18.35a8 8 0 0111.32 11.32L147.31 128z"/></svg>;
export default BackspaceFill;
