// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BandaidsFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 116a12 12 0 11-12 12 12 12 0 0112-12zm84.28 39.72a40 40 0 11-56.56 56.56L128 184.57l-27.72 27.71a40 40 0 11-56.56-56.56L71.43 128l-27.71-27.72a40 40 0 1156.56-56.56L128 71.43l27.72-27.71a40 40 0 1156.56 56.56L184.57 128zm-95.59 17.53l-33.94-33.94L55 167a24 24 0 1034 34zM161.94 128L128 94.06 94.06 128 128 161.94zm39-39A24 24 0 10167 55l-27.69 27.75 33.94 33.94z"/></svg>;
export default BandaidsFill;
