// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BarricadeThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 68H32a12 12 0 00-12 12v72a12 12 0 0012 12h28v36a4 4 0 008 0v-36h120v36a4 4 0 008 0v-36h28a12 12 0 0012-12V80a12 12 0 00-12-12zm4 12v58.34L165.66 76H224a4 4 0 014 4zM32 76h50.34l80 80h-60.68L28 82.34V80a4 4 0 014-4zm-4 76V93.66L90.34 156H32a4 4 0 01-4-4zm196 4h-50.34l-80-80h60.68L228 149.66V152a4 4 0 01-4 4z"/></svg>;
export default BarricadeThin;
