// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BaseballHelmet = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M88 128a28 28 0 1028 28 28 28 0 00-28-28zm0 40a12 12 0 1112-12 12 12 0 01-12 12zm160-48h-24.3A104 104 0 0016 128v24a72.08 72.08 0 0072 72h40a72.08 72.08 0 0072-72v-16h48a8 8 0 000-16zm-64 32a56.06 56.06 0 01-50.46 55.72A71.87 71.87 0 00160 152v-16h24zm-32-32a8 8 0 00-8 8v24a56 56 0 01-112 0v-24a88 88 0 01175.64-8z"/></svg>;
export default BaseballHelmet;
