// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BatteryChargingLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 58H32a22 22 0 00-22 22v96a22 22 0 0022 22h168a22 22 0 0022-22V80a22 22 0 00-22-22zm10 118a10 10 0 01-10 10H32a10 10 0 01-10-10V80a10 10 0 0110-10h168a10 10 0 0110 10zm44-80v64a6 6 0 01-12 0V96a6 6 0 0112 0zm-116.9 28.85a6 6 0 01.27 5.83l-16 32a6 6 0 11-10.74-5.36L122.29 134H100a6 6 0 01-5.37-8.68l16-32a6 6 0 0110.74 5.36L109.71 122H132a6 6 0 015.1 2.85z"/></svg>;
export default BatteryChargingLight;
