// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BatteryMediumFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M112 96v64a8 8 0 01-8 8H48a8 8 0 01-8-8V96a8 8 0 018-8h56a8 8 0 018 8zm112-16v96a24 24 0 01-24 24H32a24 24 0 01-24-24V80a24 24 0 0124-24h168a24 24 0 0124 24zm-16 0a8 8 0 00-8-8H32a8 8 0 00-8 8v96a8 8 0 008 8h168a8 8 0 008-8zm40 8a8 8 0 00-8 8v64a8 8 0 0016 0V96a8 8 0 00-8-8z"/></svg>;
export default BatteryMediumFill;
