// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BatteryPlusVerticalFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M88 8a8 8 0 018-8h64a8 8 0 010 16H96a8 8 0 01-8-8zm112 48v168a24 24 0 01-24 24H80a24 24 0 01-24-24V56a24 24 0 0124-24h96a24 24 0 0124 24zm-36 84a8 8 0 00-8-8h-20v-20a8 8 0 00-16 0v20h-20a8 8 0 000 16h20v20a8 8 0 0016 0v-20h20a8 8 0 008-8z"/></svg>;
export default BatteryPlusVerticalFill;
