// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BatteryPlusLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M150 128a6 6 0 01-6 6h-22v22a6 6 0 01-12 0v-22H88a6 6 0 010-12h22v-22a6 6 0 0112 0v22h22a6 6 0 016 6zm72-48v96a22 22 0 01-22 22H32a22 22 0 01-22-22V80a22 22 0 0122-22h168a22 22 0 0122 22zm-12 0a10 10 0 00-10-10H32a10 10 0 00-10 10v96a10 10 0 0010 10h168a10 10 0 0010-10zm38 10a6 6 0 00-6 6v64a6 6 0 0012 0V96a6 6 0 00-6-6z"/></svg>;
export default BatteryPlusLight;
