// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BehanceLogoLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M112.15 122.36A36 36 0 0090 58H32a6 6 0 00-6 6v128a6 6 0 006 6h62a40 40 0 0018.15-75.64zM38 70h52a24 24 0 010 48H38zm56 116H38v-56h56a28 28 0 010 56zm68-106a6 6 0 016-6h64a6 6 0 010 12h-64a6 6 0 01-6-6zm38 26a46 46 0 1036.8 73.61 6 6 0 00-9.6-7.21 34 34 0 01-60.67-14.4H240a6 6 0 006-6 46.06 46.06 0 00-46-46zm-33.47 40a34 34 0 0166.94 0z"/></svg>;
export default BehanceLogoLight;
