// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BellSimpleSlash = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M53.92 34.62a8 8 0 10-11.84 10.76L58.82 63.8A79.59 79.59 0 0048 104c0 35.34-8.26 62.38-13.81 71.94A16 16 0 0048 200h134.64l19.44 21.38a8 8 0 1011.84-10.76zM48 184c7.7-13.24 16-43.92 16-80a63.65 63.65 0 016.26-27.62L168.09 184zm120 40a8 8 0 01-8 8H96a8 8 0 010-16h64a8 8 0 018 8zm46-44.75a8.13 8.13 0 01-2.93.55 8 8 0 01-7.44-5.08C196.35 156.19 192 129.75 192 104a64 64 0 00-95.57-55.69 8 8 0 01-7.9-13.91A80 80 0 01208 104c0 35.35 8.05 58.59 10.52 64.88a8 8 0 01-4.52 10.37z"/></svg>;
export default BellSimpleSlash;
