// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BellSimpleRingingFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M168 224a8 8 0 01-8 8H96a8 8 0 010-16h64a8 8 0 018 8zm59.39-163.68a111.36 111.36 0 00-39.12-43.08 8 8 0 10-8.54 13.53 94.13 94.13 0 0133.46 36.91 8 8 0 0014.2-7.36zM35.71 72a8 8 0 007.1-4.32 94.13 94.13 0 0133.46-36.91 8 8 0 10-8.54-13.53 111.36 111.36 0 00-39.12 43.08A8 8 0 0035.71 72zM208 112a80 80 0 00-160 0c0 26.28-4.78 48.39-13.81 63.94A16 16 0 0048 200h160a16 16 0 0013.79-24.06C212.78 160.38 208 138.27 208 112z"/></svg>;
export default BellSimpleRingingFill;
