// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BellSimpleFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M168 224a8 8 0 01-8 8H96a8 8 0 110-16h64a8 8 0 018 8zm53.81-48.06C216.25 166.38 208 139.33 208 104a80 80 0 10-160 0c0 35.34-8.26 62.38-13.81 71.94A16 16 0 0048 200h160a16 16 0 0013.8-24.06z"/></svg>;
export default BellSimpleFill;
