// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BellFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M221.8 175.94c-5.55-9.56-13.8-36.61-13.8-71.94a80 80 0 10-160 0c0 35.34-8.26 62.38-13.81 71.94A16 16 0 0048 200h40.81a40 40 0 0078.38 0H208a16 16 0 0013.8-24.06zM128 216a24 24 0 01-22.62-16h45.24A24 24 0 01128 216z"/></svg>;
export default BellFill;
