// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BinocularsLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M233 147.24L191.43 52.6a6 6 0 00-1.25-1.83 30 30 0 00-42.42 0A6 6 0 00146 55v27h-36V55a6 6 0 00-1.76-4.25 30 30 0 00-42.42 0 6 6 0 00-1.25 1.83L23 147.24A46 46 0 10110 168V94h36v74a46 46 0 1087-20.76zM64 202a34 34 0 1134-34 34 34 0 01-34 34zm0-80a45.77 45.77 0 00-18.55 3.92l29.61-67.38A18 18 0 0198 57.71V137a45.89 45.89 0 00-34-15zm94-64.28a18 18 0 0122.94.83l29.61 67.37A45.9 45.9 0 00158 137zM192 202a34 34 0 1134-34 34 34 0 01-34 34z"/></svg>;
export default BinocularsLight;
