// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BirdFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236.44 73.34l-23.23-15.48A60 60 0 00156 16h-.29C122.79 16.16 96 43.47 96 76.89v19.74L11.63 197.88l-.1.12A16 16 0 0024 224h88a104.11 104.11 0 00104-104v-19.72l20.44-13.62a8 8 0 000-13.32zm-110.29 59.78l-60 72a8 8 0 11-12.29-10.24l60-72a8 8 0 1112.29 10.24zM164 80a12 12 0 1112-12 12 12 0 01-12 12z"/></svg>;
export default BirdFill;
