// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BlueprintDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 64v136H48a24 24 0 010-48h16V64z" opacity=".2"/><path d="M232 56H72V40a8 8 0 00-8-8H48a32 32 0 00-32 32v112a32 32 0 0032 32h184a8 8 0 008-8V64a8 8 0 00-8-8zM32 64a16 16 0 0116-16h8v96h-8a31.82 31.82 0 00-16 4.29zm192 128H48a16 16 0 010-32h16a8 8 0 008-8V72h152zm-120-56a8 8 0 000 16h16v8a8 8 0 0016 0v-8h24v8a8 8 0 0016 0v-8h16a8 8 0 000-16h-16v-16h16a8 8 0 000-16h-16v-8a8 8 0 00-16 0v8h-24v-8a8 8 0 00-16 0v8h-16a8 8 0 000 16h16v16zm32-16h24v16h-24z"/></svg>;
export default BlueprintDuotone;
