// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BoneFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M231.12 107.72a35.91 35.91 0 01-46.19 6.8.14.14 0 00-.1 0l-70.35 70.36v.08a36 36 0 11-66.37 22.92 36 36 0 1122.92-66.37.14.14 0 00.1 0l70.35-70.36v-.08a36 36 0 1166.37-22.92 36 36 0 0123.27 59.57z"/></svg>;
export default BoneFill;
