// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Bookmark = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M184 32H72a16 16 0 00-16 16v176a8 8 0 0012.24 6.78L128 193.43l59.77 37.35A8 8 0 00200 224V48a16 16 0 00-16-16zm0 16v113.57l-51.77-32.35a8 8 0 00-8.48 0L72 161.56V48zm-51.77 129.22a8 8 0 00-8.48 0L72 209.57v-29.14l56-35 56 35v29.14z"/></svg>;
export default Bookmark;
