// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BookOpenTextBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 44h-72a43.86 43.86 0 00-32 13.85A43.86 43.86 0 0096 44H24a12 12 0 00-12 12v144a12 12 0 0012 12h72a20 20 0 0120 20 12 12 0 0024 0 20 20 0 0120-20h72a12 12 0 0012-12V56a12 12 0 00-12-12zM96 188H36V68h60a20 20 0 0120 20v104.81A43.79 43.79 0 0096 188zm124 0h-60a43.71 43.71 0 00-20 4.83V88a20 20 0 0120-20h60zm-56-92h32a12 12 0 010 24h-32a12 12 0 010-24zm44 52a12 12 0 01-12 12h-32a12 12 0 010-24h32a12 12 0 0112 12z"/></svg>;
export default BookOpenTextBold;
