// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BuildingOfficeFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248 208h-16V96a8 8 0 000-16h-48V48a8 8 0 000-16H40a8 8 0 000 16v160H24a8 8 0 000 16h224a8 8 0 000-16zM80 72h16a8 8 0 010 16H80a8 8 0 010-16zm-8 48a8 8 0 018-8h16a8 8 0 010 16H80a8 8 0 01-8-8zm64 88H88v-48h48zm8-80h-16a8 8 0 010-16h16a8 8 0 010 16zm0-40h-16a8 8 0 010-16h16a8 8 0 010 16zm72 120h-32V96h32z"/></svg>;
export default BuildingOfficeFill;
