// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const BuildingThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 228h-28V28h12a4 4 0 000-8H40a4 4 0 000 8h12v200H24a4 4 0 000 8h208a4 4 0 000-8zM60 28h136v200h-40v-44a4 4 0 00-4-4h-48a4 4 0 00-4 4v44H60zm88 200h-40v-40h40zM92 64a4 4 0 014-4h16a4 4 0 010 8H96a4 4 0 01-4-4zm48 0a4 4 0 014-4h16a4 4 0 010 8h-16a4 4 0 01-4-4zm-48 40a4 4 0 014-4h16a4 4 0 010 8H96a4 4 0 01-4-4zm48 0a4 4 0 014-4h16a4 4 0 010 8h-16a4 4 0 01-4-4zm-44 44a4 4 0 010-8h16a4 4 0 010 8zm44-4a4 4 0 014-4h16a4 4 0 010 8h-16a4 4 0 01-4-4z"/></svg>;
export default BuildingThin;
