// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CalendarMinusBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 28h-20v-4a12 12 0 00-24 0v4H92v-4a12 12 0 00-24 0v4H48a20 20 0 00-20 20v160a20 20 0 0020 20h160a20 20 0 0020-20V48a20 20 0 00-20-20zM68 52a12 12 0 0024 0h72a12 12 0 0024 0h16v24H52V52zM52 204V100h152v104zm112-52a12 12 0 01-12 12h-48a12 12 0 010-24h48a12 12 0 0112 12z"/></svg>;
export default CalendarMinusBold;
