// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CameraPlusBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M172 136a12 12 0 01-12 12h-20v20a12 12 0 01-24 0v-20H96a12 12 0 010-24h20v-20a12 12 0 0124 0v20h20a12 12 0 0112 12zm64-56v112a28 28 0 01-28 28H48a28 28 0 01-28-28V80a28 28 0 0128-28h25.58l10.06-15.09A20 20 0 01100.28 28h55.44a20 20 0 0116.64 8.91L182.42 52H208a28 28 0 0128 28zm-24 0a4 4 0 00-4-4h-32a12 12 0 01-10-5.34L153.58 52h-51.16L90 70.66A12 12 0 0180 76H48a4 4 0 00-4 4v112a4 4 0 004 4h160a4 4 0 004-4z"/></svg>;
export default CameraPlusBold;
