// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CameraLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 58h-28.79L165 36.67a6 6 0 00-5-2.67H96a6 6 0 00-5 2.67L76.78 58H48a22 22 0 00-22 22v112a22 22 0 0022 22h160a22 22 0 0022-22V80a22 22 0 00-22-22zm10 134a10 10 0 01-10 10H48a10 10 0 01-10-10V80a10 10 0 0110-10h32a6 6 0 005-2.67L99.21 46h57.57L171 67.33a6 6 0 005 2.67h32a10 10 0 0110 10zM128 90a42 42 0 1042 42 42 42 0 00-42-42zm0 72a30 30 0 1130-30 30 30 0 01-30 30z"/></svg>;
export default CameraLight;
