// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CameraRotateFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 56h-27.72l-13.63-20.44A8 8 0 00160 32H96a8 8 0 00-6.65 3.56L75.71 56H48a24 24 0 00-24 24v112a24 24 0 0024 24h160a24 24 0 0024-24V80a24 24 0 00-24-24zm-51.19 110.4A48.21 48.21 0 0196 163.77V168a8 8 0 01-16 0v-24a8 8 0 018-8h24a8 8 0 010 16h-5.15a32.12 32.12 0 0040.34 1.61 8 8 0 019.62 12.79zM176 120a8 8 0 01-8 8h-24a8 8 0 010-16h5.15a32.12 32.12 0 00-40.34-1.61 8 8 0 01-9.62-12.79 48.21 48.21 0 0160.81 2.63V96a8 8 0 0116 0z"/></svg>;
export default CameraRotateFill;
