// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CarProfileBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236 108h-23l-42.17-42.14A19.86 19.86 0 00156.69 60H48.28a20 20 0 00-16.64 8.91L2 113.34A12 12 0 000 120v48a20 20 0 0020 20h13.5a34 34 0 0065 0h59a34 34 0 0065 0H236a20 20 0 0020-20v-40a20 20 0 00-20-20zM50.42 84H155l24 24H34.42zM66 188a10 10 0 1110-10 10 10 0 01-10 10zm124 0a10 10 0 1110-10 10 10 0 01-10 10zm42-24h-11a34 34 0 00-62 0H97a34 34 0 00-62 0H24v-32h208z"/></svg>;
export default CarProfileBold;
