// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CardsThreeBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 96H48a20 20 0 00-20 20v84a20 20 0 0020 20h160a20 20 0 0020-20v-84a20 20 0 00-20-20zm-4 100H52v-76h152zM44 68a12 12 0 0112-12h144a12 12 0 010 24H56a12 12 0 01-12-12zm16-40a12 12 0 0112-12h112a12 12 0 010 24H72a12 12 0 01-12-12z"/></svg>;
export default CardsThreeBold;
