// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CardholderFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 48H48a24 24 0 00-24 24v112a24 24 0 0024 24h160a24 24 0 0024-24V72a24 24 0 00-24-24zm-56 72a24 24 0 01-48 0 8 8 0 00-8-8H40V96h176v16h-56a8 8 0 00-8 8zM48 64h160a8 8 0 018 8v8H40v-8a8 8 0 018-8z"/></svg>;
export default CardholderFill;
