// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CardsThreeDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 104v96a8 8 0 01-8 8H48a8 8 0 01-8-8v-96a8 8 0 018-8h160a8 8 0 018 8z" opacity=".2"/><path d="M208 88H48a16 16 0 00-16 16v96a16 16 0 0016 16h160a16 16 0 0016-16v-96a16 16 0 00-16-16zm0 112H48v-96h160v96zM48 64a8 8 0 018-8h144a8 8 0 010 16H56a8 8 0 01-8-8zm16-32a8 8 0 018-8h112a8 8 0 010 16H72a8 8 0 01-8-8z"/></svg>;
export default CardsThreeDuotone;
