// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretLineLeftFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 48v160a8 8 0 01-13.66 5.66l-80-80a8 8 0 010-11.32l80-80A8 8 0 01200 48zM72 40a8 8 0 00-8 8v160a8 8 0 0016 0V48a8 8 0 00-8-8z"/></svg>;
export default CaretLineLeftFill;
