// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretLeftBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M168.49 199.51a12 12 0 01-17 17l-80-80a12 12 0 010-17l80-80a12 12 0 0117 17L97 128z"/></svg>;
export default CaretLeftBold;
