// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretCircleLeftFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm21.66 138.34a8 8 0 01-11.32 11.32l-40-40a8 8 0 010-11.32l40-40a8 8 0 0111.32 11.32L115.31 128z"/></svg>;
export default CaretCircleLeftFill;
