// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretUpDown = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M181.66 170.34a8 8 0 010 11.32l-48 48a8 8 0 01-11.32 0l-48-48a8 8 0 0111.32-11.32L128 212.69l42.34-42.35a8 8 0 0111.32 0zm-96-84.68L128 43.31l42.34 42.35a8 8 0 0011.32-11.32l-48-48a8 8 0 00-11.32 0l-48 48a8 8 0 0011.32 11.32z"/></svg>;
export default CaretUpDown;
