// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretCircleDoubleDownFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M201.57 54.43A104.15 104.15 0 10232 128a104.17 104.17 0 00-30.43-73.57zm-35.9 95.24l-32 32a8 8 0 01-11.32 0l-32-32a8 8 0 1111.32-11.32L128 164.71l26.35-26.36a8 8 0 1111.32 11.32zm0-56l-32 32a8 8 0 01-11.32 0l-32-32a8 8 0 1111.32-11.32L128 108.68l26.35-26.36a8 8 0 1111.32 11.32z"/></svg>;
export default CaretCircleDoubleDownFill;
