// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CellSignalSlashThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M84 152v48a4 4 0 01-8 0v-48a4 4 0 018 0zm-44 36a4 4 0 00-4 4v8a4 4 0 008 0v-8a4 4 0 00-4-4zm171 25.31l-160-176a4 4 0 00-6 5.38l71 78.06V200a4 4 0 008 0v-70.45l32 35.2V200a4 4 0 008 0v-26.45l41 45.14a4 4 0 105.92-5.38zm-51-93.68a4 4 0 004-4V72a4 4 0 00-8 0v43.63a4 4 0 004 4zm40 44a4 4 0 004-4V32a4 4 0 00-8 0v127.63a4 4 0 004 4z"/></svg>;
export default CellSignalSlashThin;
