// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CellSignalHighFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M198.12 25.23a16 16 0 00-17.44 3.46l-160 160A16 16 0 0032 216h160a16 16 0 0016-16V40a15.94 15.94 0 00-9.88-14.77zM192 200h-24V64l24-24z"/></svg>;
export default CellSignalHighFill;
