// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChalkboardSimple = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 192h-8v-24a8 8 0 00-8-8h-64a8 8 0 00-8 8v24H40V56h176v80a8 8 0 0016 0V56a16 16 0 00-16-16H40a16 16 0 00-16 16v136h-8a8 8 0 000 16h224a8 8 0 000-16zm-72-16h48v16h-48z"/></svg>;
export default ChalkboardSimple;
