// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartScatterLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M230 208a6 6 0 01-6 6H32a6 6 0 01-6-6V48a6 6 0 0112 0v154h186a6 6 0 016 6zm-98-50a10 10 0 10-10-10 10 10 0 0010 10zm-24-56a10 10 0 10-10-10 10 10 0 0010 10zm-32 72a10 10 0 10-10-10 10 10 0 0010 10zm96-48a10 10 0 10-10-10 10 10 0 0010 10zm24-40a10 10 0 10-10-10 10 10 0 0010 10zm-8 68a10 10 0 1010 10 10 10 0 00-10-10z"/></svg>;
export default ChartScatterLight;
