// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartLineUpDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 64v144H32V48h176a16 16 0 0116 16z" opacity=".2"/><path d="M232 208a8 8 0 01-8 8H32a8 8 0 01-8-8V48a8 8 0 0116 0v108.69l50.34-50.35a8 8 0 0111.32 0L128 132.69 180.69 80H160a8 8 0 010-16h40a8 8 0 018 8v40a8 8 0 01-16 0V91.31l-58.34 58.35a8 8 0 01-11.32 0L96 123.31l-56 56V200h184a8 8 0 018 8z"/></svg>;
export default ChartLineUpDuotone;
