// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartBarHorizontalLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 98h-42V56a6 6 0 00-6-6H54V40a6 6 0 00-12 0v176a6 6 0 0012 0v-10h90a6 6 0 006-6v-42h74a6 6 0 006-6v-48a6 6 0 00-6-6zm-54-36v36H54V62zm-32 132H54v-36h84zm80-48H54v-36h164z"/></svg>;
export default ChartBarHorizontalLight;
