// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChartPieSliceFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M100 116.43a8 8 0 004-6.93v-72A8 8 0 0093.34 30a104.06 104.06 0 00-67.61 117 8 8 0 004.52 5.81 7.86 7.86 0 003.35.74 8 8 0 004-1.07zM88 49.62v55.26l-47.88 27.63C40 131 40 129.48 40 128a88.12 88.12 0 0148-78.38zM232 128a104 104 0 01-193.68 52.7 8 8 0 012.87-11L120 123.83V32a8 8 0 018-8 104.05 104.05 0 0189.74 51.48c.11.16.21.32.31.49s.2.37.29.55A103.34 103.34 0 01232 128z"/></svg>;
export default ChartPieSliceFill;
