// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChatCenteredDotsDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 56v128a8 8 0 01-8 8h-65.07l-16 28a8 8 0 01-13.9 0l-16-28H40a8 8 0 01-8-8V56a8 8 0 018-8h176a8 8 0 018 8z" opacity=".2"/><path d="M116 120a12 12 0 1112 12 12 12 0 01-12-12zm-32 12a12 12 0 10-12-12 12 12 0 0012 12zm88 0a12 12 0 10-12-12 12 12 0 0012 12zm60-76v128a16 16 0 01-16 16h-60.43l-13.68 23.94a16 16 0 01-27.78 0L100.43 200H40a16 16 0 01-16-16V56a16 16 0 0116-16h176a16 16 0 0116 16zm-16 0H40v128h65.07a8 8 0 017 4l16 28 16-28a8 8 0 017-4H216z"/></svg>;
export default ChatCenteredDotsDuotone;
