// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChatsTeardropBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M172.29 68.9A84 84 0 0012 104v64a20 20 0 0020 20h52.1a84.18 84.18 0 0075.9 48h64a20 20 0 0020-20v-64a84 84 0 00-71.71-83.1zM36 104a60 60 0 1160 60H36zm184 108h-60a60.14 60.14 0 01-49-25.37 83.93 83.93 0 0068.55-91.37A60 60 0 01220 152z"/></svg>;
export default ChatsTeardropBold;
