// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChatTextLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 50H40a14 14 0 00-14 14v160a13.88 13.88 0 008.09 12.69A14.11 14.11 0 0040 238a13.87 13.87 0 009-3.31l.06-.05L82.23 206H216a14 14 0 0014-14V64a14 14 0 00-14-14zm2 142a2 2 0 01-2 2H80a6 6 0 00-3.92 1.46l-34.82 30.07A2 2 0 0138 224V64a2 2 0 012-2h176a2 2 0 012 2zm-52-80a6 6 0 01-6 6H96a6 6 0 010-12h64a6 6 0 016 6zm0 32a6 6 0 01-6 6H96a6 6 0 010-12h64a6 6 0 016 6z"/></svg>;
export default ChatTextLight;
