// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChatCenteredSlashDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 56v128a8 8 0 01-8 8h-65.07l-16 28a8 8 0 01-13.9 0l-16-28H40a8 8 0 01-8-8V56a8 8 0 018-8h176a8 8 0 018 8z" opacity=".2"/><path d="M53.92 34.62A8 8 0 0040 40a16 16 0 00-16 16v128a16 16 0 0016 16h60.43l13.68 23.94a16 16 0 0027.78 0L155.57 200h27.07l19.44 21.38a8 8 0 1011.84-10.76zm97 149.38a8 8 0 00-7 4l-16 28-16-28a8 8 0 00-7-4H40V56h11.73L168.1 184zM232 56v130a8 8 0 01-16 0V56H98.52a8 8 0 110-16H216a16 16 0 0116 16z"/></svg>;
export default ChatCenteredSlashDuotone;
