// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CheckSquareOffsetBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 48v160a20 20 0 01-20 20h-68a12 12 0 010-24h64V52H52v88a12 12 0 01-24 0V48a20 20 0 0120-20h160a20 20 0 0120 20zm-99.51 103.51a12 12 0 00-17 0L64 199l-15.51-15.49a12 12 0 10-17 17l24 24a12 12 0 0017 0l56-56a12 12 0 000-17z"/></svg>;
export default CheckSquareOffsetBold;
