// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CheckerboardFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 32H48a16 16 0 00-16 16v160a16 16 0 0016 16h160a16 16 0 0016-16V48a16 16 0 00-16-16zm0 176h-80v-80H48V48h80v80h80v80z"/></svg>;
export default CheckerboardFill;
