// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CheckDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 56v144a16 16 0 01-16 16H40a16 16 0 01-16-16V56a16 16 0 0116-16h176a16 16 0 0116 16z" opacity=".2"/><path d="M205.66 85.66l-96 96a8 8 0 01-11.32 0l-40-40a8 8 0 0111.32-11.32L104 164.69l90.34-90.35a8 8 0 0111.32 11.32z"/></svg>;
export default CheckDuotone;
