// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CirclesThreePlus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M80 40a40 40 0 1040 40 40 40 0 00-40-40zm0 64a24 24 0 1124-24 24 24 0 01-24 24zm96 16a40 40 0 10-40-40 40 40 0 0040 40zm0-64a24 24 0 11-24 24 24 24 0 0124-24zm-96 80a40 40 0 1040 40 40 40 0 00-40-40zm0 64a24 24 0 1124-24 24 24 0 01-24 24zm136-24a8 8 0 01-8 8h-24v24a8 8 0 01-16 0v-24h-24a8 8 0 010-16h24v-24a8 8 0 0116 0v24h24a8 8 0 018 8z"/></svg>;
export default CirclesThreePlus;
