// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CircleNotchFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 176A72 72 0 0192 65.64a8 8 0 018 13.85 56 56 0 1056 0 8 8 0 018-13.85A72 72 0 01128 200z"/></svg>;
export default CircleNotchFill;
