// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CityDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M32 40h64v176H32zm128 48v128h64V88z" opacity=".2"/><path d="M240 208h-8V88a8 8 0 00-8-8h-64a8 8 0 00-8 8v40h-48V40a8 8 0 00-8-8H32a8 8 0 00-8 8v168h-8a8 8 0 000 16h224a8 8 0 000-16zM168 96h48v112h-48zm-16 48v64h-48v-64zM40 48h48v160H40zm32 24v16a8 8 0 01-16 0V72a8 8 0 0116 0zm0 48v16a8 8 0 01-16 0v-16a8 8 0 0116 0zm0 48v16a8 8 0 01-16 0v-16a8 8 0 0116 0zm48 16v-16a8 8 0 0116 0v16a8 8 0 01-16 0zm64 0v-16a8 8 0 0116 0v16a8 8 0 01-16 0zm0-48v-16a8 8 0 0116 0v16a8 8 0 01-16 0z"/></svg>;
export default CityDuotone;
