// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ClockClockwiseBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M140 80v41.21l34.17 20.5a12 12 0 11-12.34 20.58l-40-24A12 12 0 01116 128V80a12 12 0 0124 0zm84-28a12 12 0 00-12 12v7.37c-4.21-4.67-8.58-9.31-13.29-14.08a100 100 0 10-2.07 143.44 12 12 0 00-16.48-17.46 76 76 0 111.53-109.06C187.61 80.2 193 86 198.23 92H184a12 12 0 000 24h40a12 12 0 0012-12V64a12 12 0 00-12-12z"/></svg>;
export default ClockClockwiseBold;
