// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CloudSlash = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M53.92 34.62a8 8 0 10-11.84 10.76l39.24 43.17-.06.12A65 65 0 0072 88a64 64 0 000 128h88a87.34 87.34 0 0031.8-5.93l10.28 11.31a8 8 0 1011.84-10.76zM160 200H72a48 48 0 010-96c1.1 0 2.2 0 3.3.12A88.4 88.4 0 0072 128a8 8 0 0016 0 72.25 72.25 0 015.06-26.54l87 95.7A71.66 71.66 0 01160 200zm88-72a87.89 87.89 0 01-22.35 58.61A8 8 0 01213.71 176a72 72 0 00-96.34-106 8 8 0 01-9.48-12.89A88 88 0 01248 128z"/></svg>;
export default CloudSlash;
