// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CloudArrowDownLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M246 128a85.27 85.27 0 01-17.2 51.6 6 6 0 11-9.6-7.2A74 74 0 1086 128a6 6 0 01-12 0 85.54 85.54 0 013.91-25.64A50.68 50.68 0 0072 102a50 50 0 000 100h24a6 6 0 010 12H72A62 62 0 1182.43 90.88 86 86 0 01246 128zm-66.24 43.76L158 193.51V128a6 6 0 00-12 0v65.51l-21.76-21.75a6 6 0 00-8.48 8.48l32 32a6 6 0 008.48 0l32-32a6 6 0 00-8.48-8.48z"/></svg>;
export default CloudArrowDownLight;
