// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CodaLogoThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 84a43.82 43.82 0 0123.69 6.73A8 8 0 00212 84V48a12 12 0 00-12-12H56a12 12 0 00-12 12v160a12 12 0 0012 12h144a12 12 0 0012-12v-36a8 8 0 00-12.28-6.75c-8 5.14-14.82 7.09-23.56 6.74H176a44 44 0 010-88zm-52 44a52.05 52.05 0 0051.92 52c10.35.4 18.76-2 28.08-8v36a4 4 0 01-4 4H56a4 4 0 01-4-4V48a4 4 0 014-4h144a4 4 0 014 4v36a52.24 52.24 0 00-80 44z"/></svg>;
export default CodaLogoThin;
