// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CodaLogo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 88a39.79 39.79 0 0121.53 6.1A12 12 0 00216 84V48a16 16 0 00-16-16H56a16 16 0 00-16 16v160a16 16 0 0016 16h144a16 16 0 0016-16v-36a12 12 0 00-18.44-10.11c-7.25 4.65-13.41 6.41-21.24 6.11H176a40 40 0 010-80zm-56 40a56.07 56.07 0 0055.84 56 48.37 48.37 0 0024.16-5.11V208H56V48h144v29.23A56.3 56.3 0 00120 128z"/></svg>;
export default CodaLogo;
