// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CodeThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M66.56 91.07L22.25 128l44.31 36.93A4 4 0 0164 172a3.94 3.94 0 01-2.56-.93l-48-40a4 4 0 010-6.14l48-40a4 4 0 015.12 6.14zm176 33.86l-48-40a4 4 0 10-5.12 6.14L233.75 128l-44.31 36.93a4 4 0 105.12 6.14l48-40a4 4 0 000-6.14zm-81.19-88.69a4 4 0 00-5.13 2.39l-64 176a4 4 0 002.39 5.13A4.12 4.12 0 0096 220a4 4 0 003.76-2.63l64-176a4 4 0 00-2.39-5.13z"/></svg>;
export default CodeThin;
