// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CodeLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M67.84 92.61L25.37 128l42.47 35.39a6 6 0 11-7.68 9.22l-48-40a6 6 0 010-9.22l48-40a6 6 0 017.68 9.22zm176 30.78l-48-40a6 6 0 10-7.68 9.22L230.63 128l-42.47 35.39a6 6 0 107.68 9.22l48-40a6 6 0 000-9.22zm-81.79-89a6 6 0 00-7.69 3.61l-64 176a6 6 0 003.64 7.64 6.15 6.15 0 002 .36 6 6 0 005.64-3.95l64-176a6 6 0 00-3.59-7.69z"/></svg>;
export default CodeLight;
