// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CompassThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 28a100 100 0 10100 100A100.11 100.11 0 00128 28zm0 192a92 92 0 1192-92 92.1 92.1 0 01-92 92zm46.21-143.58l-64 32a4.08 4.08 0 00-1.79 1.79l-32 64A4 4 0 0080 180a4.05 4.05 0 001.79-.42l64-32a4.08 4.08 0 001.79-1.79l32-64a4 4 0 00-5.37-5.37zM141 141l-52.08 26L115 115l52.08-26z"/></svg>;
export default CompassThin;
