// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ControlFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M207.39 123.06A8 8 0 01200 128H56a8 8 0 01-5.66-13.66l72-72a8 8 0 0111.32 0l72 72a8 8 0 011.73 8.72z"/></svg>;
export default ControlFill;
