// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CookieThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M161.66 166.34a8 8 0 11-11.32 0 8 8 0 0111.32 0zm-75.32-8a8 8 0 1011.32 0 8 8 0 00-11.32 0zm3.32-56a8 8 0 100 11.32 8 8 0 000-11.32zm36.68 16a8 8 0 1011.32 0 8 8 0 00-11.32 0zM228 128A100 100 0 11128 28a4 4 0 014 4 44.05 44.05 0 0044 44 4 4 0 014 4 44.05 44.05 0 0044 44 4 4 0 014 4zm-8.08 3.84a52.08 52.08 0 01-47.78-48 52.08 52.08 0 01-48-47.78 92 92 0 1095.76 95.76z"/></svg>;
export default CookieThin;
