// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CopyrightDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 128a96 96 0 11-96-96 96 96 0 0196 96z" opacity=".2"/><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm-32-88a32 32 0 0057.6 19.2 8 8 0 0112.8 9.61 48 48 0 110-57.62 8 8 0 01-12.8 9.61A32 32 0 0096 128z"/></svg>;
export default CopyrightDuotone;
