// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CraneBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M230.17 13.71a12 12 0 00-11.82-.3L101 76H32a20 20 0 00-20 20v104a20 20 0 0020 20h88a20 20 0 0020-20v-32a11.86 11.86 0 00-.51-3.45L118.32 94 212 44v112h-12v-4a12 12 0 00-24 0v8a20 20 0 0020 20h20a20 20 0 0020-20V24a12 12 0 00-5.83-10.29zM95.07 100l16.8 56H76v-56zM52 100v56H36v-56zm-16 96v-16h80v16z"/></svg>;
export default CraneBold;
