// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CricketThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240.49 84.2L187.8 31.51a12 12 0 00-17 0L63.52 138.83a12 12 0 000 17L87 179.31l-49.83 49.86a4 4 0 005.66 5.66L92.69 185l23.51 23.51a12 12 0 0017 0l107.29-107.34a12 12 0 000-16.97zm-113 118.63a4 4 0 01-5.66 0l-23.49-23.52 32.49-32.48a4 4 0 00-5.66-5.66l-32.48 32.49-23.52-23.52a4 4 0 010-5.66L105.66 108H164v58.34zM234.83 95.51L172 158.34V104a4 4 0 00-4-4h-54.34l62.83-62.83a4 4 0 015.66 0l52.68 52.68a4 4 0 010 5.66zM60 84a24 24 0 10-24-24 24 24 0 0024 24zm0-40a16 16 0 11-16 16 16 16 0 0116-16z"/></svg>;
export default CricketThin;
