// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CropDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 64v128H64V64z" opacity=".2"/><path d="M240 192a8 8 0 01-8 8h-32v32a8 8 0 01-16 0v-32H64a8 8 0 01-8-8V72H24a8 8 0 010-16h32V24a8 8 0 0116 0v160h160a8 8 0 018 8zM96 72h88v88a8 8 0 0016 0V64a8 8 0 00-8-8H96a8 8 0 000 16z"/></svg>;
export default CropDuotone;
