// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CrosshairSimple = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm8 191.63V184a8 8 0 00-16 0v31.63A88.13 88.13 0 0140.37 136H72a8 8 0 000-16H40.37A88.13 88.13 0 01120 40.37V72a8 8 0 0016 0V40.37A88.13 88.13 0 01215.63 120H184a8 8 0 000 16h31.63A88.13 88.13 0 01136 215.63z"/></svg>;
export default CrosshairSimple;
