// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CrosshairBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 116h-4.72A100.21 100.21 0 00140 28.72V24a12 12 0 00-24 0v4.72A100.21 100.21 0 0028.72 116H24a12 12 0 000 24h4.72A100.21 100.21 0 00116 227.28V232a12 12 0 0024 0v-4.72A100.21 100.21 0 00227.28 140H232a12 12 0 000-24zm-92 87v-3a12 12 0 00-24 0v3a76.15 76.15 0 01-63-63h3a12 12 0 000-24h-3a76.15 76.15 0 0163-63v3a12 12 0 0024 0v-3a76.15 76.15 0 0163 63h-3a12 12 0 000 24h3a76.15 76.15 0 01-63 63zM128 84a44 44 0 1044 44 44.05 44.05 0 00-44-44zm0 64a20 20 0 1120-20 20 20 0 01-20 20z"/></svg>;
export default CrosshairBold;
