// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyRubThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M148 36H88a4 4 0 00-4 4v100H56a4 4 0 000 8h28v24H56a4 4 0 000 8h28v36a4 4 0 008 0v-36h52a4 4 0 000-8H92v-24h56a56 56 0 000-112zm0 104H92V44h56a48 48 0 010 96z"/></svg>;
export default CurrencyRubThin;
