// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyRubLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M148 150a58 58 0 000-116H88a6 6 0 00-6 6v98H56a6 6 0 000 12h26v20H56a6 6 0 000 12h26v34a6 6 0 0012 0v-34h50a6 6 0 000-12H94v-20zM94 46h54a46 46 0 010 92H94z"/></svg>;
export default CurrencyRubLight;
