// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyCircleDollarFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm12 152h-4v8a8 8 0 01-16 0v-8h-16a8 8 0 010-16h36a12 12 0 000-24h-24a28 28 0 010-56h4v-8a8 8 0 0116 0v8h16a8 8 0 010 16h-36a12 12 0 000 24h24a28 28 0 010 56z"/></svg>;
export default CurrencyCircleDollarFill;
