// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyEurFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 80a8 8 0 010 16H88v16h24a8 8 0 010 16H88.81a40 40 0 0065.86 21.82 8 8 0 1110.66 11.92A56 56 0 0172.58 152H64a8 8 0 010-16h8v-16h-8a8 8 0 010-16h8.58a56 56 0 0192.75-33.74 8 8 0 11-10.66 11.92A40 40 0 0088.81 104z"/></svg>;
export default CurrencyEurFill;
