// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyInr = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 80a8 8 0 01-8 8h-32.15c.09 1.32.15 2.65.15 4a60.07 60.07 0 01-60 60H92.69l72.69 66.08a8 8 0 11-10.76 11.84l-88-80A8 8 0 0172 136h36a44.05 44.05 0 0044-44c0-1.35-.07-2.68-.19-4H72a8 8 0 010-16h75.17A44 44 0 00108 48H72a8 8 0 010-16h128a8 8 0 010 16h-51.26a60.13 60.13 0 0115.82 24H200a8 8 0 018 8z"/></svg>;
export default CurrencyInr;
