// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CurrencyDollarSimpleBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M204 168a52.06 52.06 0 01-52 52h-12v12a12 12 0 01-24 0v-12h-12a52.06 52.06 0 01-52-52 12 12 0 0124 0 28 28 0 0028 28h48a28 28 0 000-56h-40a52 52 0 010-104h4V24a12 12 0 0124 0v12h4a52.06 52.06 0 0152 52 12 12 0 01-24 0 28 28 0 00-28-28h-32a28 28 0 000 56h40a52.06 52.06 0 0152 52z"/></svg>;
export default CurrencyDollarSimpleBold;
