// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeskFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248 64H8a8 8 0 000 16h8v112a8 8 0 0016 0v-48h192v48a8 8 0 0016 0V80h8a8 8 0 000-16zM80 112H56a8 8 0 010-16h24a8 8 0 010 16zm56 8a8 8 0 01-16 0V88a8 8 0 0116 0zm64-8h-24a8 8 0 010-16h24a8 8 0 010 16z"/></svg>;
export default DeskFill;
