// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeskThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248 68H8a4 4 0 000 8h12v116a4 4 0 008 0v-52h200v52a4 4 0 008 0V76h12a4 4 0 000-8zM28 76h96v56H28zm200 56h-96V76h96zM92 104a4 4 0 01-4 4H64a4 4 0 010-8h24a4 4 0 014 4zm72 0a4 4 0 014-4h24a4 4 0 010 8h-24a4 4 0 01-4-4z"/></svg>;
export default DeskThin;
