// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceTabletSpeakerLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 26H64a22 22 0 00-22 22v160a22 22 0 0022 22h128a22 22 0 0022-22V48a22 22 0 00-22-22zm10 182a10 10 0 01-10 10H64a10 10 0 01-10-10V48a10 10 0 0110-10h128a10 10 0 0110 10zM166 64a6 6 0 01-6 6H96a6 6 0 010-12h64a6 6 0 016 6z"/></svg>;
export default DeviceTabletSpeakerLight;
