// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceTabletCameraThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 28H64a20 20 0 00-20 20v160a20 20 0 0020 20h128a20 20 0 0020-20V48a20 20 0 00-20-20zm12 180a12 12 0 01-12 12H64a12 12 0 01-12-12V48a12 12 0 0112-12h128a12 12 0 0112 12zM136 68a8 8 0 11-8-8 8 8 0 018 8z"/></svg>;
export default DeviceTabletCameraThin;
