// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DeviceMobileCameraBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 12H80a28 28 0 00-28 28v176a28 28 0 0028 28h96a28 28 0 0028-28V40a28 28 0 00-28-28zm4 204a4 4 0 01-4 4H80a4 4 0 01-4-4V40a4 4 0 014-4h96a4 4 0 014 4zM144 68a16 16 0 11-16-16 16 16 0 0116 16z"/></svg>;
export default DeviceMobileCameraBold;
