// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DiceFiveLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 34H64a30 30 0 00-30 30v128a30 30 0 0030 30h128a30 30 0 0030-30V64a30 30 0 00-30-30zm18 158a18 18 0 01-18 18H64a18 18 0 01-18-18V64a18 18 0 0118-18h128a18 18 0 0118 18zM102 92a10 10 0 11-10-10 10 10 0 0110 10zm36 36a10 10 0 11-10-10 10 10 0 0110 10zm36-36a10 10 0 11-10-10 10 10 0 0110 10zm-72 72a10 10 0 11-10-10 10 10 0 0110 10zm72 0a10 10 0 11-10-10 10 10 0 0110 10z"/></svg>;
export default DiceFiveLight;
