// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DiceOneDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 64v128a24 24 0 01-24 24H64a24 24 0 01-24-24V64a24 24 0 0124-24h128a24 24 0 0124 24z" opacity=".2"/><path d="M192 32H64a32 32 0 00-32 32v128a32 32 0 0032 32h128a32 32 0 0032-32V64a32 32 0 00-32-32zm16 160a16 16 0 01-16 16H64a16 16 0 01-16-16V64a16 16 0 0116-16h128a16 16 0 0116 16zm-68-64a12 12 0 11-12-12 12 12 0 0112 12z"/></svg>;
export default DiceOneDuotone;
