// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DivideBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 128a12 12 0 01-12 12H40a12 12 0 010-24h176a12 12 0 0112 12zM128 84a20 20 0 10-20-20 20 20 0 0020 20zm0 88a20 20 0 1020 20 20 20 0 00-20-20z"/></svg>;
export default DivideBold;
