// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Door = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 216h-24V40a16 16 0 00-16-16H64a16 16 0 00-16 16v176H24a8 8 0 000 16h208a8 8 0 000-16zM64 40h128v176H64zm104 92a12 12 0 11-12-12 12 12 0 0112 12z"/></svg>;
export default Door;
