// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DotsThreeCircleVerticalDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 128a96 96 0 11-96-96 96 96 0 0196 96z" opacity=".2"/><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm12-88a12 12 0 11-12-12 12 12 0 0112 12zm0-44a12 12 0 11-12-12 12 12 0 0112 12zm0 88a12 12 0 11-12-12 12 12 0 0112 12z"/></svg>;
export default DotsThreeCircleVerticalDuotone;
