// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DotsThreeOutlineLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 98a30 30 0 1030 30 30 30 0 00-30-30zm0 48a18 18 0 1118-18 18 18 0 01-18 18zM48 98a30 30 0 1030 30 30 30 0 00-30-30zm0 48a18 18 0 1118-18 18 18 0 01-18 18zm160-48a30 30 0 1030 30 30 30 0 00-30-30zm0 48a18 18 0 1118-18 18 18 0 01-18 18z"/></svg>;
export default DotsThreeOutlineLight;
