// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DotsSixVerticalFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 16H64a16 16 0 00-16 16v192a16 16 0 0016 16h128a16 16 0 0016-16V32a16 16 0 00-16-16zm-92 184a12 12 0 1112-12 12 12 0 01-12 12zm0-60a12 12 0 1112-12 12 12 0 01-12 12zm0-60a12 12 0 1112-12 12 12 0 01-12 12zm56 120a12 12 0 1112-12 12 12 0 01-12 12zm0-60a12 12 0 1112-12 12 12 0 01-12 12zm0-60a12 12 0 1112-12 12 12 0 01-12 12z"/></svg>;
export default DotsSixVerticalFill;
