// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DownloadSimpleBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 144v64a12 12 0 01-12 12H40a12 12 0 01-12-12v-64a12 12 0 0124 0v52h152v-52a12 12 0 0124 0zm-108.49 8.49a12 12 0 0017 0l40-40a12 12 0 00-17-17L140 115V32a12 12 0 00-24 0v83L96.49 95.51a12 12 0 00-17 17z"/></svg>;
export default DownloadSimpleBold;
