// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EngineBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236 100h-11l-34.17-34.14A19.86 19.86 0 00176.69 60H144V44h20a12 12 0 000-24h-64a12 12 0 000 24h20v16H64a20 20 0 00-20 20v48H28v-20a12 12 0 00-24 0v64a12 12 0 0024 0v-20h16v16.69a19.86 19.86 0 005.86 14.14l39.31 39.31a19.86 19.86 0 0014.14 5.86h73.38a19.86 19.86 0 0014.14-5.86L225 188h11a20 20 0 0020-20v-48a20 20 0 00-20-20zm-4 64h-12a12 12 0 00-8.49 3.51L175 204h-70l-37-37V84h107l36.48 36.49A12 12 0 00220 124h12z"/></svg>;
export default EngineBold;
