// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EqualsBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 160a12 12 0 01-12 12H40a12 12 0 010-24h176a12 12 0 0112 12zM40 108h176a12 12 0 000-24H40a12 12 0 000 24z"/></svg>;
export default EqualsBold;
