// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EscalatorDownThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M173.17 82.83a4 4 0 015.66-5.66L196 94.34V48a4 4 0 018 0v46.34l17.17-17.17a4 4 0 115.66 5.66l-24 24a4 4 0 01-5.66 0zM236 160v40a12 12 0 01-12 12h-56a4 4 0 01-2.94-1.29L70.25 108H32a12 12 0 01-12-12V56a12 12 0 0112-12h56a4 4 0 012.94 1.29L185.75 148H224a12 12 0 0112 12zm-8 0a4 4 0 00-4-4h-40a4 4 0 01-2.94-1.29L86.25 52H32a4 4 0 00-4 4v40a4 4 0 004 4h40a4 4 0 012.94 1.29L169.75 204H224a4 4 0 004-4z"/></svg>;
export default EscalatorDownThin;
