// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EscalatorDownFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M170.34 85.66a8 8 0 0111.32-11.32L192 84.69V48a8 8 0 0116 0v36.69l10.34-10.35a8 8 0 0111.32 11.32l-24 24a8 8 0 01-11.32 0zM224 144h-36.5L93.88 42.57A8 8 0 0088 40H32a16 16 0 00-16 16v40a16 16 0 0016 16h36.5l93.62 101.43A8 8 0 00168 216h56a16 16 0 0016-16v-40a16 16 0 00-16-16z"/></svg>;
export default EscalatorDownFill;
