// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ExcludeSquareFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M88 88v80H40a8 8 0 01-8-8V40a8 8 0 018-8h120a8 8 0 018 8v48zm128 0h-48v80H88v48a8 8 0 008 8h120a8 8 0 008-8V96a8 8 0 00-8-8z"/></svg>;
export default ExcludeSquareFill;
