// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FalloutShelterFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M231.94 124.55c-1.77-54.49-46-98.72-100.49-100.49A104.09 104.09 0 0024.06 131.45c1.77 54.49 46 98.72 100.49 100.49a104.09 104.09 0 00107.39-107.39zm-33.56 16.92l-23.45 32.83a8.52 8.52 0 01-13.86 0L128 128l-33.07 46.3a8.52 8.52 0 01-13.86 0l-23.45-32.83A8.52 8.52 0 0164.55 128H128L97.62 85.47A8.52 8.52 0 01104.55 72h46.9a8.52 8.52 0 016.93 13.47L128 128h63.45a8.52 8.52 0 016.93 13.47z"/></svg>;
export default FalloutShelterFill;
