// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FastForwardCircleBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M196 128a12 12 0 01-4.5 9.37l-40 32A12 12 0 01132 160v-19.83l-36.5 29.2A12 12 0 0176 160V96a12 12 0 0119.5-9.37l36.5 29.2V96a12 12 0 0119.5-9.37l40 32A12 12 0 01196 128zm40 0A108 108 0 11128 20a108.12 108.12 0 01108 108zm-24 0a84 84 0 10-84 84 84.09 84.09 0 0084-84z"/></svg>;
export default FastForwardCircleBold;
