// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileLockLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M120 178h-10v-6a26 26 0 00-52 0v6H48a6 6 0 00-6 6v40a6 6 0 006 6h72a6 6 0 006-6v-40a6 6 0 00-6-6zm-50-6a14 14 0 0128 0v6H70zm44 46H54v-28h60zm98.24-134.24l-56-56A6 6 0 00152 26H56a14 14 0 00-14 14v88a6 6 0 0012 0V40a2 2 0 012-2h90v50a6 6 0 006 6h50v122a2 2 0 01-2 2h-40a6 6 0 000 12h40a14 14 0 0014-14V88a6 6 0 00-1.76-4.24zM158 46.48L193.52 82H158z"/></svg>;
export default FileLockLight;
