// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileMdDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 88h-56V32z" opacity=".2"/><path d="M213.66 82.34l-56-56A8 8 0 00152 24H56a16 16 0 00-16 16v72a8 8 0 0016 0V40h88v48a8 8 0 008 8h48v128a8 8 0 0016 0V88a8 8 0 00-2.34-5.66zM160 51.31L188.69 80H160zM144 144h-16a8 8 0 00-8 8v56a8 8 0 008 8h16a36 36 0 000-72zm0 56h-8v-40h8a20 20 0 010 40zm-40-48v56a8 8 0 01-16 0v-30.62l-13.45 19.21a8 8 0 01-13.1 0L48 177.38V208a8 8 0 01-16 0v-56a8 8 0 0114.55-4.59L68 178.05l21.45-30.64A8 8 0 01104 152z"/></svg>;
export default FileMdDuotone;
