// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileCBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216.49 79.51l-56-56A12 12 0 00152 20H56a20 20 0 00-20 20v68a12 12 0 0024 0V44h76v48a12 12 0 0012 12h48v108h-72a12 12 0 000 24h76a20 20 0 0020-20V88a12 12 0 00-3.51-8.49zM160 57l23 23h-23zM48 180c0 8.67 5.5 16 12 16a10.27 10.27 0 007.33-3.43 12 12 0 1117.34 16.6A34 34 0 0160 220c-19.85 0-36-17.94-36-40s16.15-40 36-40a34 34 0 0124.67 10.83 12 12 0 11-17.34 16.6A10.27 10.27 0 0060 164c-6.5 0-12 7.33-12 16z"/></svg>;
export default FileCBold;
