// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilePy = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M213.66 82.34l-56-56A8 8 0 00152 24H56a16 16 0 00-16 16v72a8 8 0 0016 0V40h88v48a8 8 0 008 8h48v120h-32a8 8 0 000 16h32a16 16 0 0016-16V88a8 8 0 00-2.34-5.66zM160 51.31L188.69 80H160zM64 144H48a8 8 0 00-8 8v56a8 8 0 0016 0v-8h8a28 28 0 000-56zm0 40h-8v-24h8a12 12 0 010 24zm90.78-27.76l-18.78 30V208a8 8 0 01-16 0v-21.71l-18.78-30a8 8 0 1113.56-8.48l13.22 21.1 13.22-21.15a8 8 0 1113.56 8.48z"/></svg>;
export default FilePy;
