// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileHtmlFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M44 128h168a4 4 0 004-4V88a8 8 0 00-2.34-5.66l-56-56A8 8 0 00152 24H56a16 16 0 00-16 16v84a4 4 0 004 4zm108-84l44 44h-44zM68 160v48a8 8 0 01-16 0v-16H32v16a8 8 0 01-16 0v-48a8 8 0 0116 0v16h20v-16a8 8 0 0116 0zm56 0a8 8 0 01-8 8h-8v40a8 8 0 01-16 0v-40h-8a8 8 0 010-16h32a8 8 0 018 8zm72 0v48a8 8 0 01-16 0v-24l-9.6 12.8a8 8 0 01-12.8 0L148 184v24a8 8 0 01-16 0v-48a8 8 0 0114.4-4.8l17.6 23.47 17.6-23.47A8 8 0 01196 160zm56 48a8 8 0 01-8 8h-28a8 8 0 01-8-8v-48a8 8 0 0116 0v40h20a8 8 0 018 8z"/></svg>;
export default FileHtmlFill;
