// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FileImageFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M158.66 219.56A8 8 0 01152 232H24a8 8 0 01-6.73-12.33l36-56a8 8 0 0113.46 0l9.76 15.18 20.85-31.29a8 8 0 0113.32 0zM216 88v128a16 16 0 01-16 16h-8a8 8 0 010-16h8V96h-48a8 8 0 01-8-8V40H56v88a8 8 0 01-16 0V40a16 16 0 0116-16h96a8 8 0 015.66 2.34l56 56A8 8 0 01216 88zm-56-8h28.69L160 51.31z"/></svg>;
export default FileImageFill;
