// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilePyBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216.49 79.52l-56-56A12 12 0 00152 20H56a20 20 0 00-20 20v68a12 12 0 0024 0V44h76v48a12 12 0 0012 12h48v108h-24a12 12 0 000 24h28a20 20 0 0020-20V88a12 12 0 00-3.51-8.48zM160 57l23 23h-23zm-96 83H48a12 12 0 00-12 12v56a12 12 0 0024 0v-4h4a32 32 0 000-64zm0 40h-4v-16h4a8 8 0 010 16zm80 7.44V208a12 12 0 01-24 0v-20.56l-18.18-29.08a12 12 0 0120.36-12.72l9.82 15.72 9.82-15.72a12 12 0 0120.36 12.72z"/></svg>;
export default FilePyBold;
