// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilmScriptLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 26H56a14 14 0 00-14 14v176a14 14 0 0014 14h144a14 14 0 0014-14V40a14 14 0 00-14-14zm2 190a2 2 0 01-2 2H56a2 2 0 01-2-2V40a2 2 0 012-2h144a2 2 0 012 2zM94 80a10 10 0 11-10-10 10 10 0 0110 10zm0 96a10 10 0 11-10-10 10 10 0 0110 10zm0-48a10 10 0 11-10-10 10 10 0 0110 10z"/></svg>;
export default FilmScriptLight;
