// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FlashlightBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M184 12H72a20 20 0 00-20 20v45.33a20.12 20.12 0 004 12L76 116v108a20 20 0 0020 20h64a20 20 0 0020-20V116l20-26.67a20.12 20.12 0 004-12V32a20 20 0 00-20-20zm-4 24v16H76V36zm-20 66.67a20.12 20.12 0 00-4 12V220h-56V114.67a20.12 20.12 0 00-4-12L76 76h104zM140 120v32a12 12 0 01-24 0v-32a12 12 0 0124 0z"/></svg>;
export default FlashlightBold;
