// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FloppyDiskBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M222.14 69.17l-35.31-35.31A19.86 19.86 0 00172.69 28H48a20 20 0 00-20 20v160a20 20 0 0020 20h160a20 20 0 0020-20V83.31a19.86 19.86 0 00-5.86-14.14zM164 204H92v-44h72zm40 0h-16v-48a20 20 0 00-20-20H88a20 20 0 00-20 20v48H52V52h119l33 33zM164 84a12 12 0 01-12 12H96a12 12 0 010-24h56a12 12 0 0112 12z"/></svg>;
export default FloppyDiskBold;
