// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FlowArrowBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248.49 71.51l-32-32a12 12 0 00-17 17L211 68h-3c-52 0-64.8 30.71-75.08 55.38-8.82 21.17-15.45 37.05-42.75 40.09a44 44 0 10.28 24.08c43.34-3.87 55.07-32 64.63-54.93C164.9 109 172 92 208 92h3l-11.52 11.51a12 12 0 0017 17l32-32a12 12 0 00.01-17zM48 196a20 20 0 1120-20 20 20 0 01-20 20z"/></svg>;
export default FlowArrowBold;
