// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FootballHelmetFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 160h-50.2l-7.09-24H216a8 8 0 008-8v-4A100 100 0 00122.58 24C68.24 24.77 24 69.61 24 124a100 100 0 0043.62 82.6 8 8 0 004.52 1.4H120a16 16 0 0015.62-19.47 5.44 5.44 0 00-.15-.54l-3.56-12h21.93l10.79 36.53A16.1 16.1 0 00180 224h36a16 16 0 0016-16v-32a16 16 0 00-16-16zM84 176a12 12 0 1112-12 12 12 0 01-12 12zm43.16-16L120 136h22l7.09 24zM216 208h-36l-9.46-32H216z"/></svg>;
export default FootballHelmetFill;
