// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FrameCornersBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M140 88a12 12 0 0112-12h32a12 12 0 0112 12v32a12 12 0 01-24 0v-20h-20a12 12 0 01-12-12zm-68 92h32a12 12 0 000-24H84v-20a12 12 0 00-24 0v32a12 12 0 0012 12zM236 56v144a20 20 0 01-20 20H40a20 20 0 01-20-20V56a20 20 0 0120-20h176a20 20 0 0120 20zm-24 4H44v136h168z"/></svg>;
export default FrameCornersBold;
