// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Function = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 40a8 8 0 01-8 8h-29.29a24 24 0 00-23.62 19.71l-9.5 52.29H184a8 8 0 010 16h-49.32l-10 55.16A40 40 0 0185.29 224H56a8 8 0 010-16h29.29a24 24 0 0023.62-19.71l9.5-52.29H72a8 8 0 010-16h49.32l10-55.16A40 40 0 01170.71 32H200a8 8 0 018 8z"/></svg>;
export default Function;
