// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FunnelDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M221.9 61.38L152 136v58.65a8 8 0 01-3.56 6.66l-32 21.33A8 8 0 01104 216v-80L34.1 61.38A8 8 0 0140 48h176a8 8 0 015.9 13.38z" opacity=".2"/><path d="M230.6 49.53A15.81 15.81 0 00216 40H40a16 16 0 00-11.81 26.76l.08.09L96 139.17V216a16 16 0 0024.87 13.32l32-21.34a16 16 0 007.13-13.32v-55.49l67.74-72.32.08-.09a15.8 15.8 0 002.78-17.23zM40 56zm106.18 74.58A8 8 0 00144 136v58.66L112 216v-80a8 8 0 00-2.16-5.47L40 56h176z"/></svg>;
export default FunnelDuotone;
