// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FunnelSimpleX = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 144H64a8 8 0 010-16h128a8 8 0 010 16zm40-64H24a8 8 0 000 16h208a8 8 0 000-16zm-104 96h-24a8 8 0 000 16h24a8 8 0 000-16zm93.66-5.66a8 8 0 00-11.32 0L192 188.69l-18.34-18.35a8 8 0 00-11.32 11.32L180.69 200l-18.35 18.34a8 8 0 0011.32 11.32L192 211.31l18.34 18.35a8 8 0 0011.32-11.32L203.31 200l18.35-18.34a8 8 0 000-11.32z"/></svg>;
export default FunnelSimpleX;
