// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FunnelSimpleFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 40H40a16 16 0 00-16 16v144a16 16 0 0016 16h176a16 16 0 0016-16V56a16 16 0 00-16-16zm-72 136h-32a8 8 0 010-16h32a8 8 0 010 16zm32-40H80a8 8 0 010-16h96a8 8 0 010 16zm32-40H48a8 8 0 010-16h160a8 8 0 010 16z"/></svg>;
export default FunnelSimpleFill;
