// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GhostBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M116 116a16 16 0 11-16-16 16 16 0 0116 16zm40-16a16 16 0 1016 16 16 16 0 00-16-16zm72 20v96a12 12 0 01-19.6 9.29l-21.73-17.79-21.74 17.79a12 12 0 01-15.2 0L128 207.5l-21.73 17.79a12 12 0 01-15.2 0L69.33 207.5 47.6 225.29A12 12 0 0128 216v-96a100 100 0 01200 0zm-24 0a76 76 0 00-152 0v70.68l9.73-8a12 12 0 0115.2 0l21.74 17.82 21.73-17.79a12 12 0 0115.2 0l21.73 17.79 21.74-17.79a12 12 0 0115.2 0l9.73 8z"/></svg>;
export default GhostBold;
