// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GhostLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M110 116a10 10 0 11-10-10 10 10 0 0110 10zm46-10a10 10 0 1010 10 10 10 0 00-10-10zm66 14v96a6 6 0 01-9.8 4.64l-25.53-20.89-25.54 20.89a6 6 0 01-7.6 0L128 199.75l-25.53 20.89a6 6 0 01-7.6 0l-25.54-20.89-25.53 20.89A6 6 0 0134 216v-96a94 94 0 01188 0zm-12 0a82 82 0 00-164 0v83.34l19.53-16a6 6 0 017.6 0l25.54 20.89 25.53-20.89a6 6 0 017.6 0l25.53 20.89 25.54-20.89a6 6 0 017.6 0l19.53 16z"/></svg>;
export default GhostLight;
