// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GifThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M140 72v112a4 4 0 01-8 0V72a4 4 0 018 0zm92-4h-56a4 4 0 00-4 4v112a4 4 0 008 0v-52h44a4 4 0 000-8h-44V76h52a4 4 0 000-8zM96 124H72a4 4 0 000 8h20v20a28 28 0 01-56 0v-48a28 28 0 0128-28c13 0 25 9 28.13 21a4 4 0 107.74-2C95.85 79.36 80.76 68 64 68a36 36 0 00-36 36v48a36 36 0 0072 0v-24a4 4 0 00-4-4z"/></svg>;
export default GifThin;
