// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GitBranchFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 64a32 32 0 10-40 31v17a8 8 0 01-8 8H96a23.84 23.84 0 00-8 1.38V95a32 32 0 10-16 0v66a32 32 0 1016 0v-17a8 8 0 018-8h88a24 24 0 0024-24V95a32.06 32.06 0 0024-31zM64 64a16 16 0 1116 16 16 16 0 01-16-16zm32 128a16 16 0 11-16-16 16 16 0 0116 16z"/></svg>;
export default GitBranchFill;
