// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GitMergeBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 108a36.05 36.05 0 00-33.38 22.54l-39-5.57a4 4 0 01-2.47-1.35l-32.6-38.09A36 36 0 1068 89.94v76.12a36 36 0 1024 0v-53.62l23 26.8a28 28 0 0017.3 9.49l41.34 5.91A36 36 0 10208 108zM80 44a12 12 0 11-12 12 12 12 0 0112-12zm0 168a12 12 0 1112-12 12 12 0 01-12 12zm128-56a12 12 0 1112-12 12 12 0 01-12 12z"/></svg>;
export default GitMergeBold;
