// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GitlabLogoSimpleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M226.27 118.11L206.38 42a7.94 7.94 0 00-15.16-.75L172.57 92H83.43L64.78 41.24a7.94 7.94 0 00-15.16.76l-19.89 76.11a53.16 53.16 0 0020.44 56.68l73.27 51.76a7.9 7.9 0 009.12 0l73.27-51.76a53.16 53.16 0 0020.44-56.68zm-25.05 50.14L128 220l-73.22-51.75a45.11 45.11 0 01-17.31-48.11l19.84-76 19.58 53.24a4 4 0 003.75 2.62h94.72a4 4 0 003.75-2.62l19.57-53.22 19.85 76a45.11 45.11 0 01-17.31 48.09z"/></svg>;
export default GitlabLogoSimpleThin;
