// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GlobeStandFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M56 104a80 80 0 1180 80 80.09 80.09 0 01-80-80zm146.46 69.28A96 96 0 0166.72 37.54a8 8 0 10-11.54-11.08A112 112 0 00128 215.71V232h-24a8 8 0 000 16h64a8 8 0 000-16h-24v-16.28a111.21 111.21 0 0069.54-30.9 8 8 0 10-11.08-11.54z"/></svg>;
export default GlobeStandFill;
