// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GoogleChromeLogoBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 20a108 108 0 10108 108A108.12 108.12 0 00128 20zm0 24a83.89 83.89 0 0165.9 32H128a52.05 52.05 0 00-46.15 28.07l-17.67-30.6A83.82 83.82 0 01128 44zm28 84a28 28 0 11-28-28 28 28 0 0128 28zm-112 0a83.41 83.41 0 016-31.11L83 154c.06.11.14.2.2.3A52 52 0 00128 180q1.19 0 2.34-.06l-17.68 30.63A84.12 84.12 0 0144 128zm96.05 83.12L173 154c.09-.15.16-.3.24-.46a51.81 51.81 0 00-1.46-53.54h35.4a83.95 83.95 0 01-67.13 111.12z"/></svg>;
export default GoogleChromeLogoBold;
