// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GoogleLogo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 128a96 96 0 11-21.95-61.09 8 8 0 11-12.33 10.18A80 80 0 10207.6 136H128a8 8 0 010-16h88a8 8 0 018 8z"/></svg>;
export default GoogleLogo;
