// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GpsSlashLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M246 128a6 6 0 01-6 6h-26.21a85.2 85.2 0 01-7.3 29.2 6 6 0 01-5.48 3.55 5.91 5.91 0 01-2.45-.53 6 6 0 01-3-7.93 74.05 74.05 0 00-91.28-100.4 6 6 0 01-3.84-11.37 85.64 85.64 0 0121.56-4.3V16a6 6 0 0112 0v26.23A86.12 86.12 0 01213.77 122H240a6 6 0 016 6zm-33.56 84a6 6 0 01-8.88 8.08l-22.3-24.54A85.73 85.73 0 01134 213.77V240a6 6 0 01-12 0v-26.23A86.12 86.12 0 0142.23 134H16a6 6 0 010-12h26.22a86.23 86.23 0 0123.64-53.44L43.56 44a6 6 0 018.88-8zm-39.27-25.4L74 77.48a74 74 0 0099.17 109.12z"/></svg>;
export default GpsSlashLight;
