// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GpsSlashThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M244 128a4 4 0 01-4 4h-28.1a83.08 83.08 0 01-7.24 30.38 4 4 0 01-3.65 2.37 3.94 3.94 0 01-1.63-.36 4 4 0 01-2-5.28A76.06 76.06 0 00103.62 56a4 4 0 11-2.56-7.57A83.56 83.56 0 01124 44.1V16a4 4 0 018 0v28.1a84.11 84.11 0 0179.9 79.9H240a4 4 0 014 4zm-33 85.31a4 4 0 11-5.92 5.38l-23.56-25.91A83.81 83.81 0 01132 211.9V240a4 4 0 01-8 0v-28.1A84.11 84.11 0 0144.1 132H16a4 4 0 010-8h28.1a84.24 84.24 0 0124.5-55.39L45 42.69a4 4 0 016-5.38L184.77 184.5zm-34.87-26.47L74 74.53a76 76 0 00102.1 112.31z"/></svg>;
export default GpsSlashThin;
