// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GreaterThanOrEqualBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M51.85 148.74L173.29 104 51.85 59.26a12 12 0 018.3-22.52l152 56a12 12 0 010 22.52l-152 56a12 12 0 11-8.3-22.52zM208 188H56a12 12 0 000 24h152a12 12 0 000-24z"/></svg>;
export default GreaterThanOrEqualBold;
