// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GridNineBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 44H40a20 20 0 00-20 20v128a20 20 0 0020 20h176a20 20 0 0020-20V64a20 20 0 00-20-20zm-108 96v-24h40v24zm40 24v24h-40v-24zM44 116h40v24H44zm64-24V68h40v24zm64 24h40v24h-40zm40-24h-40V68h40zM84 68v24H44V68zm-40 96h40v24H44zm128 24v-24h40v24z"/></svg>;
export default GridNineBold;
