// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GridNineThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 52H40a12 12 0 00-12 12v128a12 12 0 0012 12h176a12 12 0 0012-12V64a12 12 0 00-12-12zm-116 96v-40h56v40zm56 8v40h-56v-40zM36 108h56v40H36zm64-8V60h56v40zm64 8h56v40h-56zm56-44v36h-56V60h52a4 4 0 014 4zM40 60h52v40H36V64a4 4 0 014-4zm-4 132v-36h56v40H40a4 4 0 01-4-4zm180 4h-52v-40h56v36a4 4 0 01-4 4z"/></svg>;
export default GridNineThin;
