// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GridFour = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 40H56a16 16 0 00-16 16v144a16 16 0 0016 16h144a16 16 0 0016-16V56a16 16 0 00-16-16zm0 80h-64V56h64zm-80-64v64H56V56zm-64 80h64v64H56zm144 64h-64v-64h64v64z"/></svg>;
export default GridFour;
