// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HairDryerFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M177.42 206.62L209 137.07A64 64 0 00168 24a8.4 8.4 0 00-1.32.11L29.37 47A16 16 0 0016 62.78v50.44A16 16 0 0029.37 129L128 145.44V200a16 16 0 0016 16 40 40 0 0040 40h16a8 8 0 000-16h-16a24 24 0 01-24-24h2.85a16 16 0 0014.57-9.38zM192 88a24 24 0 11-24-24 24 24 0 0124 24zm-25.32 63.89a8.4 8.4 0 001.32.11 63.9 63.9 0 0017.82-2.54l-23 50.54H144v-51.89z"/></svg>;
export default HairDryerFill;
