// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Hammer = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M251.34 112l-67.46-67.92a96.1 96.1 0 00-135.77 0l-.09.09L34.25 58.4a8 8 0 0011.49 11.13l13.73-14.18a79.92 79.92 0 0118.71-13.9L124.68 88l-96 96a16 16 0 000 22.63l20.69 20.69a16 16 0 0022.63 0l96-96 14.34 14.34L200 163.3a16 16 0 0022.63 0l28.69-28.69a16 16 0 00.02-22.61zM60.68 216L40 195.31l68-68L128.68 148zm101.66-101.68L140 136.67 119.31 116l22.35-22.35a8 8 0 000-11.32L94.32 35a80 80 0 0178.23 20.41l44.22 44.51L188 128.66l-14.34-14.34a8 8 0 00-11.32 0zm49 37.66l-12-12L228 111.25l12 12z"/></svg>;
export default Hammer;
