// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HandLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M188 50a25.8 25.8 0 00-14 4.11V44a26 26 0 00-51.41-5.51A26 26 0 0082 60v71l-7.53-12.1a26 26 0 00-45.11 25.87C60.76 211 78.51 238 128 238a86.1 86.1 0 0086-86V76a26 26 0 00-26-26zm14 102a74.09 74.09 0 01-74 74c-21 0-34.51-5.05-46.75-17.45C67.81 195 55.54 172 40.1 139.43l-.23-.43a14 14 0 0124.25-14l.1.17 18.68 30A6 6 0 0094 152V60a14 14 0 0128 0v60a6 6 0 0012 0V44a14 14 0 0128 0v76a6 6 0 0012 0V76a14 14 0 0128 0z"/></svg>;
export default HandLight;
