// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HandDepositThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M124 25.66V128a4 4 0 01-8 0V25.66L90.83 50.83a4 4 0 01-5.66-5.66l32-32a4 4 0 015.66 0l32 32a4 4 0 01-5.66 5.66zm64 100.12V96a12 12 0 00-12-12h-16a4 4 0 000 8h16a4 4 0 014 4v92.9l-3.27-5a24 24 0 00-41.51 24.1 1.22 1.22 0 00.12.19l22.26 34a4 4 0 106.69-4.38l-22.2-33.9A16 16 0 01169.86 188l.12.19 10.67 16.31a4 4 0 007.35-2.19v-66.84a78.83 78.83 0 0132 63.18V240a4 4 0 008 0v-41.35a86.84 86.84 0 00-40-72.87zM80 84H64a12 12 0 00-12 12v104a4 4 0 008 0V96a4 4 0 014-4h16a4 4 0 000-8z"/></svg>;
export default HandDepositThin;
