// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HandFist = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 80h-16V64a32 32 0 00-56-21.13 32 32 0 00-55.79 17.55A32 32 0 0024 88v40a104 104 0 00208 0v-16a32 32 0 00-32-32zm-48-32a16 16 0 0116 16v16h-32V64a16 16 0 0116-16zM88 64a16 16 0 0132 0v40a16 16 0 01-32 0zM40 88a16 16 0 0132 0v16a16 16 0 01-32 0zm176 40a88 88 0 01-175.92 3.75A31.93 31.93 0 0080 125.13a31.93 31.93 0 0044.58 3.35 32.21 32.21 0 0011.8 11.44A47.88 47.88 0 00120 176a8 8 0 0016 0 32 32 0 0132-32 8 8 0 000-16h-16a16 16 0 01-16-16V96h64a16 16 0 0116 16z"/></svg>;
export default HandFist;
