// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HashStraightThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 156h-52v-56h52a4 4 0 000-8h-52V40a4 4 0 00-8 0v52h-56V40a4 4 0 00-8 0v52H40a4 4 0 000 8h52v56H40a4 4 0 000 8h52v52a4 4 0 008 0v-52h56v52a4 4 0 008 0v-52h52a4 4 0 000-8zm-116 0v-56h56v56z"/></svg>;
export default HashStraightThin;
