// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HeadlightsDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M136 64v128a8 8 0 01-8 8H88a72 72 0 01-72-72.55C16.3 87.75 49.2 56 88.9 56H128a8 8 0 018 8z" opacity=".2"/><path d="M160 80a8 8 0 018-8h72a8 8 0 010 16h-72a8 8 0 01-8-8zm80 88h-72a8 8 0 000 16h72a8 8 0 000-16zm0-64h-72a8 8 0 000 16h72a8 8 0 000-16zm0 32h-72a8 8 0 000 16h72a8 8 0 000-16zm-96-72v128a16 16 0 01-16 16H88a80 80 0 01-80-80.61C8.33 83.62 44.62 48 88.9 48H128a16 16 0 0116 16zm-16 0H88.9C53.38 64 24.26 92.49 24 127.51A64 64 0 0088 192h40z"/></svg>;
export default HeadlightsDuotone;
