// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HighHeel = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M231 156.19l-51-11.49L69.66 34.34a8 8 0 00-11.56.26C36.11 58.64 24 89 24 120v72a16 16 0 0016 16h32a16 16 0 0016-16v-48.94c2.49 1.45 4.94 3 7.34 4.64a112.45 112.45 0 0140.55 50.39 15.9 15.9 0 0014.83 9.91H240a16 16 0 0016-16v-4.73a31.72 31.72 0 00-25-31.08zM72 192H40v-63.71a110.88 110.88 0 0132 7.12zm168 0h-89.32a128.36 128.36 0 00-46.27-57.46 126.9 126.9 0 00-64.12-22.26 110.67 110.67 0 0124.17-60.5l105.88 105.88a8 8 0 003.9 2.14l53.24 12A15.81 15.81 0 01240 187.31z"/></svg>;
export default HighHeel;
