// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HorseFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M202.05 55A103.24 103.24 0 00128 24h-8a8 8 0 00-8 8v27.53L11.81 121.19a8 8 0 00-2.59 11.05l13.78 22 .3.43a31.84 31.84 0 0031.34 12.83c13.93-2.36 38.62-6.54 61.4 3.29l-26.6 36.57A84.71 84.71 0 0169.34 194a8 8 0 10-10.67 12 103.32 103.32 0 0069.26 26h2.17a104 104 0 0072-177zM124 112a12 12 0 1112-12 12 12 0 01-12 12z"/></svg>;
export default HorseFill;
