// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HospitalFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248 208h-8v-80a16 16 0 00-16-16h-56V48a16 16 0 00-16-16H56a16 16 0 00-16 16v160h-8a8 8 0 000 16h216a8 8 0 000-16zm-120 0H80v-48h48zm0-104h-16v16a8 8 0 01-16 0v-16H80a8 8 0 010-16h16V72a8 8 0 0116 0v16h16a8 8 0 010 16zm96 104h-56v-80h56z"/></svg>;
export default HospitalFill;
