// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const HourglassMediumDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M180.92 88L128 128 74.67 88z" opacity=".2"/><path d="M200 75.64V40a16 16 0 00-16-16H72a16 16 0 00-16 16v36a16.07 16.07 0 006.4 12.8l52.27 39.2-52.27 39.2A16.07 16.07 0 0056 180v36a16 16 0 0016 16h112a16 16 0 0016-16v-35.64a16.09 16.09 0 00-6.35-12.77L141.27 128l52.38-39.59A16.09 16.09 0 00200 75.64zM72 40h112v35.64L178.23 80H77.33L72 76zm56 78L98.67 96h58.4zm56 98H72v-36l48-36v24a8 8 0 0016 0v-23.92l48 36.28z"/></svg>;
export default HourglassMediumDuotone;
