// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Images = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 40H72a16 16 0 00-16 16v16H40a16 16 0 00-16 16v112a16 16 0 0016 16h144a16 16 0 0016-16v-16h16a16 16 0 0016-16V56a16 16 0 00-16-16zM72 56h144v62.75l-10.07-10.06a16 16 0 00-22.63 0l-20 20-44-44a16 16 0 00-22.62 0L72 109.37zm112 144H40V88h16v80a16 16 0 0016 16h112zm32-32H72v-36l36-36 49.66 49.66a8 8 0 0011.31 0L194.63 120 216 141.38V168zm-56-84a12 12 0 1112 12 12 12 0 01-12-12z"/></svg>;
export default Images;
