// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LadderThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M211.76 214.63L160.26 73l10.54-29H184a4 4 0 000-8H88a4 4 0 000 8h10.29l-62 170.63a4 4 0 002.39 5.13A4.16 4.16 0 0040 220a4 4 0 003.76-2.63L54.44 188h55.49l-9.69 26.63a4 4 0 002.39 5.13 4.12 4.12 0 001.37.24 4 4 0 003.76-2.63L127.17 164h57.66l19.41 53.37A4 4 0 00208 220a4.16 4.16 0 001.37-.24 4 4 0 002.39-5.13zM130.29 132H74.8l14.55-40h55.48zm32-88l-14.55 40H92.26l14.54-40zM57.35 180l14.54-40h55.49l-14.55 40zm72.72-24L156 84.7l25.92 71.3z"/></svg>;
export default LadderThin;
