// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LegoSmileyBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M84 112a16 16 0 1116 16 16 16 0 01-16-16zm72-16a16 16 0 1016 16 16 16 0 00-16-16zm-6.4 45.85a41 41 0 01-43.2 0 12 12 0 10-12.8 20.3 65 65 0 0068.8 0 12 12 0 10-12.8-20.3zM220 84v88a36.07 36.07 0 01-24 33.94V224a20 20 0 01-20 20H80a20 20 0 01-20-20v-18.06A36.07 36.07 0 0136 172V84a36 36 0 0136-36h12V32a20 20 0 0120-20h48a20 20 0 0120 20v16h12a36 36 0 0136 36zM108 48h40V36h-40zm64 172v-12H84v12zm24-136a12 12 0 00-12-12H72a12 12 0 00-12 12v88a12 12 0 0012 12h112a12 12 0 0012-12z"/></svg>;
export default LegoSmileyBold;
