// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterCircleV = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm39.43-117l-32 80a8 8 0 01-14.86 0l-32-80a8 8 0 0114.86-6L128 154.46 152.57 93a8 8 0 1114.86 6z"/></svg>;
export default LetterCircleV;
