// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LetterCirclePFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M156 116a20 20 0 01-20 20h-24V96h24a20 20 0 0120 20zm76 12A104 104 0 11128 24a104.11 104.11 0 01104 104zm-60-12a36 36 0 00-36-36h-32a8 8 0 00-8 8v80a8 8 0 0016 0v-16h24a36 36 0 0036-36z"/></svg>;
export default LetterCirclePFill;
