// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LinkSimpleHorizontal = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M80 120h96a8 8 0 010 16H80a8 8 0 010-16zm24 48H64a40 40 0 010-80h40a8 8 0 000-16H64a56 56 0 000 112h40a8 8 0 000-16zm88-96h-40a8 8 0 000 16h40a40 40 0 010 80h-40a8 8 0 000 16h40a56 56 0 000-112z"/></svg>;
export default LinkSimpleHorizontal;
