// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LinktreeLogo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M136 160v72a8 8 0 01-16 0v-72a8 8 0 0116 0zm72-64h-60.69l42.35-42.34a8 8 0 00-11.32-11.32L136 84.69V24a8 8 0 00-16 0v60.69L77.66 42.34a8 8 0 00-11.32 11.32L108.69 96H48a8 8 0 000 16h60.69l-42.35 42.34a8 8 0 0011.32 11.32L128 115.31l50.34 50.35a8 8 0 0011.32-11.32L147.31 112H208a8 8 0 000-16z"/></svg>;
export default LinktreeLogo;
