// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LinkSimpleBreakBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M218.45 122.43l-30.08 30.06a12 12 0 01-17-17l30.08-30.07a36 36 0 00-50.93-50.92l-30.04 30.09a12 12 0 01-17-17l30.07-30.06a60 60 0 0184.87 84.88zm-82.93 49l-30.07 30.08a36 36 0 01-50.92-50.93l30.06-30.07a12 12 0 00-17-17l-30.04 30.07a60 60 0 0084.88 84.87l30.06-30.07a12 12 0 00-17-17z"/></svg>;
export default LinkSimpleBreakBold;
