// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LinkedinLogoLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 26H40a14 14 0 00-14 14v176a14 14 0 0014 14h176a14 14 0 0014-14V40a14 14 0 00-14-14zm2 190a2 2 0 01-2 2H40a2 2 0 01-2-2V40a2 2 0 012-2h176a2 2 0 012 2zM94 112v64a6 6 0 01-12 0v-64a6 6 0 0112 0zm88 28v36a6 6 0 01-12 0v-36a22 22 0 00-44 0v36a6 6 0 01-12 0v-64a6 6 0 0112 0v2.11A34 34 0 01182 140zM98 84a10 10 0 11-10-10 10 10 0 0110 10z"/></svg>;
export default LinkedinLogoLight;
