// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ListDashesDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 64v128H96V64z" opacity=".2"/><path d="M88 64a8 8 0 018-8h120a8 8 0 010 16H96a8 8 0 01-8-8zm128 56H96a8 8 0 100 16h120a8 8 0 000-16zm0 64H96a8 8 0 100 16h120a8 8 0 000-16zM56 56H40a8 8 0 000 16h16a8 8 0 000-16zm0 64H40a8 8 0 100 16h16a8 8 0 000-16zm0 64H40a8 8 0 100 16h16a8 8 0 000-16z"/></svg>;
export default ListDashesDuotone;
