// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ListMagnifyingGlassLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M34 64a6 6 0 016-6h176a6 6 0 010 12H40a6 6 0 01-6-6zm6 70h72a6 6 0 000-12H40a6 6 0 000 12zm88 52H40a6 6 0 000 12h88a6 6 0 000-12zm108.24 10.24a6 6 0 01-8.48 0l-21.49-21.48a38.06 38.06 0 118.49-8.49l21.48 21.49a6 6 0 010 8.48zM184 170a26 26 0 10-26-26 26 26 0 0026 26z"/></svg>;
export default ListMagnifyingGlassLight;
