// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LockOpenThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 84H92V56a36 36 0 0136-36c17.24 0 32.75 12.38 36.08 28.8a4 4 0 107.84-1.6C167.78 26.81 149.31 12 128 12a44.05 44.05 0 00-44 44v28H48a12 12 0 00-12 12v112a12 12 0 0012 12h160a12 12 0 0012-12V96a12 12 0 00-12-12zm4 124a4 4 0 01-4 4H48a4 4 0 01-4-4V96a4 4 0 014-4h160a4 4 0 014 4zm-76-56a8 8 0 11-8-8 8 8 0 018 8z"/></svg>;
export default LockOpenThin;
