// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const LockKeyBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 76h-28V56a52 52 0 00-104 0v20H48a20 20 0 00-20 20v112a20 20 0 0020 20h160a20 20 0 0020-20V96a20 20 0 00-20-20zM100 56a28 28 0 0156 0v20h-56zm104 148H52V100h152zm-76-92a32 32 0 00-12 61.66V180a12 12 0 0024 0v-6.34A32 32 0 00128 112zm0 24a8 8 0 11-8 8 8 8 0 018-8z"/></svg>;
export default LockKeyBold;
