// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MapPinSimpleLine = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 208h-80v-72.58a56 56 0 10-16 0V208H40a8 8 0 000 16h176a8 8 0 000-16zM88 80a40 40 0 1140 40 40 40 0 01-40-40z"/></svg>;
export default MapPinSimpleLine;
