// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MapPinLineDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a80 80 0 00-80 80c0 72 80 128 80 128s80-56 80-128a80 80 0 00-80-80zm0 112a32 32 0 1132-32 32 32 0 01-32 32z" opacity=".2"/><path d="M200 224h-49.46A266.56 266.56 0 00174 200.25c27.45-31.57 42-64.85 42-96.25a88 88 0 00-176 0c0 31.4 14.51 64.68 42 96.25A266.56 266.56 0 00105.46 224H56a8 8 0 000 16h144a8 8 0 000-16zM56 104a72 72 0 01144 0c0 57.23-55.47 105-72 118-16.53-13-72-60.77-72-118zm112 0a40 40 0 10-40 40 40 40 0 0040-40zm-64 0a24 24 0 1124 24 24 24 0 01-24-24z"/></svg>;
export default MapPinLineDuotone;
