// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MapPinPlusFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 16a88.1 88.1 0 00-88 88c0 31.4 14.51 64.68 42 96.25a254.19 254.19 0 0041.45 38.3 8 8 0 009.18 0 254.19 254.19 0 0041.37-38.3c27.45-31.57 42-64.85 42-96.25a88.1 88.1 0 00-88-88zm32 96h-24v24a8 8 0 01-16 0v-24H96a8 8 0 010-16h24V72a8 8 0 0116 0v24h24a8 8 0 010 16z"/></svg>;
export default MapPinPlusFill;
