// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MarkerCircleLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200.12 55.87A102 102 0 1055.88 200.12 102 102 0 10200.12 55.87zM86 207.64V176a2 2 0 012-2h80a2 2 0 012 2v31.64a90.32 90.32 0 01-84 0zM104 142h48a2 2 0 012 2v18h-52v-18a2 2 0 012-2zm11.54-12L126 79.59a2 2 0 013.92 0L140.46 130zm76.1 61.64A92.76 92.76 0 01182 200v-24a14 14 0 00-14-14h-2v-18a14 14 0 00-13.27-14l-11-52.9a14 14 0 00-27.42 0l-11 52.9A14 14 0 0090 144v18h-2a14 14 0 00-14 14v24a92.76 92.76 0 01-9.64-8.37 90 90 0 11127.28 0z"/></svg>;
export default MarkerCircleLight;
