// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MarkerCircleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M198.71 57.29A100 100 0 1057.29 198.71 100 100 0 10198.71 57.29zM84 208.83V176a4 4 0 014-4h80a4 4 0 014 4v32.83a92.25 92.25 0 01-88 0zM108.15 140H152a4 4 0 014 4v20h-56v-20a4 4 0 014-4zm4.93-8l11-52.82a4 4 0 017.84 0l11 52.82zm80 61.05A92.41 92.41 0 01180 203.9V176a12 12 0 00-12-12h-4v-20a12 12 0 00-12-12h-.91l-11.34-54.45a12 12 0 00-23.5 0L104.91 132H104a12 12 0 00-12 12v20h-4a12 12 0 00-12 12v27.9a92.41 92.41 0 01-13-10.85 92 92 0 11130.1 0z"/></svg>;
export default MarkerCircleThin;
