// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MartiniBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M243.09 35.41A12 12 0 00232 28H24a12 12 0 00-8.48 20.49L116 149v55H88a12 12 0 000 24h80a12 12 0 000-24h-28v-55L240.48 48.49a12 12 0 002.61-13.08zM203 52l-12 12H65L53 52zm-75 75L89 88h78z"/></svg>;
export default MartiniBold;
