// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MedalBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M220 96a92 92 0 10-152 69.69V240a12 12 0 0017.37 10.73L128 229.42l42.64 21.31A12 12 0 00188 240v-74.31A91.86 91.86 0 00220 96zM60 96a68 68 0 1168 68 68.07 68.07 0 01-68-68zm104 124.59l-30.64-15.32a12 12 0 00-10.74 0L92 220.58v-39.92a92 92 0 0072 0zM128 148a52 52 0 10-52-52 52.06 52.06 0 0052 52zm0-80a28 28 0 11-28 28 28 28 0 0128-28z"/></svg>;
export default MedalBold;
