// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MedalMilitaryBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M207 36H49a21 21 0 00-21 21v49.21a21 21 0 0012.31 19.11l56 25.47a52 52 0 1063.32 0l56-25.47A21 21 0 00228 106.21V57a21 21 0 00-21-21zm-79 102.82l-28-12.73V60h56v66.09zM52 60h24v55.18l-24-10.91zm76 160a28 28 0 1128-28 28 28 0 01-28 28zm76-115.73l-24 10.91V60h24z"/></svg>;
export default MedalMilitaryBold;
