// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MegaphoneSimpleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M227.41 90.5l-176-54A12 12 0 0036 48v144a12 12 0 0012 12 12.41 12.41 0 003.45-.5L140 176.32V192a12 12 0 0012 12h32a12 12 0 0012-12v-32.86l31.39-9.63A12.06 12.06 0 00236 138v-36a12 12 0 00-8.59-11.5zM49.12 195.84A4 4 0 0144 192V48a4 4 0 011.6-3.2A4 4 0 0148 44a3.89 3.89 0 011.07.15L140 72.05V168zM188 192a4 4 0 01-4 4h-32a4 4 0 01-4-4v-18.13l40-12.27zm40-54a4 4 0 01-2.88 3.84h-.05L148 165.5v-91l77.12 23.66A4 4 0 01228 102z"/></svg>;
export default MegaphoneSimpleThin;
