// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MemberOfBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 140H61.08A68.1 68.1 0 00128 196h72a12 12 0 010 24h-72a92 92 0 010-184h72a12 12 0 010 24h-72a68.1 68.1 0 00-66.92 56H200a12 12 0 010 24z"/></svg>;
export default MemberOfBold;
