// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MemberOfThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 132H52.11A76.09 76.09 0 00128 204h72a4 4 0 010 8h-72a84 84 0 010-168h72a4 4 0 010 8h-72a76.09 76.09 0 00-75.89 72H200a4 4 0 010 8z"/></svg>;
export default MemberOfThin;
