// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MicrosoftPowerpointLogoBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M94 88H76a12 12 0 00-12 12v52a12 12 0 0024 0v-4h6a30 30 0 000-60zm0 36h-6v-12h6a6 6 0 010 12zm42-104a108.16 108.16 0 00-76.73 32H40a20 20 0 00-20 20v108a20 20 0 0020 20h15.5A108 108 0 10136 20zm0 24a84.12 84.12 0 0183.13 72H164V72a20 20 0 00-20-20h-43.73A83.88 83.88 0 01136 44zM44 76h96v100H44zm92 136a83.67 83.67 0 01-43.32-12H144a20 20 0 0020-20v-40h55.13A84.12 84.12 0 01136 212z"/></svg>;
export default MicrosoftPowerpointLogoBold;
