// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MicroscopeThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 212h-29.2a83.2 83.2 0 0025.2-60 84.1 84.1 0 00-80-83.9V32a12 12 0 00-12-12H80a12 12 0 00-12 12v104a12 12 0 0012 12h48a12 12 0 0012-12V76.11A76 76 0 01182.64 212H32a4 4 0 000 8h192a4 4 0 000-8zm-92-76a4 4 0 01-4 4H80a4 4 0 01-4-4V32a4 4 0 014-4h48a4 4 0 014 4zm-60 44a4 4 0 010-8h64a4 4 0 010 8z"/></svg>;
export default MicroscopeThin;
