// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MicrosoftOutlookLogo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M120 128a32 32 0 10-32 32 32 32 0 0032-32zm-48 0a16 16 0 1116 16 16 16 0 01-16-16zm152-24h-16V40a8 8 0 00-8-8h-96a8 8 0 00-8 8v24H40a16 16 0 00-16 16v96a16 16 0 0016 16h32v16a16 16 0 0016 16h128a16 16 0 0016-16v-96a8 8 0 00-8-8zm-58.34 60L216 127.65v72.7zM112 48h80v77.24l-40 28.89V80a16 16 0 00-16-16h-24zM40 80h96v96H40zm48 112h48a16 16 0 0016-16v-2.13L199.26 208H88z"/></svg>;
export default MicrosoftOutlookLogo;
