// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MoneyThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 164a36 36 0 10-36-36 36 36 0 0036 36zm0-64a28 28 0 11-28 28 28 28 0 0128-28zm112-40H16a4 4 0 00-4 4v128a4 4 0 004 4h224a4 4 0 004-4V64a4 4 0 00-4-4zM20 107.26A52.75 52.75 0 0059.26 68h137.48A52.75 52.75 0 00236 107.26v41.48A52.75 52.75 0 00196.74 188H59.26A52.75 52.75 0 0020 148.74zM236 99a44.8 44.8 0 01-31-31h31zM51 68a44.8 44.8 0 01-31 31V68zm-31 89a44.8 44.8 0 0131 31H20zm185 31a44.8 44.8 0 0131-31v31z"/></svg>;
export default MoneyThin;
