// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MonitorDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 64v112a16 16 0 01-16 16H48a16 16 0 01-16-16V64a16 16 0 0116-16h160a16 16 0 0116 16z" opacity=".2"/><path d="M208 40H48a24 24 0 00-24 24v112a24 24 0 0024 24h160a24 24 0 0024-24V64a24 24 0 00-24-24zm8 136a8 8 0 01-8 8H48a8 8 0 01-8-8V64a8 8 0 018-8h160a8 8 0 018 8zm-48 48a8 8 0 01-8 8H96a8 8 0 010-16h64a8 8 0 018 8z"/></svg>;
export default MonitorDuotone;
