// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Moped = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 128a39.3 39.3 0 00-6.27.5l-34.24-91.31A8 8 0 00168 32h-32a8 8 0 000 16h26.46l32.3 86.13a40.13 40.13 0 00-18 25.87h-40.22l-25-66.81A8 8 0 00104 88H24a8 8 0 000 16h8v13.39A56.12 56.12 0 000 168a8 8 0 008 8h8.8a40 40 0 0078.4 0h81.6a40 40 0 1039.2-48zm-173.33 2.27a8 8 0 005.33-7.54V104h50.46l21 56H16.81a40.07 40.07 0 0125.86-29.73zM56 192a24 24 0 01-22.62-16h45.24A24 24 0 0156 192zm160 0a24 24 0 01-15.43-42.36l7.94 21.17a8 8 0 0015-5.62L215.55 144h.45a24 24 0 010 48z"/></svg>;
export default Moped;
