// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MopedThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 132a35.7 35.7 0 00-8.82 1.1l-35.43-94.5A4 4 0 00168 36h-32a4 4 0 000 8h29.23l34.47 91.92A36.06 36.06 0 00180.23 164h-46.46l-26-69.4A4 4 0 00104 92H24a4 4 0 000 8h12v20a52.1 52.1 0 00-32 48 4 4 0 004 4h12.23a36 36 0 0071.54 0h88.46A36 36 0 10216 132zm-174.67-5.5a4 4 0 002.67-3.77V100h57.23l24 64h-113a44.1 44.1 0 0129.1-37.5zM56 196a28 28 0 01-27.71-24h55.42A28 28 0 0156 196zm160 0a28 28 0 01-13.47-52.54l9.72 25.94a4 4 0 107.5-2.8L210 140.65a28 28 0 116 55.35z"/></svg>;
export default MopedThin;
