// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MusicNoteSimpleFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M210.3 56.34l-80-24A8 8 0 00120 40v108.26A48 48 0 10136 184V50.75l69.7 20.91a8 8 0 104.6-15.32z"/></svg>;
export default MusicNoteSimpleFill;
