// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const MusicNotesMinusThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 48a4 4 0 01-4 4h-48a4 4 0 010-8h48a4 4 0 014 4zm-16 40v76a32.06 32.06 0 11-8-21.13V88a4 4 0 018 0zm-8 76a24 24 0 10-24 24 24 24 0 0024-24zM84 107.12V196a32.06 32.06 0 11-8-21.13V56a4 4 0 013-3.88l56-14a4 4 0 012 7.76L84 59.12v39.76l75-18.76a4 4 0 012 7.76zM76 196a24 24 0 10-24 24 24 24 0 0024-24z"/></svg>;
export default MusicNotesMinusThin;
