// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NeedleLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M188.24 67.76a6 6 0 010 8.48l-16 16a6 6 0 01-8.48-8.48l16-16a6 6 0 018.48 0zM222 72a37.74 37.74 0 01-11.13 26.87l-24 24a6 6 0 01-3.23 1.67c-52.14 9-138.53 94.84-139.4 95.7a5.81 5.81 0 01-1.82 1.25A6.12 6.12 0 0140 222a6 6 0 01-4.24-10.24c1.4-1.41 86.78-87.44 95.69-139.39a6 6 0 011.67-3.23l24-24A38 38 0 01222 72zm-12 0a26 26 0 00-44.38-18.38L142.93 76.3c-4.14 20.79-18.62 47.61-43.13 79.9 32.29-24.51 59.11-39 79.9-43.13l22.68-22.69A25.79 25.79 0 00210 72z"/></svg>;
export default NeedleLight;
