// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NewspaperClippingFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 40H40a16 16 0 00-16 16v160a8 8 0 0011.58 7.15L64 208.94l28.42 14.21a8 8 0 007.16 0L128 208.94l28.42 14.21a8 8 0 007.16 0L192 208.94l28.42 14.21A8 8 0 00232 216V56a16 16 0 00-16-16zM116 160a4 4 0 01-4 4H64a4 4 0 01-4-4V96a4 4 0 014-4h48a4 4 0 014 4zm76-8h-48a8 8 0 010-16h48a8 8 0 010 16zm0-32h-48a8 8 0 010-16h48a8 8 0 010 16z"/></svg>;
export default NewspaperClippingFill;
