// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NotMemberOfLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M212 35.56a6 6 0 00-8.48.4l-5.49 6H128A85.93 85.93 0 0065.9 187.4L43.56 212a6 6 0 008.88 8l22.33-24.57A85.52 85.52 0 00128 214h72a6 6 0 000-12h-72a73.65 73.65 0 01-45.14-15.42L130.65 134H200a6 6 0 000-12h-58.44l70.88-78a6 6 0 00-.44-8.44zM74 178.5A73.74 73.74 0 0154.26 134h60.18zM54.26 122A74.09 74.09 0 01128 54h59.16l-61.81 68z"/></svg>;
export default NotMemberOfLight;
