// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NotMemberOfDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 48v160h-72a80 80 0 01-80-80 80 80 0 0180-80z" opacity=".2"/><path d="M213.38 34.08a8 8 0 00-11.3.54L197.19 40H128a88 88 0 00-64.84 147.43l-21.08 23.19a8 8 0 1011.84 10.76L75 198.2a87.5 87.5 0 0053 17.8h72a8 8 0 000-16h-72a71.63 71.63 0 01-42.18-13.7l45.72-50.3H200a8 8 0 000-16h-53.92l67.84-74.62a8 8 0 00-.54-11.3zM74 175.53A71.69 71.69 0 0156.46 136h53.46zM56.46 120A72.08 72.08 0 01128 56h54.64l-58.18 64z"/></svg>;
export default NotMemberOfDuotone;
