// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberFour = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M184 160h-16V48a8 8 0 00-14.25-5l-96 120A8 8 0 0064 176h88v32a8 8 0 0016 0v-32h16a8 8 0 000-16zm-32 0H80.64L152 70.81z"/></svg>;
export default NumberFour;
