// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberFiveLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M174 160a54 54 0 01-90 40.25 6 6 0 118-8.94 42 42 0 10.8-63.31 6 6 0 01-9.8-5.75l15.12-75.43A6 6 0 01104 42h64a6 6 0 010 12h-59.08l-11.38 56.89A54 54 0 01174 160z"/></svg>;
export default NumberFiveLight;
