// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberSquareTwoFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 32H48a16 16 0 00-16 16v160a16 16 0 0016 16h160a16 16 0 0016-16V48a16 16 0 00-16-16zm-56 136a8 8 0 010 16h-48a8 8 0 01-6.4-12.8l43.17-57.56a16 16 0 10-27.86-15 8 8 0 01-15.09-5.34 32 32 0 1155.74 29.93L120 168z"/></svg>;
export default NumberSquareTwoFill;
