// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberCircleFiveBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 20a108 108 0 10108 108A108.12 108.12 0 00128 20zm0 192a84 84 0 1184-84 84.09 84.09 0 01-84 84zm-5.83-120l-2.71 16.23A45.39 45.39 0 01124 108a40 40 0 010 80 39.53 39.53 0 01-28.57-11.6 12 12 0 1117.14-16.8A15.54 15.54 0 00124 164a16 16 0 000-32 15.54 15.54 0 00-11.43 4.4A12 12 0 0192.16 126l8-48A12 12 0 01112 68h40a12 12 0 010 24z"/></svg>;
export default NumberCircleFiveBold;
