// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberFourBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M184 156h-12V48a12 12 0 00-21.37-7.5l-96 120A12 12 0 0064 180h84v28a12 12 0 0024 0v-28h12a12 12 0 000-24zm-36 0H89l59-73.79z"/></svg>;
export default NumberFourBold;
