// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberCircleNine = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm18-139.18A36 36 0 10127.94 144q.94 0 1.89-.06l-16.7 28a8 8 0 002.77 11 8 8 0 0011-2.77L159.18 126A36.05 36.05 0 00146 76.82zm-.67 41.18A20 20 0 11138 90.68a20 20 0 017.31 27.32z"/></svg>;
export default NumberCircleNine;
