// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberThree = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 160a56 56 0 01-93.33 41.74 8 8 0 1110.66-11.92A40 40 0 10120 120a8 8 0 01-6.4-12.8L152 56H88a8 8 0 010-16h80a8 8 0 016.4 12.8l-39.84 53.12A56.1 56.1 0 01176 160z"/></svg>;
export default NumberThree;
