// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberSquareTwo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 32H48a16 16 0 00-16 16v160a16 16 0 0016 16h160a16 16 0 0016-16V48a16 16 0 00-16-16zm0 176H48V48h160v160zm-48-32a8 8 0 01-8 8h-48a8 8 0 01-6.4-12.8l43.17-57.56a16 16 0 10-27.86-15 8 8 0 01-15.09-5.34 32.43 32.43 0 014.62-8.59 32 32 0 1151.11 38.52L120 168h32a8 8 0 018 8z"/></svg>;
export default NumberSquareTwo;
