// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberEightLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M151.62 119.45a46 46 0 10-47.24 0 54 54 0 1047.24 0zM94 80a34 34 0 1134 34 34 34 0 01-34-34zm34 130a42 42 0 1142-42 42 42 0 01-42 42z"/></svg>;
export default NumberEightLight;
