// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberCircleOne = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm12-136v96a8 8 0 01-16 0V95l-11.56 7.71a8 8 0 11-8.88-13.32l24-16A8 8 0 01140 80z"/></svg>;
export default NumberCircleOne;
