// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberTwoDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 40v176a16 16 0 01-16 16H56a16 16 0 01-16-16V40a16 16 0 0116-16h144a16 16 0 0116 16z" opacity=".2"/><path d="M176 208a8 8 0 01-8 8H88a8 8 0 01-6.4-12.8l71.94-95.92a32 32 0 10-51.1-38.53 32.5 32.5 0 00-3.78 6.46A8 8 0 1184 68.8a48 48 0 1182.33 48.09L104 200h64a8 8 0 018 8z"/></svg>;
export default NumberTwoDuotone;
