// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const NumberSquareEightFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M112 100a16 16 0 1116 16 16 16 0 01-16-16zm16 32a20 20 0 1020 20 20 20 0 00-20-20zm96-84v160a16 16 0 01-16 16H48a16 16 0 01-16-16V48a16 16 0 0116-16h160a16 16 0 0116 16zm-60 104a35.93 35.93 0 00-14.19-28.61 32 32 0 10-43.62 0A36 36 0 10164 152z"/></svg>;
export default NumberSquareEightFill;
