// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const OptionBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236 192a12 12 0 01-12 12h-63.06a19.89 19.89 0 01-17.88-11.06L92.58 92H32a12 12 0 010-24h63.06a19.89 19.89 0 0117.88 11.06L163.42 180H224a12 12 0 0112 12zM152 92h72a12 12 0 000-24h-72a12 12 0 000 24z"/></svg>;
export default OptionBold;
