// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const OrangeThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M155.62 72.69A60.09 60.09 0 00196 16a4 4 0 00-4-4h-8a60.09 60.09 0 00-56 38.5A60.09 60.09 0 0072 12h-8a4 4 0 000 8h8a52.06 52.06 0 0151.84 48.11 84 84 0 1031.78 4.58zM184 20h3.85A52.07 52.07 0 01136 68h-3.85A52.07 52.07 0 01184 20zm-56 208a76 76 0 1176-76 76.08 76.08 0 01-76 76zm51.94-67.34A53.45 53.45 0 01136.66 204a5 5 0 01-.66.05 4 4 0 01-.66-7.95 45.33 45.33 0 0036.72-36.71 4 4 0 117.88 1.32z"/></svg>;
export default OrangeThin;
