// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const OvenLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 34H48a14 14 0 00-14 14v160a14 14 0 0014 14h160a14 14 0 0014-14V48a14 14 0 00-14-14zm2 174a2 2 0 01-2 2H48a2 2 0 01-2-2V48a2 2 0 012-2h160a2 2 0 012 2zM74 76a10 10 0 1110 10 10 10 0 01-10-10zm44 0a10 10 0 1110 10 10 10 0 01-10-10zm44 0a10 10 0 1110 10 10 10 0 01-10-10zm22 30H72a6 6 0 00-6 6v72a6 6 0 006 6h112a6 6 0 006-6v-72a6 6 0 00-6-6zm-6 72H78v-60h100z"/></svg>;
export default OvenLight;
