// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PaintRollerThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 92h-20V64a12 12 0 00-12-12H48a12 12 0 00-12 12v28H16a4 4 0 000 8h20v28a12 12 0 0012 12h152a12 12 0 0012-12v-28h20a4 4 0 014 4v50a4 4 0 01-2.9 3.84L132.7 186.5A12 12 0 00124 198v34a4 4 0 008 0v-34a4 4 0 012.9-3.84l100.4-28.66A12 12 0 00244 154v-50a12 12 0 00-12-12zm-28 36a4 4 0 01-4 4H48a4 4 0 01-4-4V64a4 4 0 014-4h152a4 4 0 014 4z"/></svg>;
export default PaintRollerThin;
