// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PaperclipHorizontalBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M252 128a60.07 60.07 0 01-60 60H44a40 40 0 010-80h140a12 12 0 010 24H44a16 16 0 000 32h148a36 36 0 000-72H80a12 12 0 010-24h112a60.07 60.07 0 0160 60z"/></svg>;
export default PaperclipHorizontalBold;
