// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ParagraphThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 44H96a60 60 0 000 120h44v44a4 4 0 008 0V52h32v156a4 4 0 008 0V52h20a4 4 0 000-8zm-68 112H96a52 52 0 010-104h44z"/></svg>;
export default ParagraphThin;
