// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PathThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 172a28 28 0 00-27.71 24H72a36 36 0 010-72h96a36 36 0 000-72H72a4 4 0 000 8h96a28 28 0 010 56H72a44 44 0 000 88h100.29A28 28 0 10200 172zm0 48a20 20 0 1120-20 20 20 0 01-20 20z"/></svg>;
export default PathThin;
