// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PencilSimpleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224.49 76.2L179.8 31.51a12 12 0 00-17 0l-29.63 29.66-93.65 93.66a11.9 11.9 0 00-3.52 8.48V208a12 12 0 0012 12h44.69a12 12 0 008.48-3.51L224.48 93.17a12 12 0 000-17zm-129 134.63a4 4 0 01-2.8 1.17H48a4 4 0 01-4-4v-44.69a4 4 0 011.17-2.83L136 69.65 186.34 120zM218.83 87.51L192 114.34 141.66 64l26.82-26.83a4 4 0 015.66 0l44.69 44.68a4 4 0 010 5.66z"/></svg>;
export default PencilSimpleThin;
