// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PerspectiveLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 122h-18V48a14 14 0 00-16.5-13.77l-160 29.09A14 14 0 0034 77.09V122H16a6 6 0 000 12h18v44.91a14 14 0 0011.5 13.77l160 29.09a14.2 14.2 0 002.5.23 14 14 0 0014-14v-74h18a6 6 0 000-12zM46 77.09a2 2 0 011.64-2l160-29.1h.37a2 2 0 012 2v74H46zM210 208a2 2 0 01-.72 1.53 2 2 0 01-1.64.44l-160-29.1a2 2 0 01-1.64-2V134h164z"/></svg>;
export default PerspectiveLight;
