// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Perspective = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 120h-16V48a16 16 0 00-18.86-15.74l-160 29.09A16 16 0 0032 77.09V120H16a8 8 0 000 16h16v42.91a16 16 0 0013.14 15.74l160 29.09a16.47 16.47 0 002.86.26 16 16 0 0016-16v-72h16a8 8 0 000-16zM48 77.09L208 48v72H48zM208 208L48 178.91V136h160z"/></svg>;
export default Perspective;
