// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PersonFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M100 36a28 28 0 1128 28 28 28 0 01-28-28zm115.42 104.78l-45.25-51.3a28 28 0 00-21-9.48h-42.34a28 28 0 00-21 9.48l-45.25 51.3a16 16 0 0022.56 22.69L89 142.7l-19.7 74.88a16 16 0 0029.08 13.35L128 180l29.58 51a16 16 0 0029.08-13.35L167 142.7l25.9 20.77a16 16 0 0022.56-22.69z"/></svg>;
export default PersonFill;
