// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PhosphorLogoLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M152 34H72a6 6 0 00-6 6v128a78.09 78.09 0 0078 78 6 6 0 006-6v-66h2a70 70 0 000-140zM78 62.91L133.74 162H78zm60 82.19L82.26 46H138zM78.28 174H138v59.73A66.1 66.1 0 0178.28 174zM152 162h-2V46h2a58 58 0 010 116z"/></svg>;
export default PhosphorLogoLight;
