// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PinterestLogoBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 112c0 23.6-8.29 45.23-23.35 60.88C190.52 187.57 171.33 196 152 196c-15.45 0-26.78-4.18-34.89-9.31l-9.43 40.06a12 12 0 11-23.36-5.5l32-136a12 12 0 1123.36 5.5l-16.45 69.93C126.72 164.86 135.16 172 152 172c25.56 0 52-22.45 52-60a68 68 0 10-126.91 34 12 12 0 01-20.77 12A92 92 0 11228 112z"/></svg>;
export default PinterestLogoBold;
