// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlayFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 128a15.74 15.74 0 01-7.6 13.51L88.32 229.65a16 16 0 01-16.2.3A15.86 15.86 0 0164 216.13V39.87a15.86 15.86 0 018.12-13.82 16 16 0 0116.2.3l144.08 88.14A15.74 15.74 0 01240 128z"/></svg>;
export default PlayFill;
