// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlugCharging = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 56h-48V16a8 8 0 00-16 0v40H96V16a8 8 0 00-16 0v40H32.55C26.28 56 24 60.78 24 64a8 8 0 008 8h16v88a40 40 0 0040 40h32v40a8 8 0 0016 0v-40h32a40 40 0 0040-40V72h16a8 8 0 000-16zm-56 128H88a24 24 0 01-24-24V72h128v88a24 24 0 01-24 24zm-17.42-60.56a8 8 0 01.91 7.37l-12 32a8 8 0 01-15-5.62l8-21.19H112a8 8 0 01-7.49-10.81l12-32a8 8 0 1115 5.62l-8 21.19H144a8 8 0 016.58 3.44z"/></svg>;
export default PlugCharging;
