// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PlusMinus = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M205.66 61.66l-144 144a8 8 0 01-11.32-11.32l144-144a8 8 0 0111.32 11.32zM64 112a8 8 0 0016 0V80h32a8 8 0 000-16H80V32a8 8 0 00-16 0v32H32a8 8 0 000 16h32zm160 64h-80a8 8 0 000 16h80a8 8 0 000-16z"/></svg>;
export default PlusMinus;
