// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PoliceCarBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 100h-9l-26.28-45.92A20 20 0 00187.36 44H68.64a20 20 0 00-17.36 10.08L25 100h-9a12 12 0 000 24h4v76a20 20 0 0020 20h28a20 20 0 0020-20v-20h80v20a20 20 0 0020 20h28a20 20 0 0020-20v-76h4a12 12 0 000-24zM71 68h114l18.28 32H52.68zm-7 128H44v-16h20zm148 0h-20v-16h20zm0-40H44v-32h168zM92 20a12 12 0 0112-12h48a12 12 0 010 24h-48a12 12 0 01-12-12z"/></svg>;
export default PoliceCarBold;
