// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PopsicleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 12a68.07 68.07 0 00-68 68v96a12 12 0 0012 12h36v44a20 20 0 0040 0v-44h36a12 12 0 0012-12V80a68.07 68.07 0 00-68-68zm12 220a12 12 0 01-24 0v-44h24zm48-56a4 4 0 01-4 4H72a4 4 0 01-4-4V80a60 60 0 01120 0zM116 72v80a4 4 0 01-8 0V72a4 4 0 018 0zm32 0v80a4 4 0 01-8 0V72a4 4 0 018 0z"/></svg>;
export default PopsicleThin;
