// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PresentationChartLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 42h-82V24a6 6 0 00-12 0v18H40a14 14 0 00-14 14v120a14 14 0 0014 14h43.52l-24.21 30.25a6 6 0 009.38 7.5L98.88 190h58.24l30.19 37.75a6 6 0 009.38-7.5L172.48 190H216a14 14 0 0014-14V56a14 14 0 00-14-14zm2 134a2 2 0 01-2 2H40a2 2 0 01-2-2V56a2 2 0 012-2h176a2 2 0 012 2zm-116-56v24a6 6 0 01-12 0v-24a6 6 0 0112 0zm32-16v40a6 6 0 01-12 0v-40a6 6 0 0112 0zm32-16v56a6 6 0 01-12 0V88a6 6 0 0112 0z"/></svg>;
export default PresentationChartLight;
