// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ProjectorScreenFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 64V48a16 16 0 00-16-16H40a16 16 0 00-16 16v16a16 16 0 0016 16v96h-8a8 8 0 000 16h88v17.38a24 24 0 1016 0V192h88a8 8 0 000-16h-8V80a16 16 0 0016-16zM128 240a8 8 0 118-8 8 8 0 01-8 8zM40 48h176v16H40z"/></svg>;
export default ProjectorScreenFill;
