// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ProjectorScreenBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236 72V48a20 20 0 00-20-20H40a20 20 0 00-20 20v24a20 20 0 0016 19.6V164h-4a12 12 0 000 24h84v23.22a24 24 0 1024 0V188h84a12 12 0 000-24h-4V91.6A20 20 0 00236 72zM44 52h168v16H44zm16 112V92h136v72z"/></svg>;
export default ProjectorScreenBold;
