// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Record = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zm0 192a88 88 0 1188-88 88.1 88.1 0 01-88 88zm0-160a72 72 0 1072 72 72.08 72.08 0 00-72-72zm0 128a56 56 0 1156-56 56.06 56.06 0 01-56 56z"/></svg>;
export default Record;
