// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ReplitLogoBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 84h-60V40a20 20 0 00-20-20H72a20 20 0 00-20 20v48a20 20 0 0020 20h60v40H72a20 20 0 00-20 20v48a20 20 0 0020 20h64a20 20 0 0020-20v-44h60a20 20 0 0020-20v-48a20 20 0 00-20-20zm-84 128H76v-40h56zm0-128H76V44h56zm80 64h-56v-40h56z"/></svg>;
export default ReplitLogoBold;
