// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RewindFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 71.84v112.32a15.92 15.92 0 01-24.48 13.34L128 146.86v37.3a15.92 15.92 0 01-24.48 13.34l-88.19-56.16a15.8 15.8 0 010-26.68l88.19-56.16A15.91 15.91 0 01128 71.84v37.3l79.52-50.64A15.91 15.91 0 01232 71.84z"/></svg>;
export default RewindFill;
