// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const RulerDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M229.66 90.34L90.34 229.66a8 8 0 01-11.31 0L26.34 177a8 8 0 010-11.31L165.66 26.34a8 8 0 0111.31 0L229.66 79a8 8 0 010 11.34z" opacity=".2"/><path d="M235.32 73.37l-52.69-52.68a16 16 0 00-22.63 0L20.68 160a16 16 0 000 22.63l52.69 52.68a16 16 0 0022.63 0L235.32 96a16 16 0 000-22.63zM84.68 224L32 171.31l32-32 26.34 26.35a8 8 0 0011.32-11.32L75.31 128 96 107.31l26.34 26.35a8 8 0 0011.32-11.32L107.31 96 128 75.31l26.34 26.35a8 8 0 0011.32-11.32L139.31 64l32-32L224 84.69z"/></svg>;
export default RulerDuotone;
