// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Sailboat = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M247.21 172.53A8 8 0 00240 168h-96v-24h72a8 8 0 005.92-13.38L144 44.91V8a8 8 0 00-14.21-5l-104 128A8 8 0 0032 144h96v24H16a8 8 0 00-6.25 13l29.6 37a15.93 15.93 0 0012.49 6h152.32a15.93 15.93 0 0012.49-6l29.6-37a8 8 0 00.96-8.47zM197.92 128H144V68.69zm-149.11 0L128 30.53V128zm155.35 80H51.84l-19.2-24h190.72z"/></svg>;
export default Sailboat;
