// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Scan = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 40v40a8 8 0 01-16 0V48h-32a8 8 0 010-16h40a8 8 0 018 8zM80 208H48v-32a8 8 0 00-16 0v40a8 8 0 008 8h40a8 8 0 000-16zm136-40a8 8 0 00-8 8v32h-32a8 8 0 000 16h40a8 8 0 008-8v-40a8 8 0 00-8-8zM40 88a8 8 0 008-8V48h32a8 8 0 000-16H40a8 8 0 00-8 8v40a8 8 0 008 8zm40-16h96a8 8 0 018 8v96a8 8 0 01-8 8H80a8 8 0 01-8-8V80a8 8 0 018-8zm8 96h80V88H88z"/></svg>;
export default Scan;
