// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Seatbelt = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M172 68a44 44 0 10-44 44 44.05 44.05 0 0044-44zm-44 28a28 28 0 1128-28 28 28 0 01-28 28zm80 128a8 8 0 01-8 8H56a8 8 0 01-5.29-14l98.07-86.54a64 64 0 00-84 50.33A8 8 0 0149 179.25a80 80 0 01113.16-59.59L186.71 98a8 8 0 0110.58 12L77.16 216H200a8 8 0 018 8zm-14.27-77.62A79.6 79.6 0 01208 192a8 8 0 01-16 0 63.67 63.67 0 00-11.41-36.49 8 8 0 0113.14-9.13z"/></svg>;
export default Seatbelt;
