// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SecurityCameraLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M248 138a6 6 0 00-6 6v18h-46.69a2 2 0 01-1.41-.59l-19.76-19.75L225.9 89.9a14 14 0 000-19.8l-56-56a14 14 0 00-19.81 0L4.34 160.35A8 8 0 0010 174h40.2l35.9 35.9a14 14 0 0019.8 0l59.76-59.76 19.75 19.76a13.94 13.94 0 009.9 4.1H242v18a6 6 0 0012 0v-48a6 6 0 00-6-6zM158.59 22.59a2 2 0 012.82 0l14.1 14.1L50.2 162H19.64zM97.41 201.41a2 2 0 01-2.82 0L61.17 168 184 45.17l33.41 33.42a2 2 0 010 2.82z"/></svg>;
export default SecurityCameraLight;
