// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SelectionInverseThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M148 216a4 4 0 01-4 4h-32a4 4 0 010-8h32a4 4 0 014 4zM40 148a4 4 0 004-4v-32a4 4 0 00-8 0v32a4 4 0 004 4zm32 64H48a4 4 0 01-4-4v-24a4 4 0 00-8 0v24a12 12 0 0012 12h24a4 4 0 000-8zM220 48v160a12 12 0 01-12 12h-24a4 4 0 010-8h22.34L44 49.66V72a4 4 0 01-8 0V48a12 12 0 0112-12h160a12 12 0 0112 12zm-12-4H49.66L212 206.34V48a4 4 0 00-4-4z"/></svg>;
export default SelectionInverseThin;
