// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShareFatLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236.24 107.76l-80-80A6 6 0 00146 32v42.2c-54.48 3.59-120.39 55-127.93 120.66a10 10 0 0017.23 8C46.56 190.85 87 152.6 146 150.13V192a6 6 0 0010.24 4.24l80-80a6 6 0 000-8.48zM158 177.52V144a6 6 0 00-6-6c-27.73 0-54.76 7.25-80.32 21.55a193.38 193.38 0 00-40.81 30.65c4.7-26.56 20.16-52 44-72.27C98.47 97.94 127.29 86 152 86a6 6 0 006-6V46.49L223.51 112z"/></svg>;
export default ShareFatLight;
