// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShieldCheckeredFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 40H48a16 16 0 00-16 16v56c0 52.72 25.52 84.67 46.93 102.19 23.06 18.86 46 25.27 47 25.53a8 8 0 004.2 0c1-.26 23.91-6.67 47-25.53C198.48 196.67 224 164.72 224 112V56a16 16 0 00-16-16zm-80 183.62a128.25 128.25 0 01-38.92-21.81C65.83 182.79 52.37 158 48.9 128H128V56h80v56a141.24 141.24 0 01-.9 16H128v95.62z"/></svg>;
export default ShieldCheckeredFill;
