// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShieldCheckeredLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 42H48a14 14 0 00-14 14v56c0 51.94 25.12 83.4 46.2 100.64 22.73 18.6 45.27 24.89 46.22 25.15a6 6 0 003.16 0c.95-.26 23.49-6.55 46.22-25.15C196.88 195.4 222 163.94 222 112V56a14 14 0 00-14-14zm2 14v56c0 3.39-.12 6.72-.34 10H134V54h74a2 2 0 012 2zM46 56a2 2 0 012-2h74v68H46.34c-.22-3.28-.34-6.61-.34-10zm1.71 78H122v89.52a133.13 133.13 0 01-34.56-20.46C65.5 185 52.2 161.8 47.71 134zm120.85 69.06A133.13 133.13 0 01134 223.52V134h74.29c-4.49 27.8-17.79 51-39.73 69.06z"/></svg>;
export default ShieldCheckeredLight;
