// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SidebarLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 42H40a14 14 0 00-14 14v144a14 14 0 0014 14h176a14 14 0 0014-14V56a14 14 0 00-14-14zM38 200v-50h18a6 6 0 000-12H38v-20h18a6 6 0 000-12H38V86h18a6 6 0 000-12H38V56a2 2 0 012-2h42v148H40a2 2 0 01-2-2zm180 0a2 2 0 01-2 2H94V54h122a2 2 0 012 2z"/></svg>;
export default SidebarLight;
