// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SigmaFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 24H56a16 16 0 00-16 16v176a16 16 0 0016 16h144a16 16 0 0016-16V40a16 16 0 00-16-16zm-16 64a8 8 0 01-16 0V72H96l38.4 51.2a8 8 0 010 9.6L96 184h72v-16a8 8 0 0116 0v24a8 8 0 01-8 8H80a8 8 0 01-6.4-12.8L118 128 73.6 68.8A8 8 0 0180 56h96a8 8 0 018 8z"/></svg>;
export default SigmaFill;
