// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SignpostFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M246 117.35l-33.67 37.35a16 16 0 01-11.89 5.3H136v64a8 8 0 01-16 0v-64H40a16 16 0 01-16-16V80a16 16 0 0116-16h80V32a8 8 0 0116 0v32h64.44a16 16 0 0111.89 5.3L246 106.65a8 8 0 010 10.7z"/></svg>;
export default SignpostFill;
