// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SimCardBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216.49 79.51l-56-56A12 12 0 00152 20H56a20 20 0 00-20 20v176a20 20 0 0020 20h144a20 20 0 0020-20V88a12 12 0 00-3.51-8.49zM196 212H60V44h87l49 49zM88 112a12 12 0 00-12 12v60a12 12 0 0012 12h80a12 12 0 0012-12v-60a12 12 0 00-12-12zm12 24h16v36h-16zm56 36h-16v-36h16z"/></svg>;
export default SimCardBold;
