// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SimCardDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 120v72H80v-72z" opacity=".2"/><path d="M213.66 82.34l-56-56A8 8 0 00152 24H56a16 16 0 00-16 16v176a16 16 0 0016 16h144a16 16 0 0016-16V88a8 8 0 00-2.34-5.66zM200 216H56V40h92.69L200 91.31V216zm-24-104H80a8 8 0 00-8 8v72a8 8 0 008 8h96a8 8 0 008-8v-72a8 8 0 00-8-8zm-8 72h-16v-32a8 8 0 00-16 0v32h-16v-32a8 8 0 00-16 0v32H88v-56h80z"/></svg>;
export default SimCardDuotone;
