// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SlideshowLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 50H64a14 14 0 00-14 14v128a14 14 0 0014 14h128a14 14 0 0014-14V64a14 14 0 00-14-14zm2 142a2 2 0 01-2 2H64a2 2 0 01-2-2V64a2 2 0 012-2h128a2 2 0 012 2zm44-136v144a6 6 0 01-12 0V56a6 6 0 0112 0zM30 56v144a6 6 0 01-12 0V56a6 6 0 0112 0z"/></svg>;
export default SlideshowLight;
