// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SmileyAngryThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M100 140a8 8 0 11-8-8 8 8 0 018 8zm64-8a8 8 0 108 8 8 8 0 00-8-8zm64-4A100 100 0 11128 28a100.11 100.11 0 01100 100zm-8 0a92 92 0 10-92 92 92.1 92.1 0 0092-92zm-46.22-43.33L128 115.19 82.22 84.67a4 4 0 10-4.44 6.66l48 32a4 4 0 004.44 0l48-32a4 4 0 10-4.44-6.66zm-19.57 96c-7.82-5.2-15.27-8.67-26.21-8.67s-18.39 3.47-26.21 8.67a4 4 0 104.42 6.66C113.2 182.69 119 180 128 180s14.8 2.69 21.79 7.33a4 4 0 104.42-6.66z"/></svg>;
export default SmileyAngryThin;
