// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SmileyAngryBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M92 156a16 16 0 1116-16 16 16 0 01-16 16zm72-32a16 16 0 1016 16 16 16 0 00-16-16zm72 4A108 108 0 11128 20a108.12 108.12 0 01108 108zm-24 0a84 84 0 10-84 84 84.09 84.09 0 0084-84zM85.34 102l36 24a12 12 0 0013.32 0l36-24a12 12 0 00-13.32-20L128 101.58 98.66 82a12 12 0 00-13.32 20zM154 167.12a51.1 51.1 0 00-52 0 12 12 0 1012 20.76 27.13 27.13 0 0128 0 12 12 0 1012-20.76z"/></svg>;
export default SmileyAngryBold;
