// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SolarRoofDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 128H96L56 48h144z" opacity=".2"/><path d="M247.16 124.42l-40-80A8 8 0 00200 40H56a8 8 0 00-7.16 4.42l-40 80A8.08 8.08 0 008 128v56a16 16 0 0016 16h208a16 16 0 0016-16v-56a8.08 8.08 0 00-.84-3.58zM99.06 56l12 24H80.94l-12-24zm48 0l12 24h-30.12l-12-24zm-46.12 64l-12-24h30.12l12 24zm48 0l-12-24h30.12l12 24zm48 0l-12-24h30.12l12 24zm10.12-40h-30.12l-12-24h30.12zM24 129.89l32-64 32 64V184H24zM104 184v-48h128v48z"/></svg>;
export default SolarRoofDuotone;
