// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SpeakerHifiDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 32H64a8 8 0 00-8 8v176a8 8 0 008 8h128a8 8 0 008-8V40a8 8 0 00-8-8zm-64 152a32 32 0 1132-32 32 32 0 01-32 32z" opacity=".2"/><path d="M192 24H64a16 16 0 00-16 16v176a16 16 0 0016 16h128a16 16 0 0016-16V40a16 16 0 00-16-16zm0 192H64V40h128zM116 76a12 12 0 1112 12 12 12 0 01-12-12zm12 116a40 40 0 10-40-40 40 40 0 0040 40zm0-64a24 24 0 11-24 24 24 24 0 0124-24z"/></svg>;
export default SpeakerHifiDuotone;
