// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SpeakerSimpleLowDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M160 32v192l-72-56H40a8 8 0 01-8-8V96a8 8 0 018-8h48z" opacity=".2"/><path d="M163.51 24.81a8 8 0 00-8.42.88L85.25 80H40a16 16 0 00-16 16v64a16 16 0 0016 16h45.25l69.84 54.31A8 8 0 00168 224V32a8 8 0 00-4.49-7.19zM152 207.64l-59.09-45.95A7.94 7.94 0 0088 160H40V96h48a7.94 7.94 0 004.91-1.69L152 48.36zM208 104v48a8 8 0 01-16 0v-48a8 8 0 0116 0z"/></svg>;
export default SpeakerSimpleLowDuotone;
