// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SpinnerGapThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M132 32v32a4 4 0 01-8 0V32a4 4 0 018 0zm92 92h-32a4 4 0 000 8h32a4 4 0 000-8zm-47.92 46.43a4 4 0 10-5.65 5.65l22.62 22.63a4 4 0 005.66-5.66zM128 188a4 4 0 00-4 4v32a4 4 0 008 0v-32a4 4 0 00-4-4zm-48.08-17.57l-22.63 22.62a4 4 0 005.71 5.66l22.62-22.63a4 4 0 10-5.65-5.65zM68 128a4 4 0 00-4-4H32a4 4 0 000 8h32a4 4 0 004-4zm-5-70.71A4 4 0 0057.29 63l22.63 22.57a4 4 0 105.65-5.65z"/></svg>;
export default SpinnerGapThin;
