// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SpinnerGapLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M134 32v32a6 6 0 01-12 0V32a6 6 0 0112 0zm90 90h-32a6 6 0 000 12h32a6 6 0 000-12zm-46.5 47a6 6 0 00-8.5 8.5l22.63 22.62a6 6 0 008.48-8.48zM128 186a6 6 0 00-6 6v32a6 6 0 0012 0v-32a6 6 0 00-6-6zm-49.5-17l-22.62 22.64a6 6 0 108.48 8.48L87 177.5a6 6 0 10-8.5-8.5zM70 128a6 6 0 00-6-6H32a6 6 0 000 12h32a6 6 0 006-6zm-5.64-72.12a6 6 0 00-8.48 8.48L78.5 87a6 6 0 108.5-8.5z"/></svg>;
export default SpinnerGapLight;
