// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SquareHalfBottomLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 42H56a14 14 0 00-14 14v144a14 14 0 0014 14h144a14 14 0 0014-14V56a14 14 0 00-14-14zM56 54h144a2 2 0 012 2v66H54V56a2 2 0 012-2zm50 80v68H86v-68zm12 0h20v68h-20zm32 0h20v68h-20zm-96 66v-66h20v68H56a2 2 0 01-2-2zm146 2h-18v-68h20v66a2 2 0 01-2 2z"/></svg>;
export default SquareHalfBottomLight;
