// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StackSimpleBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M10.05 110.42l112 64a12 12 0 0011.9 0l112-64a12 12 0 000-20.84l-112-64a12 12 0 00-11.9 0l-112 64a12 12 0 000 20.84zm118-60.6L215.81 100 128 150.18 40.19 100zm122.42 92.23a12 12 0 01-4.47 16.37l-112 64a12 12 0 01-11.9 0l-112-64A12 12 0 1122 137.58l106 60.6 106-60.6a12 12 0 0116.42 4.47z"/></svg>;
export default StackSimpleBold;
