// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StackLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M229.18 173a6 6 0 01-2.16 8.2l-96 56a6 6 0 01-6 0l-96-56a6 6 0 016-10.36l93 54.23 93-54.23a6 6 0 018.16 2.16zM221 122.82l-93 54.23-93-54.23a6 6 0 00-6 10.36l96 56a6 6 0 006 0l96-56a6 6 0 00-6-10.36zM26 80a6 6 0 013-5.18l96-56a6 6 0 016 0l96 56a6 6 0 010 10.36l-96 56a6 6 0 01-6 0l-96-56A6 6 0 0126 80zm17.91 0L128 129.05 212.09 80 128 31z"/></svg>;
export default StackLight;
