// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StackDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 80l-96 56-96-56 96-56z" opacity=".2"/><path d="M230.91 172a8 8 0 01-2.91 10.91l-96 56a8 8 0 01-8.06 0l-96-56A8 8 0 0136 169.09l92 53.65 92-53.65a8 8 0 0110.91 2.91zM220 121.09l-92 53.65-92-53.65a8 8 0 00-8 13.82l96 56a8 8 0 008.06 0l96-56a8 8 0 10-8.06-13.82zM24 80a8 8 0 014-6.91l96-56a8 8 0 018.06 0l96 56a8 8 0 010 13.82l-96 56a8 8 0 01-8.06 0l-96-56A8 8 0 0124 80zm23.88 0L128 126.74 208.12 80 128 33.26z"/></svg>;
export default StackDuotone;
