// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StarFourThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228.13 116.77l-65.19-23.71-23.71-65.19a11.95 11.95 0 00-22.46 0L93.06 93.06l-65.19 23.71a11.95 11.95 0 000 22.46l65.19 23.71 23.71 65.19a11.95 11.95 0 0022.46 0l23.71-65.19 65.19-23.71a11.95 11.95 0 000-22.46zm-2.73 15l-67 24.34a4 4 0 00-2.39 2.39l-24.34 67a4 4 0 01-7.44 0l-24.34-67a4 4 0 00-2.39-2.39l-66.9-24.39a4 4 0 010-7.44l66.95-24.34a4 4 0 002.39-2.39l24.34-66.95a4 4 0 017.44 0l24.34 66.95a4 4 0 002.39 2.39l67 24.34a4 4 0 010 7.44z"/></svg>;
export default StarFourThin;
