// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StethoscopeThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 160a8 8 0 11-8-8 8 8 0 018 8zm-4.17 35.79A44.06 44.06 0 01168 236h-24a44.05 44.05 0 01-44-44v-44.15A60 60 0 0144 88V40a4 4 0 014-4h24a4 4 0 010 8H52v44a52 52 0 0052.69 52C133 139.63 156 115.93 156 87.17V44h-20a4 4 0 010-8h24a4 4 0 014 4v47.17c0 32-24.84 58.59-56 60.69V192a36 36 0 0036 36h24a36.05 36.05 0 0035.8-32.25 36 36 0 118 0zM236 160a28 28 0 10-28 28 28 28 0 0028-28z"/></svg>;
export default StethoscopeThin;
