// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StudentFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M226.53 56.41l-96-32a8 8 0 00-5.06 0l-96 32A8 8 0 0024 64v80a8 8 0 0016 0V75.1l33.59 11.19a64 64 0 0020.65 88.05c-18 7.06-33.56 19.83-44.94 37.29a8 8 0 1013.4 8.74C77.77 197.25 101.57 184 128 184s50.23 13.25 65.3 36.37a8 8 0 0013.4-8.74c-11.38-17.46-27-30.23-44.94-37.29a64 64 0 0020.65-88l44.12-14.7a8 8 0 000-15.18zM176 120a48 48 0 11-86.65-28.45l36.12 12a8 8 0 005.06 0l36.12-12A47.89 47.89 0 01176 120z"/></svg>;
export default StudentFill;
