// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SubsetProperOfBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M212 208a12 12 0 01-12 12h-72a92 92 0 010-184h72a12 12 0 010 24h-72a68 68 0 000 136h72a12 12 0 0112 12z"/></svg>;
export default SubsetProperOfBold;
