// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SubtitlesSlashBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M48 128a12 12 0 0112-12h16a12 12 0 010 24H60a12 12 0 01-12-12zm168.88 79.93a12 12 0 11-17.76 16.14l-11-12.07H32a20 20 0 01-20-20V64a20 20 0 0120-20h4.68a12 12 0 0120.2-12.07zM166.33 188l-10.91-12H60a12 12 0 010-24h73.6l-10.91-12H116a12 12 0 01-10.1-18.47L57.24 68H36v120zM224 44H116.6a12 12 0 000 24H220v114.94a12 12 0 0024 0V64a20 20 0 00-20-20zm-28 96a12 12 0 000-24h-13.94a12 12 0 000 24z"/></svg>;
export default SubtitlesSlashBold;
