// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SuitcaseRollingFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M192 48h-24V24a24 24 0 00-24-24h-32a24 24 0 00-24 24v24H64a16 16 0 00-16 16v144a16 16 0 0016 16h16v16a8 8 0 0016 0v-16h64v16a8 8 0 0016 0v-16h16a16 16 0 0016-16V64a16 16 0 00-16-16zM96 192a8 8 0 01-16 0V80a8 8 0 0116 0zm40 0a8 8 0 01-16 0V80a8 8 0 0116 0zm16-144h-48V24a8 8 0 018-8h32a8 8 0 018 8zm24 144a8 8 0 01-16 0V80a8 8 0 0116 0z"/></svg>;
export default SuitcaseRollingFill;
