// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SuitcaseSimpleDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 152v48a8 8 0 01-8 8H40a8 8 0 01-8-8v-48z" opacity=".2"/><path d="M216 56h-40v-8a24 24 0 00-24-24h-48a24 24 0 00-24 24v8H40a16 16 0 00-16 16v128a16 16 0 0016 16h176a16 16 0 0016-16V72a16 16 0 00-16-16zM96 48a8 8 0 018-8h48a8 8 0 018 8v8H96zm120 24v72H40V72zm0 128H40v-40h176v40z"/></svg>;
export default SuitcaseSimpleDuotone;
