// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const SunglassesDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M32 136h72v28a36 36 0 01-72 0zm120 0v28a36 36 0 0072 0v-28z" opacity=".2"/><path d="M200 40a8 8 0 000 16 16 16 0 0116 16v56H40V72a16 16 0 0116-16 8 8 0 000-16 32 32 0 00-32 32v92a44 44 0 0088 0v-20h32v20a44 44 0 0088 0V72a32 32 0 00-32-32zm12.63 137.31L179.31 144H216v20a27.8 27.8 0 01-3.37 13.31zM40 164v-16.69l41.31 41.32A28 28 0 0140 164zm56 0a27.8 27.8 0 01-3.37 13.31L59.31 144H96zm64 0v-16.69l41.31 41.32A28 28 0 01160 164z"/></svg>;
export default SunglassesDuotone;
