// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TagChevronBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M250 121.34l-45.64-68.43A20 20 0 00187.72 44H32a12 12 0 00-10 18.66L65.58 128 22 193.34A12 12 0 0032 212h155.72a20 20 0 0016.64-8.91L250 134.66a12 12 0 000-13.32zM185.58 188H54.42L90 134.66a12 12 0 000-13.32L54.42 68h131.16l40 60z"/></svg>;
export default TagChevronBold;
