// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TelevisionSimpleFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 64h-68.69l34.35-34.34a8 8 0 10-11.32-11.32L128 60.69 85.66 18.34a8 8 0 00-11.32 11.32L108.69 64H40a16 16 0 00-16 16v120a16 16 0 0016 16h176a16 16 0 0016-16V80a16 16 0 00-16-16zm0 136H40V80h176v120zm-16-100v80a4 4 0 01-4 4H60a4 4 0 01-4-4v-80a4 4 0 014-4h136a4 4 0 014 4z"/></svg>;
export default TelevisionSimpleFill;
