// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TennisBallLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200.16 55.88a102 102 0 100 144.24 101.4 101.4 0 000-144.24zM64.33 64.36a89.62 89.62 0 0157.25-26.07 89.32 89.32 0 01-26.12 57.18 89.38 89.38 0 01-57.21 26.11 89.61 89.61 0 0126.08-57.22zM38.2 133.63A101.36 101.36 0 00104 104a101.24 101.24 0 0029.68-65.72 89.76 89.76 0 0184.17 84.13 102 102 0 00-95.43 95.39 89.76 89.76 0 01-84.22-84.17zm153.47 58a89.63 89.63 0 01-57.25 26.06 89.94 89.94 0 0183.33-83.28 89.61 89.61 0 01-26.08 57.23z"/></svg>;
export default TennisBallLight;
