// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TennisBallThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M198.74 57.29A99.39 99.39 0 00128 28h-.19a100 100 0 1070.93 29.29zM62.92 63a91.38 91.38 0 0160.8-26.85 91.31 91.31 0 01-26.85 60.74 91.44 91.44 0 01-60.77 26.84A91.61 91.61 0 0162.92 63zm-26.83 68.74a99.36 99.36 0 0066.44-29.2 99.25 99.25 0 0029.21-66.45 91.9 91.9 0 0188.17 88.17 100 100 0 00-95.65 95.65 91.9 91.9 0 01-88.17-88.17zm157 61.31a91.38 91.38 0 01-60.8 26.85 92 92 0 0187.62-87.63 91.61 91.61 0 01-26.83 60.78z"/></svg>;
export default TennisBallThin;
