// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TerminalWindowDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 56v144a8 8 0 01-8 8H40a8 8 0 01-8-8V56a8 8 0 018-8h176a8 8 0 018 8z" opacity=".2"/><path d="M128 128a8 8 0 01-3 6.25l-40 32a8 8 0 11-10-12.5L107.19 128 75 102.25a8 8 0 1110-12.5l40 32a8 8 0 013 6.25zm48 24h-40a8 8 0 000 16h40a8 8 0 000-16zm56-96v144a16 16 0 01-16 16H40a16 16 0 01-16-16V56a16 16 0 0116-16h176a16 16 0 0116 16zm-16 144V56H40v144h176z"/></svg>;
export default TerminalWindowDuotone;
