// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextAlignRightBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M28 64a12 12 0 0112-12h176a12 12 0 010 24H40a12 12 0 01-12-12zm188 28H88a12 12 0 000 24h128a12 12 0 000-24zm0 40H40a12 12 0 000 24h176a12 12 0 000-24zm0 40H88a12 12 0 000 24h128a12 12 0 000-24z"/></svg>;
export default TextAlignRightBold;
