// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextTSlashBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216.07 224.88a12 12 0 01-16.95-.81L140 159v29h20a12 12 0 010 24H96a12 12 0 010-24h20v-55.36l-48-52.8V88a12 12 0 01-24 0V56a11.75 11.75 0 01.23-2.31l-5.11-5.62a12 12 0 1117.76-16.14l160 176a12 12 0 01-.81 16.95zM116 68v.57a12 12 0 1024 0V68h48v20a12 12 0 0024 0V56a12 12 0 00-12-12h-83.4a12 12 0 00-.6 24z"/></svg>;
export default TextTSlashBold;
