// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextAlignCenter = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M32 64a8 8 0 018-8h176a8 8 0 010 16H40a8 8 0 01-8-8zm32 32a8 8 0 000 16h128a8 8 0 000-16zm152 40H40a8 8 0 000 16h176a8 8 0 000-16zm-24 40H64a8 8 0 000 16h128a8 8 0 000-16z"/></svg>;
export default TextAlignCenter;
