// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextSuperscriptFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 32H48a16 16 0 00-16 16v160a16 16 0 0016 16h160a16 16 0 0016-16V48a16 16 0 00-16-16zm-81.45 147.41a8 8 0 11-13.1 9.18L92 158l-21.45 30.59a8 8 0 11-13.1-9.18L82.23 144l-24.78-35.41a8 8 0 1113.1-9.18L92 130.05l21.45-30.64a8 8 0 0113.1 9.18L101.77 144zM192 160h-40a8 8 0 01-6.4-12.8l36-48a12 12 0 10-19.15-14.46 13.06 13.06 0 00-2.58 4.81 8 8 0 11-15.68-3.18 28.17 28.17 0 1150.2 22.44L168 144h24a8 8 0 010 16z"/></svg>;
export default TextSuperscriptFill;
