// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextHFourBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M156 56v120a12 12 0 01-24 0v-48H52v48a12 12 0 01-24 0V56a12 12 0 0124 0v48h80V56a12 12 0 0124 0zm100 128a12 12 0 01-12 12v12a12 12 0 01-24 0v-12h-40a12 12 0 01-9.73-19l52-72a12 12 0 0121.73 7v60a12 12 0 0112 12zm-36-34.89L203.47 172H220z"/></svg>;
export default TextHFourBold;
