// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextColumnsDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 64v120H40V64z" opacity=".2"/><path d="M120 64a8 8 0 01-8 8H40a8 8 0 010-16h72a8 8 0 018 8zm-8 32H40a8 8 0 000 16h72a8 8 0 000-16zm0 40H40a8 8 0 000 16h72a8 8 0 000-16zm0 40H40a8 8 0 000 16h72a8 8 0 000-16zm32-104h72a8 8 0 000-16h-72a8 8 0 000 16zm72 24h-72a8 8 0 000 16h72a8 8 0 000-16zm0 40h-72a8 8 0 000 16h72a8 8 0 000-16zm0 40h-72a8 8 0 000 16h72a8 8 0 000-16z"/></svg>;
export default TextColumnsDuotone;
