// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TextHLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M206 56v144a6 6 0 01-12 0v-66H62v66a6 6 0 01-12 0V56a6 6 0 0112 0v66h132V56a6 6 0 0112 0z"/></svg>;
export default TextHLight;
