// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ThermometerThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M212 60a24 24 0 1024 24 24 24 0 00-24-24zm0 40a16 16 0 1116-16 16 16 0 01-16 16zm-88 56.29V88a4 4 0 00-8 0v68.29a28 28 0 108 0zM120 204a20 20 0 1120-20 20 20 0 01-20 20zm36-68V48a36 36 0 00-72 0v88a60 60 0 1072 0zm-36 100a52 52 0 01-29.71-94.68A4 4 0 0092 138V48a28 28 0 0156 0v90a4 4 0 001.71 3.28A52 52 0 01120 236z"/></svg>;
export default ThermometerThin;
