// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TiktokLogo = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M224 72a48.05 48.05 0 01-48-48 8 8 0 00-8-8h-40a8 8 0 00-8 8v132a20 20 0 11-28.57-18.08 8 8 0 004.57-7.23V88a8 8 0 00-9.4-7.88C50.91 86.48 24 119.1 24 156a76 76 0 00152 0v-39.71A103.25 103.25 0 00224 128a8 8 0 008-8V80a8 8 0 00-8-8zm-8 39.64a87.19 87.19 0 01-43.33-16.15A8 8 0 00160 102v54a60 60 0 01-120 0c0-25.9 16.64-49.13 40-57.6v27.67A36 36 0 10136 156V32h24.5A64.14 64.14 0 00216 87.5z"/></svg>;
export default TiktokLogo;
