// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TimerDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 136a88 88 0 11-88-88 88 88 0 0188 88z" opacity=".2"/><path d="M128 40a96 96 0 1096 96 96.11 96.11 0 00-96-96zm0 176a80 80 0 1180-80 80.09 80.09 0 01-80 80zm45.66-125.66a8 8 0 010 11.32l-40 40a8 8 0 01-11.32-11.32l40-40a8 8 0 0111.32 0zM96 16a8 8 0 018-8h48a8 8 0 010 16h-48a8 8 0 01-8-8z"/></svg>;
export default TimerDuotone;
