// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ToggleLeftThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M176 60H80a68 68 0 000 136h96a68 68 0 000-136zm0 128H80a60 60 0 010-120h96a60 60 0 010 120zM80 92a36 36 0 1036 36 36 36 0 00-36-36zm0 64a28 28 0 1128-28 28 28 0 01-28 28z"/></svg>;
export default ToggleLeftThin;
