// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TornadoThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M228 40a4 4 0 01-4 4H56a4 4 0 010-8h168a4 4 0 014 4zm-48 32a4 4 0 00-4-4H32a4 4 0 000 8h144a4 4 0 004-4zm-16 32a4 4 0 00-4-4H56a4 4 0 000 8h104a4 4 0 004-4zm16 32a4 4 0 00-4-4H88a4 4 0 000 8h88a4 4 0 004-4zm4 28h-64a4 4 0 000 8h64a4 4 0 000-8zm-24 32h-32a4 4 0 000 8h32a4 4 0 000-8zm-32 32h-16a4 4 0 000 8h16a4 4 0 000-8z"/></svg>;
export default TornadoThin;
