// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ToteSimpleDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M231.94 80.93l-14.25 120a8.06 8.06 0 01-8 7.07H46.33a8.06 8.06 0 01-8-7.07l-14.25-120a8 8 0 018-8.93h191.84a8 8 0 018.02 8.93z" opacity=".2"/><path d="M236 69.4a16.13 16.13 0 00-12.08-5.4H176a48 48 0 00-96 0H32.08a16.13 16.13 0 00-12 5.4 16 16 0 00-3.92 12.48l14.26 120a16 16 0 0016 14.12h163.25a16 16 0 0016-14.12l14.26-120A16 16 0 00236 69.4zM128 32a32 32 0 0132 32H96a32 32 0 0132-32zm81.76 168a.13.13 0 01-.09 0H46.25L32.08 80H224z"/></svg>;
export default ToteSimpleDuotone;
