// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TramFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M184 48h-48V24h32a8 8 0 000-16H88a8 8 0 000 16h32v24H72a32 32 0 00-32 32v104a32 32 0 0032 32h8l-14.4 19.2a8 8 0 1012.8 9.6L100 216h56l21.6 28.8a8 8 0 1012.8-9.6L176 216h8a32 32 0 0032-32V80a32 32 0 00-32-32zm0 152H72a16 16 0 01-16-16v-56h144v56a16 16 0 01-16 16zm-88-28a12 12 0 11-12-12 12 12 0 0112 12zm88 0a12 12 0 11-12-12 12 12 0 0112 12z"/></svg>;
export default TramFill;
