// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TrashBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M216 48h-36V36a28 28 0 00-28-28h-48a28 28 0 00-28 28v12H40a12 12 0 000 24h4v136a20 20 0 0020 20h128a20 20 0 0020-20V72h4a12 12 0 000-24zM100 36a4 4 0 014-4h48a4 4 0 014 4v12h-56zm88 168H68V72h120zm-72-100v64a12 12 0 01-24 0v-64a12 12 0 0124 0zm48 0v64a12 12 0 01-24 0v-64a12 12 0 0124 0z"/></svg>;
export default TrashBold;
