// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TruckBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M255.14 115.54l-14-35A19.89 19.89 0 00222.58 68H196v-4a12 12 0 00-12-12H32a20 20 0 00-20 20v112a20 20 0 0020 20h14.06a36 36 0 0067.88 0h44.12a36 36 0 0067.88 0H236a20 20 0 0020-20v-64a21.7 21.7 0 00-.86-4.46zM196 92h23.88l6.4 16H196zM80 204a12 12 0 1112-12 12 12 0 01-12 12zm92-41.92A36.32 36.32 0 00158.06 180h-44.12a36 36 0 00-67.88 0H36v-40h136zm0-46.08H36V76h136zm20 88a12 12 0 1112-12 12 12 0 01-12 12zm40-24h-6.06A36.09 36.09 0 00196 156.23V132h36z"/></svg>;
export default TruckBold;
