// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const TwitchLogoBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208 28H48a20 20 0 00-20 20v144a20 20 0 0020 20h12v28a12 12 0 0019.68 9.22L124.34 212h40.76a20.06 20.06 0 0012.81-4.64l42.89-35.74a19.93 19.93 0 007.2-15.37V48a20 20 0 00-20-20zm-4 126.38L163.66 188H120a12 12 0 00-7.68 2.78L84 214.38V200a12 12 0 00-12-12H52V52h152zM156 136V88a12 12 0 0124 0v48a12 12 0 01-24 0zm-48 0V88a12 12 0 0124 0v48a12 12 0 01-24 0z"/></svg>;
export default TwitchLogoBold;
