// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UmbrellaSimpleLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M238 126.79A110.43 110.43 0 0053.11 55.22a109.51 109.51 0 00-35.06 71.57A14 14 0 0032 142h90v58a30 30 0 0060 0 6 6 0 00-12 0 18 18 0 01-36 0v-58h90a14 14 0 0014-15.21zm-12.49 2.56a2 2 0 01-1.51.65H32a2 2 0 01-1.49-.65 2 2 0 01-.53-1.56 98.43 98.43 0 01164.78-63.74A97.5 97.5 0 01226 127.79a2 2 0 01-.54 1.56z"/></svg>;
export default UmbrellaSimpleLight;
