// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UploadSimpleThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M220 144v64a4 4 0 01-4 4H40a4 4 0 01-4-4v-64a4 4 0 018 0v60h168v-60a4 4 0 018 0zM90.83 74.83L124 41.66V144a4 4 0 008 0V41.66l33.17 33.17a4 4 0 105.66-5.66l-40-40a4 4 0 00-5.66 0l-40 40a4 4 0 005.66 5.66z"/></svg>;
export default UploadSimpleThin;
