// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UsbThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M250.22 124.67l-48-32A4 4 0 00196 96v28H68V72a4 4 0 014-4h36.29a28 28 0 100-8H72a12 12 0 00-12 12v52H8a4 4 0 000 8h52v52a12 12 0 0012 12h36v12a12 12 0 0012 12h32a12 12 0 0012-12v-32a12 12 0 00-12-12h-32a12 12 0 00-12 12v12H72a4 4 0 01-4-4v-52h128v28a4 4 0 002.11 3.53 4 4 0 004.11-.2l48-32a4 4 0 000-6.66zM136 44a20 20 0 11-20 20 20 20 0 0120-20zm-20 132a4 4 0 014-4h32a4 4 0 014 4v32a4 4 0 01-4 4h-32a4 4 0 01-4-4zm88-23.47v-49.06L240.79 128z"/></svg>;
export default UsbThin;
