// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UserMinusFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M198.13 194.85A8 8 0 01192 208H24a8 8 0 01-6.12-13.15c14.94-17.78 33.52-30.41 54.17-37.17a68 68 0 1171.9 0c20.65 6.76 39.23 19.39 54.18 37.17zM248 128h-48a8 8 0 000 16h48a8 8 0 000-16z"/></svg>;
export default UserMinusFill;
