// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VideoFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M232 208a8 8 0 01-8 8H32a8 8 0 010-16h192a8 8 0 018 8zm0-152v112a16 16 0 01-16 16H40a16 16 0 01-16-16V56a16 16 0 0116-16h176a16 16 0 0116 16zm-68 56a8 8 0 00-3.41-6.55l-40-28A8 8 0 00108 84v56a8 8 0 0012.59 6.55l40-28A8 8 0 00164 112z"/></svg>;
export default VideoFill;
