// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VideoCamera = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M251.77 73a8 8 0 00-8.21.39L208 97.05V72a16 16 0 00-16-16H32a16 16 0 00-16 16v112a16 16 0 0016 16h160a16 16 0 0016-16v-25l35.56 23.71A8 8 0 00248 184a8 8 0 008-8V80a8 8 0 00-4.23-7zM192 184H32V72h160v112zm48-22.95l-32-21.33v-23.44L240 95z"/></svg>;
export default VideoCamera;
