// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VinylRecordFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 24a104 104 0 10104 104A104.11 104.11 0 00128 24zM72 128a8 8 0 01-16 0 72.08 72.08 0 0172-72 8 8 0 010 16 56.06 56.06 0 00-56 56zm32 0a24 24 0 1124 24 24 24 0 01-24-24zm24 72a8 8 0 010-16 56.06 56.06 0 0056-56 8 8 0 0116 0 72.08 72.08 0 01-72 72z"/></svg>;
export default VinylRecordFill;
