// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VirtualRealityLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M121.62 98.11l-24 64a6 6 0 01-11.24 0l-24-64a6 6 0 0111.24-4.22l18.38 49 18.38-49a6 6 0 1111.24 4.22zM254 128a78.09 78.09 0 01-78 78H80a78 78 0 010-156h96a78.09 78.09 0 0178 78zm-12 0a66.08 66.08 0 00-66-66H80a66 66 0 000 132h96a66.08 66.08 0 0066-66zm-63.8 9.76l11 19.26a6 6 0 01-10.42 6l-12.07-21.12a27.06 27.06 0 01-2.71.1h-14v18a6 6 0 01-12 0V96a6 6 0 016-6h20a26 26 0 0114.2 47.76zM164 130a14 14 0 000-28h-14v28z"/></svg>;
export default VirtualRealityLight;
