// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VoicemailLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 74a54 54 0 00-33.89 96H89.89A54 54 0 1056 182h144a54 54 0 000-108zM14 128a42 42 0 1142 42 42 42 0 01-42-42zm186 42a42 42 0 1142-42 42 42 0 01-42 42z"/></svg>;
export default VoicemailLight;
