// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VoicemailThin = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M200 76a52 52 0 00-27.66 96H83.66A52 52 0 1056 180h144a52 52 0 000-104zM12 128a44 44 0 1144 44 44.05 44.05 0 01-44-44zm188 44a44 44 0 1144-44 44.05 44.05 0 01-44 44z"/></svg>;
export default VoicemailThin;
