// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WallDuotone = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M128 104H32V56h96zm48 0v48h-48v48h96v-96z" opacity=".2"/><path d="M224 48H32a8 8 0 00-8 8v144a8 8 0 008 8h192a8 8 0 008-8V56a8 8 0 00-8-8zM88 144v-32h80v32zm-48 0v-32h32v32zm144-32h32v32h-32zm32-16h-80V64h80zm-96-32v32H40V64zm-80 96h80v32H40zm96 32v-32h80v32z"/></svg>;
export default WallDuotone;
