// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WarehouseBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 180h-4V61.13l6.51-1.39a12 12 0 10-5-23.47l-224 48A12 12 0 0016 108a12.21 12.21 0 002.53-.26l1.48-.32V180H16a12 12 0 000 24h224a12 12 0 000-24zM44 102.27l168-36V180h-20v-60a12 12 0 00-12-12H76a12 12 0 00-12 12v60H44zM168 144H88v-12h80zm-80 24h80v12H88z"/></svg>;
export default WarehouseBold;
