// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WaveSquareLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M238 128v56a6 6 0 01-6 6H128a6 6 0 01-6-6V78H30v50a6 6 0 01-12 0V72a6 6 0 016-6h104a6 6 0 016 6v106h92v-50a6 6 0 0112 0z"/></svg>;
export default WaveSquareLight;
