// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WaveSquare = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M240 128v56a8 8 0 01-8 8H128a8 8 0 01-8-8V80H32v48a8 8 0 01-16 0V72a8 8 0 018-8h104a8 8 0 018 8v104h88v-48a8 8 0 0116 0z"/></svg>;
export default WaveSquare;
