// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WaveTriangleLight = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M236.86 131.51l-52 72a6 6 0 01-9.72 0L76 66.25l-47.14 65.26a6 6 0 11-9.72-7l52-72a6 6 0 019.72 0L180 189.75l47.14-65.26a6 6 0 019.72 7z"/></svg>;
export default WaveTriangleLight;
