// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const WebcamFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M160 104a32 32 0 11-32-32 32 32 0 0132 32zm72 104a8 8 0 01-8 8H32a8 8 0 010-16h88v-16.4a80 80 0 1116 0V200h88a8 8 0 018 8zm-104-56a48 48 0 10-48-48 48.05 48.05 0 0048 48z"/></svg>;
export default WebcamFill;
