// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const XBold = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor" {...props}><path d="M208.49 191.51a12 12 0 01-17 17L128 145l-63.51 63.49a12 12 0 01-17-17L111 128 47.51 64.49a12 12 0 0117-17L128 111l63.51-63.52a12 12 0 0117 17L145 128z"/></svg>;
export default XBold;
