'use strict';

/**
 * Converts an SVGO-processed SVG string into a React TSX component string.
 */

// Map of SVG/HTML XML attribute names to React JSX camelCase equivalents.
// Only attributes that differ from the React JSX name are listed.
const SVG_TO_JSX_ATTRS = {
  class: 'className',
  'clip-path': 'clipPath',
  'clip-rule': 'clipRule',
  'color-interpolation': 'colorInterpolation',
  'color-interpolation-filters': 'colorInterpolationFilters',
  'color-rendering': 'colorRendering',
  'dominant-baseline': 'dominantBaseline',
  'enable-background': 'enableBackground',
  'fill-opacity': 'fillOpacity',
  'fill-rule': 'fillRule',
  'flood-color': 'floodColor',
  'flood-opacity': 'floodOpacity',
  'font-family': 'fontFamily',
  'font-size': 'fontSize',
  'font-style': 'fontStyle',
  'font-weight': 'fontWeight',
  'glyph-name': 'glyphName',
  'image-rendering': 'imageRendering',
  'letter-spacing': 'letterSpacing',
  'lighting-color': 'lightingColor',
  'marker-end': 'markerEnd',
  'marker-mid': 'markerMid',
  'marker-start': 'markerStart',
  'shape-rendering': 'shapeRendering',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'stroke-dasharray': 'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-miterlimit': 'strokeMiterlimit',
  'stroke-opacity': 'strokeOpacity',
  'stroke-width': 'strokeWidth',
  'text-anchor': 'textAnchor',
  'text-decoration': 'textDecoration',
  'text-rendering': 'textRendering',
  'unicode-bidi': 'unicodeBidi',
  'vector-effect': 'vectorEffect',
  'word-spacing': 'wordSpacing',
  'writing-mode': 'writingMode',
  'xlink:actuate': 'xlinkActuate',
  'xlink:arcrole': 'xlinkArcrole',
  'xlink:href': 'href',
  'xlink:role': 'xlinkRole',
  'xlink:show': 'xlinkShow',
  'xlink:title': 'xlinkTitle',
  'xlink:type': 'xlinkType',
  'xml:base': 'xmlBase',
  'xml:lang': 'xmlLang',
  'xml:space': 'xmlSpace',
};

/**
 * Rename all SVG attribute names to their JSX equivalents throughout the string.
 */
function convertAttrs(svg) {
  svg = svg.replace(/\s+xmlns:xlink="[^"]*"/g, '');
  for (const [from, to] of Object.entries(SVG_TO_JSX_ATTRS)) {
    const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`(\\s)${escaped}(=["'])`, 'g');
    svg = svg.replace(re, `$1${to}$2`);
  }
  return svg;
}

/**
 * Insert `{...props}` into the root <svg> opening tag, just before its closing >.
 */
function insertPropsSpread(svg) {
  let i = 4; // start after '<svg'
  let inAttr = false;
  let quoteChar = null;
  while (i < svg.length) {
    const c = svg[i];
    if (inAttr) {
      if (c === quoteChar) inAttr = false;
    } else {
      if (c === '"' || c === "'") {
        inAttr = true;
        quoteChar = c;
      } else if (c === '>') {
        const selfClose = svg[i - 1] === '/';
        if (selfClose) {
          return svg.slice(0, i - 1) + ' {...props}/>' + svg.slice(i + 1);
        }
        return svg.slice(0, i) + ' {...props}>' + svg.slice(i + 1);
      }
    }
    i++;
  }
  return svg;
}

/**
 * Identifiers that conflict with the generated file's own imports and must be
 * prefixed with 'Svg' to avoid a compile-time name clash.
 */
const RESERVED_NAMES = new Set(['React', 'Component', 'Fragment', 'createElement']);

/**
 * Derive a valid PascalCase React component name from an icon filename (no extension).
 * Examples:
 *   account     -> Account
 *   arrow-down  -> ArrowDown
 *   1f004       -> Svg1f004   (starts with digit -> prefixed)
 *   react       -> SvgReact   (conflicts with the React import alias)
 */
function toComponentName(iconName) {
  const pascal = iconName
    .split(/[-_.\s]+/)
    .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : ''))
    .join('');
  return /^\d/.test(pascal) || RESERVED_NAMES.has(pascal) ? 'Svg' + pascal : pascal;
}

/**
 * Convert an SVGO-processed SVG string to a TSX React component string.
 */
function svgToTsx(svgContent, iconName) {
  let svg = svgContent.trim();

  // 1. Convert attribute names to JSX equivalents
  svg = convertAttrs(svg);

  // 2. Inject {...props} spread into the root <svg> tag
  svg = insertPropsSpread(svg);

  const componentName = toComponentName(iconName);

  return [
    '// This file is autogenerated by "make react_icons", do not edit it.',
    "import * as React from 'react';",
    `const ${componentName} = (props: React.SVGProps<SVGSVGElement>) => ${svg};`,
    `export default ${componentName};`,
    '',
  ].join('\n');
}

module.exports = {svgToTsx, toComponentName, convertAttrs, insertPropsSpread};
