// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Svg1SquareFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-1-square-fill" viewBox="0 0 16 16" {...props}><path d="M2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2zm7.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383z"/></svg>;
export default Svg1SquareFill;
