// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Brilliance = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-brilliance" viewBox="0 0 16 16" {...props}><path d="M8 16A8 8 0 118 0a8 8 0 010 16M1 8a7 7 0 007 7 3.5 3.5 0 100-7 3.5 3.5 0 110-7 7 7 0 00-7 7"/></svg>;
export default Brilliance;
