// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Calendar2Heart = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-calendar2-heart" viewBox="0 0 16 16" {...props}><path fillRule="evenodd" d="M4 .5a.5.5 0 00-1 0V1H2a2 2 0 00-2 2v11a2 2 0 002 2h12a2 2 0 002-2V3a2 2 0 00-2-2h-1V.5a.5.5 0 00-1 0V1H4zM1 3a1 1 0 011-1h12a1 1 0 011 1v11a1 1 0 01-1 1H2a1 1 0 01-1-1zm2 .5a.5.5 0 00-.5.5v1a.5.5 0 00.5.5h10a.5.5 0 00.5-.5V4a.5.5 0 00-.5-.5zm5 4.493c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132"/></svg>;
export default Calendar2Heart;
