// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretRightSquareFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-caret-right-square-fill" viewBox="0 0 16 16" {...props}><path d="M0 2a2 2 0 012-2h12a2 2 0 012 2v12a2 2 0 01-2 2H2a2 2 0 01-2-2zm5.5 10a.5.5 0 00.832.374l4.5-4a.5.5 0 000-.748l-4.5-4A.5.5 0 005.5 4z"/></svg>;
export default CaretRightSquareFill;
