// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretUpFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-caret-up-fill" viewBox="0 0 16 16" {...props}><path d="M7.247 4.86l-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 00.753-1.659l-4.796-5.48a1 1 0 00-1.506 0z"/></svg>;
export default CaretUpFill;
