// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretLeft = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-caret-left" viewBox="0 0 16 16" {...props}><path d="M10 12.796V3.204L4.519 8zm-.659.753l-5.48-4.796a1 1 0 010-1.506l5.48-4.796A1 1 0 0111 3.204v9.592a1 1 0 01-1.659.753"/></svg>;
export default CaretLeft;
