// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const DistributeVertical = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-distribute-vertical" viewBox="0 0 16 16" {...props}><path fillRule="evenodd" d="M1 1.5a.5.5 0 00.5.5h13a.5.5 0 000-1h-13a.5.5 0 00-.5.5m0 13a.5.5 0 00.5.5h13a.5.5 0 000-1h-13a.5.5 0 00-.5.5"/><path d="M2 7a1 1 0 011-1h10a1 1 0 011 1v2a1 1 0 01-1 1H3a1 1 0 01-1-1z"/></svg>;
export default DistributeVertical;
