// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Dot = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-dot" viewBox="0 0 16 16" {...props}><path d="M8 9.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3"/></svg>;
export default Dot;
