// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const FilePostFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-file-post-fill" viewBox="0 0 16 16" {...props}><path d="M12 0H4a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V2a2 2 0 00-2-2M4.5 3h5a.5.5 0 010 1h-5a.5.5 0 010-1m0 2h7a.5.5 0 01.5.5v8a.5.5 0 01-.5.5h-7a.5.5 0 01-.5-.5v-8a.5.5 0 01.5-.5"/></svg>;
export default FilePostFill;
