// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const GripVertical = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-grip-vertical" viewBox="0 0 16 16" {...props}><path d="M7 2a1 1 0 11-2 0 1 1 0 012 0m3 0a1 1 0 11-2 0 1 1 0 012 0M7 5a1 1 0 11-2 0 1 1 0 012 0m3 0a1 1 0 11-2 0 1 1 0 012 0M7 8a1 1 0 11-2 0 1 1 0 012 0m3 0a1 1 0 11-2 0 1 1 0 012 0m-3 3a1 1 0 11-2 0 1 1 0 012 0m3 0a1 1 0 11-2 0 1 1 0 012 0m-3 3a1 1 0 11-2 0 1 1 0 012 0m3 0a1 1 0 11-2 0 1 1 0 012 0"/></svg>;
export default GripVertical;
