// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const PentagonFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-pentagon-fill" viewBox="0 0 16 16" {...props}><path d="M7.685.256a.5.5 0 01.63 0l7.421 6.03a.5.5 0 01.162.538l-2.788 8.827a.5.5 0 01-.476.349H3.366a.5.5 0 01-.476-.35L.102 6.825a.5.5 0 01.162-.538l7.42-6.03z"/></svg>;
export default PentagonFill;
