// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ShiftFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-shift-fill" viewBox="0 0 16 16" {...props}><path d="M7.27 2.047a1 1 0 011.46 0l6.345 6.77c.6.638.146 1.683-.73 1.683H11.5v3a1 1 0 01-1 1h-5a1 1 0 01-1-1v-3H1.654C.78 10.5.326 9.455.924 8.816z"/></svg>;
export default ShiftFill;
