// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const StopBtnFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-stop-btn-fill" viewBox="0 0 16 16" {...props}><path d="M0 12V4a2 2 0 012-2h12a2 2 0 012 2v8a2 2 0 01-2 2H2a2 2 0 01-2-2m6.5-7A1.5 1.5 0 005 6.5v3A1.5 1.5 0 006.5 11h3A1.5 1.5 0 0011 9.5v-3A1.5 1.5 0 009.5 5z"/></svg>;
export default StopBtnFill;
