// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Substack = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-substack" viewBox="0 0 16 16" {...props}><path d="M15 3.604H1v1.891h14v-1.89zM1 7.208V16l7-3.926L15 16V7.208zM15 0H1v1.89h14z"/></svg>;
export default Substack;
