// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const UsbDriveFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-usb-drive-fill" viewBox="0 0 16 16" {...props}><path d="M6 .5a.5.5 0 01.5-.5h4a.5.5 0 01.5.5v4H6zM7 1v1h1V1zm2 0v1h1V1zM5.5 5a.5.5 0 00-.5.5V15a1 1 0 001 1h5a1 1 0 001-1V5.5a.5.5 0 00-.5-.5z"/></svg>;
export default UsbDriveFill;
