// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const VolumeOffFill = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-volume-off-fill" viewBox="0 0 16 16" {...props}><path d="M10.717 3.55A.5.5 0 0111 4v8a.5.5 0 01-.812.39L7.825 10.5H5.5A.5.5 0 015 10V6a.5.5 0 01.5-.5h2.325l2.363-1.89a.5.5 0 01.529-.06"/></svg>;
export default VolumeOffFill;
