// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Minus = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M2.25 9.556c0-.307.248-.556.555-.556h14.433a.555.555 0 0 1 0 1.11H2.805a.555.555 0 0 1-.555-.554z" fill="#000" fillRule="evenodd"/></svg>;
export default Minus;
