// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Upload = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M18.098 17.43H2.555A.555.555 0 0 1 2 16.876v-4.441a.555.555 0 0 1 1.11 0v3.886h14.433v-3.886a.555.555 0 0 1 1.11 0v4.44a.556.556 0 0 1-.555.557zM13.26 7.833l-2.377-2.775v8.487a.555.555 0 0 1-1.11 0V5.057L7.392 7.832a.56.56 0 1 1-.792-.792L9.93 3.157A.55.55 0 0 1 10.343 3h.003c.138.006.262.06.357.148.006.005.015.003.021.008l3.328 3.884a.56.56 0 1 1-.793.792z" fill="#000" fillRule="evenodd"/></svg>;
export default Upload;
