// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ApmTrace = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><defs><path id="a" d="M2 0h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2zm.5 2h10a.5.5 0 1 1 0 1h-10a.5.5 0 0 1 0-1zm1 3h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1 0-1zm2 3h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1zm3 3h5a.5.5 0 1 1 0 1h-5a.5.5 0 1 1 0-1z"/></defs><use href="#a"/></svg>;
export default ApmTrace;
