// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const EditorItalic = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}><defs><path id="a" d="M8.16 12H9.5a.5.5 0 1 1 0 1h-4a.5.5 0 1 1 0-1h1.639l1.7-8H7.5a.5.5 0 0 1 0-1h4a.5.5 0 1 1 0 1H9.861l-1.7 8z"/></defs><use href="#a"/></svg>;
export default EditorItalic;
