// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Empty = (props: React.SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" {...props}/>;
export default Empty;
