// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const CaretDown = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M4.182 6.182a.45.45 0 01.636 0L7.5 8.864l2.682-2.682a.45.45 0 01.636.636l-3 3a.45.45 0 01-.636 0l-3-3a.45.45 0 010-.636z" fill="currentColor"/></svg>;
export default CaretDown;
