// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const ChevronRight = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M6.158 3.135a.5.5 0 01.707.023l3.75 4a.5.5 0 010 .684l-3.75 4a.5.5 0 11-.73-.684L9.566 7.5l-3.43-3.658a.5.5 0 01.023-.707z" fill="currentColor"/></svg>;
export default ChevronRight;
