// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Dot = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M7.5 9.125a1.625 1.625 0 100-3.25 1.625 1.625 0 000 3.25zm0 1a2.625 2.625 0 100-5.25 2.625 2.625 0 000 5.25z" fill="currentColor"/></svg>;
export default Dot;
