// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Slash = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M4.109 14L9.466 1h1.352L5.46 14H4.109z" fill="currentColor"/></svg>;
export default Slash;
