// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Square = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M1 1h13v13H1V1zm1 1v11h11V2H2z" fill="currentColor"/></svg>;
export default Square;
