// This file is autogenerated by "make react_icons", do not edit it.
import * as React from 'react';
const Stop = (props: React.SVGProps<SVGSVGElement>) => <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path fillRule="evenodd" clipRule="evenodd" d="M2 3a1 1 0 011-1h9a1 1 0 011 1v9a1 1 0 01-1 1H3a1 1 0 01-1-1V3zm10 0H3v9h9V3z" fill="currentColor"/></svg>;
export default Stop;
